// ============================================================================
//  ALPHAFOLD EXPLAINED  ·  screensaver gallery builder  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Reads AlphaFold DB models of proteins with different folds and writes
//  saver-data.js. Only the screensaver (window.snSaver in main.js) imports
//  saver-data.js, and it imports it when the saver starts. The page cards
//  keep the one protein of data.js (SUMO1).
//
//  GET THE INPUT FILES (AlphaFold DB, CC-BY 4.0):
//      d="$(mktemp -d)" && cd "$d" && for u in P02144 P42212 P60174 \
//        P0DP23 P61769 P09493 P37840 P04637 P62873 P00568 P13489 P02945 \
//        P24941 P61626; do curl -sfSO \
//        "https://alphafold.ebi.ac.uk/files/AF-$u-F1-model_v6.pdb"; done
//  RUN:
//      node <repo>/stella-nova/pages/alphafold-explained/build-saver.mjs "$d"
//
//  OUTPUT FORMAT (one record per protein in GALLERY)
//    id, uni, name, fold .. AlphaFold DB entry, UniProt, label, fold class
//    nat .................. heavy atoms per residue
//    xyz .................. x, y, z, element (0 C 1 N 2 O 3 S) per atom, in
//                           residue order. x, y, z are integers in 0.1 Å,
//                           centered on the mean CA of the pLDDT >= 70 core.
//                           The first three atoms of a residue are N, CA, C.
//    plddt ................ pLDDT per residue (B-factor column)
//
//  SECTION MAP   (jump with grep -n "<anchor>" build-saver.mjs)
//      protein list .... "const LIST"
//      pdb parse ....... "function parsePdb"
//      output .......... "const js"
// ============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const dir = process.argv[2];
if (!dir) { console.error('usage: node build-saver.mjs <dir with AF-*-F1-model_v6.pdb files>'); process.exit(1); }

// One entry for each fold class. The order is the order of the gallery.
const LIST = [
  ['P02144', 'Myoglobin (human)', 'globin · all α'],
  ['P42212', 'Green fluorescent protein (Aequorea victoria)', 'β-barrel, 11 strands'],
  ['P60174', 'Triosephosphate isomerase (human)', 'TIM barrel · α/β'],
  ['P0DP23', 'Calmodulin-1 (human)', 'EF-hand dumbbell · all α'],
  ['P61769', 'β2-microglobulin (human)', 'immunoglobulin β-sandwich'],
  ['P09493', 'Tropomyosin α-1 (human)', 'coiled coil, one long helix'],
  ['P37840', 'α-Synuclein (human)', 'intrinsically disordered'],
  ['P04637', 'p53 tumour suppressor (human)', 'DNA-binding core, disordered tails'],
  ['P62873', 'Gβ1 (human G protein β subunit)', 'WD40 β-propeller, 7 blades'],
  ['P00568', 'Adenylate kinase 1 (human)', 'P-loop α/β'],
  ['P13489', 'Ribonuclease inhibitor (human)', 'leucine-rich repeat horseshoe'],
  ['P02945', 'Bacteriorhodopsin (Halobacterium salinarum)', 'membrane, 7 helices'],
  ['P24941', 'CDK2 (human cyclin-dependent kinase 2)', 'protein kinase, two lobes'],
  ['P61626', 'Lysozyme C (human)', 'α+β, two domains'],
];
const EL = ['C', 'N', 'O', 'S'];

// One record for each residue: pLDDT and heavy atoms in file order.
function parsePdb(text) {
  const res = [];
  for (const line of text.split('\n')) {
    if (!line.startsWith('ATOM')) continue;
    const name = line.slice(12, 16).trim(), seq = +line.slice(22, 26);
    const p = [+line.slice(30, 38), +line.slice(38, 46), +line.slice(46, 54)];
    let r = res[res.length - 1];
    if (!r || r.seq !== seq) { r = { seq, plddt: +line.slice(60, 66), atoms: [] }; res.push(r); }
    r.atoms.push({ name, el: EL.indexOf(line.slice(76, 78).trim()), p });
  }
  for (const r of res) {
    const n = r.atoms.slice(0, 3).map(a => a.name).join(' ');
    if (n !== 'N CA C') throw new Error(`residue ${r.seq}: first atoms are ${n}, not N CA C`);
    if (r.atoms.some(a => a.el < 0)) throw new Error(`residue ${r.seq}: element not in ${EL}`);
  }
  return res;
}

const GALLERY = LIST.map(([uni, name, fold]) => {
  const id = `AF-${uni}-F1-model_v6`;
  const res = parsePdb(readFileSync(join(dir, id + '.pdb'), 'utf8'));
  // Center on the mean CA of the core. With no core, center on all CA.
  const core = res.filter(r => r.plddt >= 70);
  const use = core.length >= 10 ? core : res;
  const ctr = [0, 1, 2].map(k => use.reduce((s, r) => s + r.atoms[1].p[k], 0) / use.length);
  const xyz = [];
  for (const r of res) for (const a of r.atoms) xyz.push(...a.p.map((v, k) => Math.round((v - ctr[k]) * 10)), a.el);
  return { id, uni, name, fold, nat: res.map(r => r.atoms.length), xyz, plddt: res.map(r => r.plddt) };
});

const js = `// ============================================================================
//  ALPHAFOLD EXPLAINED  ·  screensaver gallery  (GENERATED by build-saver.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Run build-saver.mjs again.
//  Structures and pLDDT: AlphaFold DB, CC-BY 4.0. Entries:
${GALLERY.map(g => `//    ${g.id}  ${g.name}`).join('\n')}
//  xyz: [x, y, z, element (0 C 1 N 2 O 3 S)] per atom, x y z in 0.1 Å.
//  nat: heavy atoms per residue. Each residue starts N, CA, C.
// ============================================================================
export const GALLERY = ${JSON.stringify(GALLERY)};
`;
const dest = fileURLToPath(new URL('./saver-data.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
for (const g of GALLERY) console.log(g.id, 'residues', g.nat.length, 'atoms', g.xyz.length / 4,
  'mean pLDDT', (g.plddt.reduce((a, b) => a + b, 0) / g.plddt.length).toFixed(1));
