// ============================================================================
//  SCREENSAVER CATALOG  ·  lib/screensaver-catalog.js
// ----------------------------------------------------------------------------
//  The tier of each page for screensaver mode (lib/screensaver.js), that is,
//  how much work the page needs before it runs calm and full-frame with no
//  user. The menu shows the tier, and "default: true" puts a page in the
//  default list. "hook: true" marks a page that defines window.snSaver.
//
//  Classic script, loaded by the shell before lib/screensaver.js. It sets
//  window.SN_SAVER_CATALOG = { tiers, pages }.
//
//  grep -n targets
//    tier names ........... "tiers:"
//    page table ........... "pages:"
// ============================================================================
window.SN_SAVER_CATALOG = {
  tiers: {
    1: { name: 'Generic', text: 'The generic mode (largest canvas, full-frame) is enough.' },
    2: { name: 'Preset', text: 'A small hook: hide the GUI, set a preset, slow time.' },
    3: { name: 'Autopilot', text: 'Needs scripted motion: a camera tour or cycled presets.' },
    4: { name: 'Authored', text: 'A tool or editor: needs made content and an autopilot.' },
    5: { name: 'Unsuitable', text: 'Text, forms, microphone or network: not for a screensaver.' },
  },
  // From tools/screensaver-survey.json. Nav order. A page with a hook gets
  // hook: true and default: true when its hook lands.
  pages: {
    'wiki': { tier: 5, note: 'Exclude. stella-nova/pages/wiki/main.js is a hash router that draws text articles from window.SN_DATA into #view;' },
    'research': { tier: 5, note: 'Exclude. research/main.js draws a tech-tree board of DOM node cards and SVG paths (main.js:213 createElementNS path).' },
    'guide': { tier: 3, hook: true, note: 'Not a default (user, 2026-10-02). Long-form tutorial with six small 2D canvases, one per figure (index.html:62,81,100,120,140,164).' },
    'planner': { tier: 3, default: true, hook: true, note: 'Editor, but it ships a built-in layout: PL.example() (planner/model.js:318), which boot() loads when there is no share hash and no localStorage key ’sn-planner-' },
    'crafting': { tier: 5, note: 'Exclude. crafting/main.js builds a production-chain explorer from DOM cards and an SVG wire layer (main.js:137 svg.wires, main.js:161 paths).' },
    'shipdesigner': { tier: 2, default: true, hook: true, note: 'The fleet canvas (#fleetCanvas, index.html) already flies on its own.' },
    'flagdesigner': { tier: 5, note: 'Unsuitable (user, 2026-10-02): presets can read as real national flags. Its hook stays in the page.' },
    'selection': { tier: 3, default: true, hook: true, note: '#cv fills main#stage.' },
    'behaviors': { tier: 5, note: 'Exclude. A static written page.' },
    'controls': { tier: 5, note: 'Exclude. A key-binding reference: controls/main.js builds a DOM keyboard (#board, #arrows, #keyGrid) and a list from SN_DATA.controls.' },
    'social-dynamics': { tier: 5, note: 'Exclude. A text page: social-dynamics/main.js fills [data-fill] blocks with wiki links and static ring SVGs (main.js:109).' },
    'fortom': { tier: 5, note: 'Exclude. pages/for-tom/index.html is a long scrolling design doc (ASTROTECHS OPS: .topnav, .bootbar, hero, numbered <section class="section"> blocks, register table).' },
    'starward-belt': { tier: 3, default: true, hook: true, note: 'Generic fallback is wrong here: it would pin canvas#field (dust only) and hide svg#overlay, which holds every station and route.' },
    'translate': { tier: 5, note: 'Exclude. translate/main.js:1-40 is a crowd-translation editor: language picker, text rows, localStorage edits (sn_tr_v5), TOML export and a formsubmit.co POST (' },
    'solar': { tier: 5, note: 'Exclude by default. It is a light-theme three-column analysis dashboard for one stadium site;' },
    'matlab': { tier: 3, default: true, hook: true, note: 'Editor, but it boots into a material: presets.js:565-576 loads DEFAULT_PRESET ’rustedIron’ and there are 16 recipe presets (MATERIAL_PRESETS, presets.js:438-461' },
    'hohmann': { tier: 3, default: true, hook: true, note: 'Idle it only shows planets orbiting with no transfer;' },
    'leo': { tier: 3, default: true, hook: true, note: 'Idle it shows the globe with satellites moving at SIM.speed=3 (main.js:128-134), which is near-static, and the camera does not move.' },
    'gravity': { tier: 2, default: true, hook: true, note: 'It moves on its own (laplace preset, loop() main.js:752), but the generic fallback breaks sizing: resizeCanvas() (main.js:297) sets canvas.width and inline styl' },
    'forge': { tier: 3, default: true, hook: true, note: 'Starts with only a holo wireframe placeholder and ’#empty-state: select parameters and generate’ (index.html:137);' },
    'galaxy': { tier: 1, default: true, note: 'Generic fallback is enough: one full-window canvas#c (index.html:33), resize() sizes from window.innerWidth/innerHeight (main.js resize, ~line 181) so the pin +' },
    'blackhole': { tier: 1, default: true, hook: true, note: 'Generic fallback is enough: frame() starts unconditionally (main.js:282) even before the GPU warning is dismissed (warnDismissed only gates the UI reveal, main.' },
    'wormhole': { tier: 2, default: true, hook: true, note: 'Generic fallback already gives a slow orbit (autoSpin, SPIN_SPEED 0.0008, main.js:84-85) and RenderScale sizes from the window, so tier 1 would show.' },
    'orbital': { tier: 2, default: true, hook: true, note: 'Idle motion already exists: default S (core.js:21-33) has n=3,l=1,m=1, animateFlow=true, B-field tracers on, so particles flow along J (main.js loop, animateFlow at m!=0).' },
    'molecular-bond': { tier: 3, default: true, hook: true, note: 'Idle frame loop (main.js:466) only renders;' },
    'hydrogen-table': { tier: 3, default: true, hook: true, note: 'Page is a scrolling DOM table of many tile canvases (main.js layout/addShell);' },
    'qave': { tier: 2, default: true, hook: true, note: 'Already plays and orbits idle: VS.playing=true, speed 2, autoRotate true speed 0.55 (core.js:29-31,50).' },
    'qft-flow': { tier: 'excluded', note: 'Pulled from the screensaver by the user (2026-10-02). Its hook stays in the page.' },
    'qft-store': { tier: 5, note: 'Exclude. Page is a form: payload textarea #payload, register steppers, SVG dials built in buildDials (main.js:123), decoded text and badge.' },
    'frqi': { tier: 3, default: true, hook: true, note: 'Stack autorotates idle (initGL, main.js:264, autoRotateSpeed 0.5) but layers do not advance.' },
    'protein-viewer': { tier: 3, default: true, hook: true, note: 'Draws only when S.dirty (app/loop.js);' },
    'protein-folding': { tier: 2, default: true, hook: true, note: 'Sim workers run idle (S.running=true) and camera orbits after 2 s idle (S.orbit=!REDUCED, main.js:541).' },
    'alphafold': { tier: 3, default: true, hook: true, note: 'Long scrolling explainer;' },
    'human-skull': { tier: 3, default: true, hook: true, note: 'Intro flies parts in and opens Anatomy layout;' },
    'human-skeleton': { tier: 3, default: true, hook: true, note: 'Loads eight groups with dissolve-in, then static: S.show.spin=false (app/state.js:24), loop draws only when dirty.' },
    'fluidlab': { tier: 2, default: true, hook: true, note: 'Classic IIFE in pages/fluidlab/main.js;' },
    'wind-tunnel': { tier: 3, default: true, hook: true, note: 'ES module pages/wind-tunnel/main.js;' },
    'tidal-currents': { tier: 2, default: true, hook: true, note: 'Already poster-like: particles animate one model week in 70 s (WEEK_SECONDS main.js:36) and loop;' },
    'ns-equations': { tier: 5, note: 'Shared engine stella-nova/widgets/ns/main.js pinned by window.NS_FIXED_VIEW=’equations’.' },
    'ns-burgers': { tier: 3, default: true, hook: true, note: 'Shared engine widgets/ns/main.js (one file for all six ns-* pages;' },
    'ns-flow2d': { tier: 3, default: true, hook: true, note: 'Shared widgets/ns/main.js.' },
    'ns-flow3d': { tier: 3, default: true, hook: true, note: 'Shared widgets/ns/main.js.' },
    'ns-wave': { tier: 3, default: true, hook: true, note: 'Shared widgets/ns/main.js.' },
    'ns-geometry': { tier: 3, default: true, hook: true, note: 'Article page pages/ns-geometry/main.js (classic script, guarded() figures).' },
    'ns-vortex': { tier: 2, default: true, hook: true, note: 'Shared widgets/ns/main.js.' },
    'magnetlab': { tier: 2, default: true, hook: true, note: 'Classic script, so SIM, magnets, addMagnet, spawnTracers, resize, tracerBudget, updateTracerCount are global lexical bindings;' },
    'biot-savart': { tier: 2, default: true, hook: true, note: 'Classic script; SIM (main.js ~67), wires, preset(name) (main.js:491: ’parallel’,’anti’,’triangle’,’quad’), spawnTracers, resize are global.' },
    'maxwell': { tier: 3, default: true, hook: true, note: 'Classic script; switchEq(i) (law 0..3), STATE (main.js:134), fitScene (main.js:115, reads #card height), resize (main.js:866) are global.' },
    'twenty-to-four': { tier: 2, default: true, hook: true, note: 'Classic script; SIM (main.js ~66: speed, freq, axisDeg, lambda, show*), SRC, resize (main.js:441, measures #stage) are global.' },
    'smith-chart': { tier: 3, default: true, hook: true, note: 'IIFE but exports window.SC (main.js:89): SC.S (state R, X, z0, len, walking, grid), SC.setWalk(on) (main.js:529), SC.setGrid(mode), SC.setDirty(), SC.gridDirty().' },
    'diffraction': { tier: 3, default: true, hook: true, note: 'Classic script; S (main.js:182), PR presets (main.js:490), applyP(pr), animDir/animLoop (main.js:275), recompute, scheduleRecompute, syncBars are global.' },
    'double-slit': { tier: 2, default: true, hook: true, note: 'Classic script; P (main.js:120), init(), setSlider, setPaused, paused, window.__ds (main.js:516) exist.' },
    'polarization': { tier: 2, default: true, hook: true, note: 'ES module; window.__polar (main.js:555) exposes params, setDelta, controls, camera, renderer.' },
    'photon-caustics': { tier: 3, default: true, hook: true, note: 'Own saver tour: 2D scenes with push-ins on the caustic cusps, three pool cross-section shots (sunlight in flight at a slowed c, a floor push-in, the lamp with TIR) and four photon-pulse shots (cup, drop, lens, prism).' },
    'photon-caustics-3d': { tier: 3, default: true, hook: true, note: 'Own saver tour: calm 3D pool shots with slow camera, sun and wave moves, including "A slow swell" and "Nearly still".' },
    'attractorlab': { tier: 2, default: true, hook: true, note: 'Classic script pages/attractorlab/main.js.' },
    'flowlab': { tier: 2, default: true, hook: true, note: 'Classic script pages/flowlab/main.js.' },
    'reaction-diffusion': { tier: 3, default: true, hook: true, note: 'ES module pages/reaction-diffusion/main.js;' },
    'lenia': { tier: 3, default: true, hook: true, note: 'ES module pages/lenia/main.js;' },
    'game-of-life': { tier: 2, default: true, hook: true, note: 'window.__life = {S, loadPattern, setRule, setRunning, randomFill, fitWorld, setLearn, setPanel, ...} (pages/game-of-life/main.js:724), so the hook can live in t' },
    'chordlab': { tier: 5, note: 'Exclude. All content is driven by live mic input (dsp.js:147-159 getUserMedia into one AnalyserNode;' },
    'chordchart': { tier: 5, note: 'Exclude. Reference grid of chord cards rendered as inline SVG (diagrams.js), no canvas and no animation;' },
    'harmonywheel': { tier: 3, hook: true, note: 'Not a default (user, 2026-10-02): the chord pages are not screensaver material. Classic ’use strict’ script;' },
    'resonance-figure': { tier: 1, default: true, hook: true, note: 'Generic fallback is enough: #fig is already position:fixed inset:0 (style.css:38) and resize() reads its client size on window resize;' },
    'resonance-table': { tier: 5, note: 'Exclude. buildGrid (main.js:130) draws each Lissajous cell once into its own small canvas;' },
    'resonance-3d': { tier: 2, default: true, hook: true, note: '#gl is position:fixed inset:0 (style.css:27).' },
    'chladni-plate': { tier: 3, default: true, hook: true, note: 'Sand plate with its own saver tour: glides from resonance to resonance on each plate, labelled with mode, Hz and the plate equation.' },
    'wave-membrane': { tier: 2, default: true, hook: true, note: 'Everything is inside an IIFE (G at main.js:56, view at :96, frame at :347);' },
    'watch-movement': { tier: 3, default: true, hook: true, note: 'three.js page. stage.js already runs a gentle idle orbit: after st.idle > 2.5 s, controls.autoRotate is on with speed -0.5*orbitAmt (stage.js:151-170).' },
    'watch-randomizer': { tier: 3, default: true, hook: true, note: 'Same stage as watch-movement (it imports ../watch-movement/stage.js), so the idle auto-orbit is already present.' },
    'four-stroke-engine': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: explode and assemble cycles, labelled with the Otto cycle and piston kinematics.' },
    'wankel-engine': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: single and twin rotor, labelled with the epitrochoid and chamber cycle.' },
    'differential': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: open, clutch and Torsen units, labelled with the speed and torque split.' },
    'planetary-gearbox': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: simple set and Simpson train, labelled with the Willis equation.' },
    'geneva-cams': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: 4- and 6-slot Geneva drives and a disc cam, whole unit, close view, from above, exploded, part close-ups.' },
    'linkages': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: four-bar coupler curve, Peaucellier straight line and a Jansen leg, upright on a backboard.' },
    'manual-gearbox': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: shifts through five gears while the camera visits the gear set, the synchro, the top and the exploded box, then part close-ups.' },
    'harmonic-drive': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a strain wave gear with a flexing flexspline and a two-disc cycloidal drive, whole, mesh close-up, from above, exploded, part close-ups.' },
    'radial-engine': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a single-row radial engine with a master rod and articulated link rods, whole, close, from above, exploded, part close-ups.' },
    'steam-locomotive': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: Walschaerts valve gear on a steam locomotive, whole engine, valve gear, cut-away piston valve and cylinder, exploded, part close-ups, with a new reverser setting each round.' },
    'gear-types': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: spur, helical, bevel, worm and rack-and-pinion pairs with the line of action and moving contact dots.' },
    'cvt': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a push-belt CVT with sliding sheaves and a full-toroidal traction drive with tilting rollers, in section with the ratio sweeping.' },
    'universal-joints': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a single Cardan joint, double Cardan Z and W and a Rzeppa CV joint, with the shaft angle swinging about a seeded 15-35 deg.' },
    'ball-screw': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: an ACME lead screw that self-locks, a four-start lead screw and a ball screw with recirculating balls; whole stage, the nut cut open, exploded, part close-ups.' },
    'ratchets': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a ratchet and pawl, a 14-sprag clutch and a 3-pawl bicycle freehub, each driving one way and slipping the other.' },
    'sewing-machine': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a cutaway lockstitch machine runs its stitch cycle (needle, take-up lever, rotary hook, feed dog) while the camera tours the head and the hook.' },
    'swashplate-pump': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: 7-, 8- and 9-piston swashplate pumps with the swash angle sweeping, whole pump, pistons close in, side view of the tilt, valve plate kidneys, exploded, part close-ups.' },
    'calculators': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: the Pascaline sautoir carry and the Curta stepped drum, with each carry rippling through the digit wheels.' },
    'enigma-rotors': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: the Enigma I rotor stack types a tape, lights the lamps, shows the double step and follows the current through the wiring in x-ray.' },
    'pendulum-clock': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: a weight-driven pendulum clock with anchor, deadbeat and grasshopper escapements, whole clock, escapement close view, going train, exploded view, part close-ups.' },
    'antikythera': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: the Antikythera gear train (published Freeth tooth counts, original layout) cranked in days, with the pin-and-slot lunar anomaly, the phase ball and the Metonic and Saros spirals.' },
    'pumps': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: an external gear pump, a sliding-vane pump and a two-lobe Roots blower with fluid pockets coloured inlet, sealed and outlet; whole, face on, the mesh, a pocket, exploded, part close-ups.' },
    'fractal-flames': { tier: 3, default: true, hook: true, note: 'Seeded flam3 autopilot (GPL-3.0 port): gated random, mutated or re-symmetrised genomes morph by flam3_interpolate every 5-12 s with slow turn, zoom swell and hue drift, framed in plateBand; the plate shows the leading variations and their WGSL.' },
    'volume-noise': { tier: 3, default: true, hook: true, note: 'TileableVolumeNoise port (MIT): a seeded shuffle of cloud-layer fly-throughs (dawn, noon, dusk), volume-cube orbits, slice sweeps and 1-to-3x3 tiling pull-backs, cut every 5-12 s, with WGSL extracts of worley_cells and perlin_fbm on the plate.' },
    'line-art': { tier: 3, default: true, hook: true, note: 'Rust/wasm port of ln (MIT): a seeded shuffle of the 17 ln example scenes and 16 original scenes of ours (gyroid, carved city, gear train, Menger sponge, lighthouse and more), each pen-plotted with random parameters and themes, credited to Michael Fogleman.' },
    'fishdraw': { tier: 3, default: true, hook: true, note: 'Pen-plotter fish tour (fishdraw by Lingdong Huang, MIT): a seeded shuffle of draw-on, a filling specimen plate, push-ins on scales and fins, and a morph through relatives, on changing paper themes, labelled with the Latin name, seed and a fishdraw.js extract.' },
    'halftone': { tier: 3, default: true, hook: true, note: 'glsl-halftone port (MIT; Gustavson method, public domain): a seeded shuffle of push-ins from the whole image to the dots and rosettes, frequency sweeps, screen-angle turns, ink-set changes and split wipes over NASA photos and two live scenes, cut every 5-12 s, with WGSL extracts on the plate.' },
    'chandrasekhar-limit': { tier: 4, default: true, hook: true, note: 'Authored hook: a seeded shuffle of seven 5-12 s shots (accretion onto the white dwarf, the Type Ia flash, collapse, the black hole with lensing, a nebula fly-through, E(R) losing its minimum, the cutaway), framed in plateBand, with live numbers and real code extracts on the plate.' },
    'image-worlds': { tier: 3, default: true, hook: true, note: 'Gaussian-splat world player (Spark 2.3.1, three r185): a seeded tour of orbit, push, pull, crane and truck shots round the CC0 still-life sample (and any published image-blaster worlds), framed in plateBand, with a viewer.js extract on the plate. Sound stays off.' },
    'nuclear-blast': { tier: 3, default: true, hook: true, note: 'Effects of a burst from the Glasstone & Dolan scaling laws over made-up places, presets named by yield only. The saver plays only the fireball, the cloud rising and the shock crossing a city in slow motion; it draws no rings, fallout or dose (user, 2026-10-06).' },
    'antenna-fields': { tier: 4, default: true, hook: true, note: 'Authored hook: a seeded shuffle of 3 wavefront shot kinds (field lines peeling off a dipole, an array beam sweeping as the wavefronts tilt, a slow zoom into the near field), framed with plateBand.' },
    'market-forecast': { tier: 3, default: true, hook: true, note: 'Chronos forecast tour on a seeded synthetic market (labelled as synthetic): fans unfurling to the close, the day forecast replayed with median trails, a portfolio distribution forming and a backtest sweep, with the forecast numbers and a WGSL/JS extract on the plate.' },
    'ancient-earth': { tier: 3, default: true, hook: true, note: 'Sixteen curated journeys (PALEOMAP plates and PaleoDEMs, CC BY 4.0): named cities ride their plates from deep time to today and end on NASA Blue Marble, for example London, New York and Morocco, India, Australia and Antarctica, Pangea from above, the last ice age. Clouds churn faster as time runs.' },
    'molecules': { tier: 3, default: true, hook: true, note: 'Molecule Explorer (PubChem, public domain; OpenChemLib, BSD-3): a seeded tour of famous molecules drawn as textbook skeletal formulas that lift into 3D, slow orbits in ball-and-stick and space-filling, functional-group highlights and family montages.' },
    'dice': { tier: 3, default: true, hook: true, note: 'Dice Lab (Rapier physics): a seeded director of slow-motion throws, a d20 tumble, macro push-ins on the read faces, a d6 pour filling the bell curve, glass dice and a material turntable.' },
    'roche-limit': { tier: 3, default: true, hook: true, note: 'Planet-fixed, calm saver (camera turn capped at 4 deg/s, no follow cam): the Saturn ring story (an icy moon spirals in, crosses the Roche limit and spreads into a ring), a rings fly-by and a comet pass, debris coloured by collision heat on a plasma map.' },
    'context-free': { tier: 3, default: true, hook: true, note: 'Context Free engine (GPL-2+, compiled to WASM) tour: a seeded shuffle of the example designs with new variations, each grown from the engine partial frames, then a push-in or pan on a zoom-resolution render; time designs play their frames; the plate shows the variation code, shape count and a CFDG extract.' },
    'city-atlas': { tier: 3, default: true, hook: true, note: 'Seeded tour of 21 cities (Overture/OSM buildings, real terrain, ocean currents, a lattice Boltzmann wind layer): slow orbits with varied light and overlays, the next city preloaded so cuts never wait.' },
    'storm-globe': { tier: 3, default: true, hook: true, note: 'Live storm globe (NHC, JTWC, EONET, GFS; deploy snapshot): eased flights from storm to storm, orbits round each eye in the magma wind field, track time-lapses, deep lows and EONET events, wide circulation views, with a solver.wgsl extract on the plate.' },
    'ulam-spiral': { tier: 3, default: true, hook: true, note: 'Shot director over 22 shapes: counted spirals, shape morphs, colour sweeps, Euler n^2 + n + 41 lighting up, zooms from one cell to millions, Miller-Rabin fly-overs near 1e9-1e12 and twin-prime hunts.' },
    'lose-the-modifier': { tier: 4, default: true, hook: true, note: 'Own canvas type tour: a seeded shuffle of five shots (type-in, strike and backspace edits, a family montage, a redline sentence edit, a word-cloud collapse, a kinetic letter drop), cut every 7-13 s, framed in the plate band, labelled with the live pair, its family and a matcher code extract.' },
    'particle-collider': { tier: 4, default: true, hook: true, note: 'Collisions only, no hardware: seeded events (hypothetical energies labelled) shown in the 3D view with labelled products and branched-light trails, flanked or underlined by the transverse and longitudinal diagrams (T, wing or 3D-only by band height); orbit, push-in, along-the-beam and pull-out moves.' },
    'pattern-designer': { tier: 3, default: true, hook: true, note: 'Seeded shuffle of all 48 original patterns, dark palettes and one light modifier (warp, clip, kaleidoscope); each shot draws on stroke by stroke and holds with a slight push-in, cut every 5-12 s, framed in plateBand, with the pattern gen() source on the plate.' },
    'spirograph': { tier: 2, default: true, hook: true, note: 'Mechanism page with its own saver tour: cycles the presets, draws each one calmly with the gears shown, labelled with the hypotrochoid or epitrochoid and gcd(R, r).' },
    'pin-tumbler-lock': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: right and wrong keys against the shear line, pin and wafer locks.' },
    'stirling-engine': { tier: 3, default: true, hook: true, note: 'Mechanism page with its own saver tour: explode and assemble cycles, labelled with the Stirling cycle.' },
    'origami': { tier: 3, default: true, hook: true, note: 'WebGPU. One canvas #gl (index.html:92) draws two panes by scissor rects measured from DOM #pane2d and #pane3d (app/layout.js paneGeom).' },
    'noise': { tier: 2, hook: true, note: 'Not a default (user, 2026-10-02): a mostly static shader table. Generic fallback fails: all 80 tiles are equal-size canvases in #stage, G.hoverOnly=true (state.js G) so no tile animates without pointerenter (gpu.js:73 sets t.hover).' },
    'fields': { tier: 2, default: true, hook: true, note: 'Shared hook for all table-engine pages, written once in lib/table-engine.js inside bootTable (closure owns G:32, GENS:51, tiles:132, makeSurface:197, frame:227)' },
    'sims': { tier: 3, default: true, hook: true, note: 'Uses the shared table-engine snSaver hook (see fields plan: saverCanvas + ssurf drawn via PAGE.draw at the inspected-style path table-engine.js:261, saverTile f' },
    'dot-field': { tier: 2, hook: true, note: 'Not a default (user, 2026-10-02): a mostly static shader table. Shared table-engine snSaver hook (see fields plan).' },
    'polar': { tier: 2, hook: true, note: 'Not a default (user, 2026-10-02): a mostly static shader table. Shared table-engine snSaver hook (see fields plan);' },
    'sdf2d': { tier: 4, default: true, hook: true, note: 'Own build-up saver (pages/sdf2d-table/saver.js): 8 shapes built op by op, the field shown as flowing bands, a sphere-tracing demo or a tile-out.' },
    'color': { tier: 'excluded', note: 'Pulled from the screensaver by the user (2026-10-02). Its saver list stays in the page.' },
    'postfx': { tier: 'excluded', note: 'Pulled from the screensaver by the user (2026-10-02). Its saver list stays in the page.' },
    'sampling': { tier: 2, default: false, hook: true, note: 'Shared table-engine snSaver hook (see fields plan).' },
    'lighting': { tier: 2, hook: true, note: 'Not a default (user, 2026-10-02): a mostly static shader table. Shared table-engine snSaver hook (see fields plan).' },
    'sdf-solids': { tier: 4, default: true, hook: true, note: 'Own build-up saver (pages/sdf-solids-table/saver.js): 11 solids built op by op from primitives, cuts and modifiers.' },
    'liquid-metal': { tier: 2, default: true, hook: true, note: 'Shared table-engine snSaver hook (see fields plan);' },
    'bench': { tier: 4, note: 'Generic fallback fails: no canvas in static HTML;' },
    'explosion': { tier: 2, default: true, hook: true, note: 'Classic (non-module) script, so playback state is global: stella-nova/pages/explosion/main.js:124-128 declares top-level vars playing, speed, zoom, quality, cur' },
    'flare': { tier: 2, default: true, hook: true, note: 'stella-nova/pages/flare/main.js is one async IIFE;' },
    'beam': { tier: 3, default: true, hook: true, note: 'SHARED TABLE HOOK (write once in stella-nova/lib/table-engine.js inside bootTable, ~60 LOC, used by all 7 effects tables and other tables): the engine exposes no globals;' },
    'fire': { tier: 3, default: true, hook: true, note: 'Uses the SHARED TABLE HOOK described for the beam page (window.snSaver in stella-nova/lib/table-engine.js: hide stage/side, set inspected=t directly, pin #m-orb' },
    'fire-ev1': { tier: 3, default: true, hook: true, note: 'Uses the SHARED TABLE HOOK (see beam page plan;' },
    'smoke': { tier: 3, default: true, hook: true, note: 'Uses the SHARED TABLE HOOK (see beam page plan).' },
    'heat-diffraction': { tier: 3, hook: true, note: 'Not a default (user, 2026-10-02). Uses the SHARED TABLE HOOK (see beam page plan).' },
    'heat-metal': { tier: 3, default: true, hook: true, note: 'Uses the SHARED TABLE HOOK (see beam page plan).' },
    'frost': { tier: 3, default: true, hook: true, note: 'Uses the SHARED TABLE HOOK (see beam page plan).' },
    'supernova': { tier: 2, default: true, hook: true, note: 'Single canvas = renderer.domElement inserted before #ui (stella-nova/pages/fractal-orb/main.js:143), no id.' },
    'sdf-lab': { tier: 4, note: 'Editor. Renders only dirty panes (frame() stella-nova/pages/sdf-lab/js/main.js:336), so idle is a frozen image;' },
    'sphere-tracing': { tier: 3, default: true, hook: true, note: 'On-demand renderer: frame() (stella-nova/pages/sphere-tracing/main.js:461) only draws when gpuDirty/ovDirty, so idle is static.' },
    'cornell': { tier: 3, default: true, hook: true, note: 'Classic script; globals SCENE (stella-nova/pages/cornell/main.js:70), CAM {az,el,R,fov,tx,ty,tz} (main.js:81) and APP (main.js:432) returning {init,setMode,setB' },
    'glass-cube': { tier: 3, default: true, hook: true, note: 'Specimen tour: 12 glasses (index, dispersion, tint, interior shape, camera move), one every 5.5 to 7 s, morphing in place.' },
    'platonic': { tier: 1, default: true, hook: true, note: 'Generic is enough: one canvas #c (stella-nova/pages/platonic-mirrors/index.html:36), resize() uses window.innerWidth/innerHeight (main.js:209) with a window res' },
    'branched-flow': { tier: 3, default: true, hook: true, note: 'Seeded look per run: palette, field shape, start time, camera;' },
    'orbs': { tier: 3, default: true, hook: true, note: 'Grid of 66 small WebGPU canvases;' },
    'voxel': { tier: 2, default: true, hook: true, note: 'Already an autopilot: fly mode cruises a planned loop (loop() stella-nova/pages/voxel-flythrough/main.js:652).' },
    'mandelbulber': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
    'shan-shui': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
    'markov-junior': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
    'holocloth': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
    'sdf-clouds': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
    'refraction-table': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
    'thinking-orbs': { tier: 'excluded', note: 'Port of code we did not write; the home page leaves it out too.' },
  },
};
