// engine.js - WebGPU host for the Mandelbulber port: assembles the WGSL program for the
// formulas in use, packs the scene, renders one jittered sample per pixel per pass into an
// accumulation buffer, and presents the average with the image adjustments.
// The engine structure follows Mandelbulber v2 (src/opencl_engine_render_fractal.cpp:
// shader source assembly, the formula switch, per-sample accumulation).
// Copyright (C) 2017-24 Mandelbulber Team, Krzysztof Marczak and contributors.
// Mandelbulber is free software under the GNU General Public License v3 or later.
// This port is also GPL-3.0. See COPYING in the page folder.
//
// API (contract C6): createEngine(canvas) -> { setScene, resize, frame, reset, setPreview,
// onStatus }. frame() submits at most one band and returns at once. A band is every
// bandCount-th stripe of 8 rows (see renderSample in main.wgsl), so each dispatch spreads over
// the whole image and keeps the GPU full. The band count comes from a per-mode cost estimate
// (ms per pixel), so that one GPU submission takes about BAND_TARGET_MS, with at least
// MIN_BAND_PIXELS pixels per band. A slow sample never blocks input: reset() abandons the bands
// in flight (their completions are ignored), and at most MAX_QUEUED submissions wait on the GPU
// queue. Sample 0 overwrites the accumulation buffer, so a reset needs no clear. In preview
// mode a reset keeps the band position, so a long drag still refreshes every band in turn.
// Extras: frame() also returns progress (0..1 inside the current sample); frameView() fits
// the camera to the surface with a few probe rays (see the probe entry in main.wgsl).
// Frame budget: setFrameBudget(ms) sets the band target and the preview budget. While the
// user drags, tunePreview() steps the preview scale (2..8) so that one preview frame fits
// the budget, from the measured preview cost per pixel.
//
// grep: createEngine loadSources assembleSource formulaOrder buildCallFormula compileProgram
//       setScene resize frame reset setPreview onStatus stats frameView probeRays bandRows
//       BAND_TARGET_MS MIN_BAND_PIXELS PREVIEW_SCALE MAX_QUEUED setFrameBudget tunePreview

import {
  parseWgslStructs, computeLayout, layoutFromJson, packValues, flatten, buildFractalBuffer,
  buildSequence, buildRenderParams, catalogLookup, imageAdjustments, formulaSetForScene,
} from './params.js';

const PREVIEW_SCALE = 3;
const BAND_TARGET_MS = 40;
const MAX_QUEUED = 2;
const MIN_BAND_PIXELS = 40000;
const DEFAULT_MAX_SAMPLES = 256;

const ENGINE_SHADERS = [
  'shaders/render_params.wgsl',
  'shaders/compute_fractal.wgsl',
  'shaders/fractal_coloring.wgsl',
  'shaders/calculate_distance.wgsl',
  'shaders/normal.wgsl',
  'shaders/shading.wgsl',
  'shaders/main.wgsl',
];

async function fetchText(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`engine: cannot load ${url} (${r.status})`);
  return r.text();
}

// load the generated files and the engine shaders once
async function loadSources(base) {
  const u = p => new URL(p, base).href;
  const [struct, aux, helpers, layout, params, catalog, index, present, ...engine] = await Promise.all([
    fetchText(u('gen/struct.wgsl')), fetchText(u('gen/aux.wgsl')), fetchText(u('gen/helpers.wgsl')),
    fetchText(u('gen/layout.json')).then(JSON.parse), fetchText(u('gen/params.json')).then(JSON.parse),
    fetchText(u('gen/catalog.json')).then(JSON.parse), fetchText(u('gen/formulas/index.json')).then(JSON.parse),
    fetchText(u('shaders/present.wgsl')),
    ...ENGINE_SHADERS.map(p => fetchText(u(p))),
  ]);
  return { struct, aux, helpers, layout, params, catalog, index, present, engine, formulaText: new Map() };
}

// formula files in dependency order, each once (deps before users)
function formulaOrder(files, index) {
  const out = [], seen = new Set();
  const visit = f => {
    if (seen.has(f)) return;
    seen.add(f);
    for (const d of index[f]?.deps || []) visit(d);
    out.push(f);
  };
  for (const f of files) visit(f);
  return out;
}

// generated dispatch: one case per formula in the sorted set
function buildCallFormula(files, index) {
  let s = '// generated by engine.js: formula dispatch for the formulas in use\n';
  s += 'fn callFormula(fcase: u32, z: vec4f, fi: u32, aux: ptr<function, Aux>) -> vec4f {\n';
  s += '  switch (fcase) {\n';
  files.forEach((f, i) => {
    const fn = index[f]?.fn || 'F_' + f;
    s += `    case ${i}u: { return ${fn}(z, fi, aux); }\n`;
  });
  s += '    default: { (*aux).r = -1.0; return vec4f(0.0); } // DummyIteration\n';
  s += '  }\n}\n';
  return s;
}

// full WGSL program for a formula set; exported for the naga check harness
export function assembleSource(src, files, formulaTexts) {
  const order = formulaOrder(files, src.index);
  const parts = [src.struct, src.aux, src.helpers];
  for (const f of order) parts.push(formulaTexts.get(f) || '');
  parts.push(buildCallFormula(files, src.index));
  let engine = src.engine.join('\n');
  // gen/struct.wgsl may declare FR itself; then the engine declaration goes
  if (/var\s*<\s*storage\s*,\s*read\s*>\s*FR\s*:/.test(src.struct)) {
    engine = engine.replace(/@group\(0\)\s*@binding\(1\)\s*var<storage,\s*read>\s*FR:[^;]*;/, '');
  }
  parts.push(engine);
  return parts.join('\n');
}

export async function createEngine(canvas) {
  if (!('gpu' in navigator) || !navigator.gpu) {
    throw new Error('WebGPU is not available in this browser. Use a recent Chrome, Edge or Safari with WebGPU enabled.');
  }
  const adapter = await navigator.gpu.requestAdapter({ powerPreference: 'high-performance' });
  if (!adapter) throw new Error('WebGPU is present, but no GPU adapter is available.');
  const device = await adapter.requestDevice({
    requiredLimits: {
      maxStorageBufferBindingSize: adapter.limits.maxStorageBufferBindingSize,
      maxBufferSize: adapter.limits.maxBufferSize,
    },
  });

  const statusListeners = [];
  const status = msg => { for (const fn of statusListeners) { try { fn(msg); } catch (e) { console.error(e); } } };

  device.lost.then(info => status(`GPU device lost: ${info.message || info.reason}`));
  device.addEventListener?.('uncapturederror', ev => {
    console.error('WebGPU error:', ev.error?.message);
    status(`GPU error: ${ev.error?.message || ev.error}`);
  });

  const context = canvas.getContext('webgpu');
  const format = navigator.gpu.getPreferredCanvasFormat();
  context.configure({ device, format, alphaMode: 'opaque' });

  const base = new URL('.', import.meta.url);
  const src = await loadSources(base);
  const P = src.params;
  const lookup = catalogLookup(src.catalog);

  const rpStructs = parseWgslStructs(src.engine[0]);
  const rpLayout = computeLayout(rpStructs, 'RenderParams');
  const frLayout = layoutFromJson(src.layout.Fractal);
  const frStride = Math.ceil(frLayout.size / frLayout.align) * frLayout.align;

  // ---- buffers
  const paramsBuf = device.createBuffer({ size: Math.ceil(rpLayout.size / 16) * 16, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST });
  const fractalBuf = device.createBuffer({ size: frStride * 9, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST });
  let seqBuf = device.createBuffer({ size: 4 * 4096, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST });
  let accBuf = null, dispBuf = null;
  const presentBuf = device.createBuffer({ size: 48, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });

  // ---- present pipeline
  const presentModule = device.createShaderModule({ code: src.present, label: 'mandelbulber present' });
  const presentPipeline = device.createRenderPipeline({
    layout: 'auto',
    vertex: { module: presentModule, entryPoint: 'presentVertex' },
    fragment: { module: presentModule, entryPoint: 'presentFragment', targets: [{ format }] },
    primitive: { topology: 'triangle-list' },
  });

  // ---- state
  const S = {
    scene: null, pendingScene: null,
    width: Math.max(1, canvas.width | 0), height: Math.max(1, canvas.height | 0),
    preview: false,
    samples: 0, maxSamples: DEFAULT_MAX_SAMPLES,
    presents: 0,                  // images shown so far (the page waits for a preview image)
    band: 0, bands: 1, partial: false,   // next band index and band count of the running sample
    queued: 0, current: null,     // GPU submissions not yet done; token of the newest band
    cost: [0, 0],                 // ms per pixel estimate, [full, preview]; 0 = unknown
    sampleStart: 0, lastSampleMs: 0, sampleTimes: [],
    frameSeed: (Math.random() * 0xffffffff) >>> 0,
    program: null,                // { key, files, pipeline, cases }
    compiling: 0,
    compileMs: 0,
    dirtyParams: true,
    bindGroup: null, presentBindGroup: null, presentFrom: null,
    seqLen: 1, lastError: '',
    gen: 0,                       // bumps on reset; stale band completions are ignored
    previewScale: PREVIEW_SCALE,  // preview resolution divisor; tunePreview() steps it
    previewDown: 0,               // checks in a row that allowed a finer preview
    budget: BAND_TARGET_MS,       // ms per GPU submission, and per preview frame
  };
  const cache = new Map();         // key -> Promise<program>

  const renderSize = () => {
    if (!S.preview) return [S.width, S.height];
    return [Math.max(1, Math.ceil(S.width / S.previewScale)), Math.max(1, Math.ceil(S.height / S.previewScale))];
  };

  function allocAccum() {
    const bytes = Math.max(16, S.width * S.height * 16);
    if (accBuf && accBuf.size === bytes) return;
    accBuf?.destroy(); dispBuf?.destroy();
    accBuf = device.createBuffer({ size: bytes, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC });
    dispBuf = device.createBuffer({ size: bytes, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST });
    S.bindGroup = null;
    S.presentBindGroup = null;
  }

  async function loadFormula(f) {
    if (src.formulaText.has(f)) return src.formulaText.get(f);
    const t = await fetchText(new URL(`gen/formulas/${f}.wgsl`, base));
    src.formulaText.set(f, t);
    return t;
  }

  // Step the preview scale by one toward a frame that fits the budget. Returns true on a change.
  function tunePreview() {
    const c = S.cost[1];
    if (!S.preview || !c) return false;
    const px = S.width * S.height;
    const cost = s => c * px / (s * s);
    let s = S.previewScale;
    // up at once when over budget; down only after 12 checks in a row with room to spare
    if (cost(s) > S.budget && s < 8) { s++; S.previewDown = 0; }
    else if (s > 2 && cost(s - 1) < S.budget * 0.6) { if (++S.previewDown >= 12) { s--; S.previewDown = 0; } }
    else S.previewDown = 0;
    if (s === S.previewScale) return false;
    S.previewScale = s;
    S.presentBindGroup = null;
    return true;
  }

  // compile (or fetch from cache) the program for a sorted formula list
  function compileProgram(files) {
    const key = files.join('|') || '(none)';
    if (cache.has(key)) return cache.get(key);
    const p = (async () => {
      S.compiling++;
      const t0 = performance.now();
      try {
        const order = formulaOrder(files, src.index);
        await Promise.all(order.map(loadFormula));
        const code = assembleSource(src, files, src.formulaText);
        const module = device.createShaderModule({ code, label: `mandelbulber ${key}` });
        const info = await module.getCompilationInfo();
        const errors = info.messages.filter(m => m.type === 'error');
        if (errors.length) {
          const first = errors.slice(0, 3).map(m => `line ${m.lineNum}:${m.linePos} ${m.message}`).join(' | ');
          throw new Error(`WGSL compile error (${key}): ${first}`);
        }
        const pipeline = await device.createComputePipelineAsync({
          layout: 'auto', compute: { module, entryPoint: 'renderSample' }, label: `mandelbulber ${key}`,
        });
        const ms = performance.now() - t0;
        S.compileMs = ms;
        console.log(`[mandelbulber] compiled ${key} in ${ms.toFixed(0)} ms (${code.length} chars)`);
        status(`Compiled ${files.join(' + ') || 'no formula'} in ${(ms / 1000).toFixed(2)} s`);
        const cases = new Map(files.map((f, i) => [f, i]));
        return { key, files, pipeline, cases, module, probe: null };
      } catch (e) {
        cache.delete(key);
        S.lastError = String(e.message || e);
        console.error('[mandelbulber]', e);
        status(S.lastError);
        return null;
      } finally {
        S.compiling--;
      }
    })();
    cache.set(key, p);
    return p;
  }

  function uploadScene(scene, program) {
    const seqInfo = buildSequence(scene, P, lookup);
    // formulas whose translation failed run as DummyIteration
    const [w, h] = renderSize();
    const rp = buildRenderParams(scene, P, seqInfo, program.cases, w, h);
    rp.sampleIndex = S.samples;
    rp.bandIndex = 0;
    rp.bandCount = 1;
    rp.jitterEnable = S.samples > 0 ? 1 : 0;
    rp.frameSeed = S.frameSeed;
    rp.previewMode = S.preview ? 1 : 0;
    const buf = new ArrayBuffer(paramsBuf.size);
    const view = new DataView(buf);
    const missing = new Set();
    packValues(rpLayout, flatten(rp), view, 0, missing);
    if (missing.size) {
      const key = [...missing].sort().join(' ');
      if (key !== S.missingKey) console.warn(`[mandelbulber] RenderParams fields not in struct: ${key}`);
      S.missingKey = key;
    }
    device.queue.writeBuffer(paramsBuf, 0, buf);

    const slotsInfo = [];
    for (let k = 0; k < 9; k++) slotsInfo.push(seqInfo.slots[k] || { formulaId: 0 });
    const fr = buildFractalBuffer(scene, P, frLayout, slotsInfo);
    device.queue.writeBuffer(fractalBuf, 0, fr.buffer, 0, Math.min(fr.buffer.byteLength, fractalBuf.size));

    const seqArr = seqInfo.seq.array;
    if (seqArr.byteLength > seqBuf.size) {
      seqBuf.destroy();
      seqBuf = device.createBuffer({ size: Math.ceil(seqArr.byteLength / 16) * 16, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST });
      S.bindGroup = null;
    }
    device.queue.writeBuffer(seqBuf, 0, seqArr);
    S.seqInfo = seqInfo;
    S.imageAdj = imageAdjustments(scene, P);
    S.dirtyParams = false;
  }

  // the small per-pass header fields of RenderParams (sample index, rows, jitter)
  const passFields = ['sampleIndex', 'bandIndex', 'bandCount', 'jitterEnable', 'frameSeed', 'previewMode'];
  function writePassHeader(bandIndex, bandCount) {
    const f0 = rpLayout.fields.sampleIndex.offset;
    const data = new Uint32Array(passFields.length);
    data[0] = S.samples; data[1] = bandIndex; data[2] = bandCount; data[3] = S.samples > 0 ? 1 : 0;
    data[4] = S.frameSeed; data[5] = S.preview ? 1 : 0;
    for (let i = 1; i < passFields.length; i++) {
      if (rpLayout.fields[passFields[i]].offset !== f0 + 4 * i) throw new Error('engine: pass header fields must be consecutive');
    }
    device.queue.writeBuffer(paramsBuf, f0, data);
  }

  function ensureBindGroups() {
    if (!S.bindGroup && S.program) {
      S.bindGroup = device.createBindGroup({
        layout: S.program.pipeline.getBindGroupLayout(0),
        entries: [
          { binding: 0, resource: { buffer: paramsBuf } },
          { binding: 1, resource: { buffer: fractalBuf } },
          { binding: 2, resource: { buffer: seqBuf } },
          { binding: 3, resource: { buffer: accBuf } },
        ],
      });
    }
    const from = dispBuf; // a copy of ACC taken after each complete sample
    if (!S.presentBindGroup || S.presentFrom !== from) {
      S.presentFrom = from;
      S.presentBindGroup = device.createBindGroup({
        layout: presentPipeline.getBindGroupLayout(0),
        entries: [
          { binding: 0, resource: { buffer: presentBuf } },
          { binding: 1, resource: { buffer: from } },
        ],
      });
    }
  }

  // n = samples summed in the display copy
  function present(n = S.samples) {
    if (!accBuf) return;
    S.presents++;
    ensureBindGroups();
    const [w, h] = renderSize();
    const adj = S.imageAdj || { brightness: 1, contrast: 1, imageGamma: 1, saturation: 1, hdrEnabled: 0 };
    const b = new ArrayBuffer(48);
    const f = new Float32Array(b), i32 = new Int32Array(b);
    f[0] = w; f[1] = h; f[2] = canvas.width; f[3] = canvas.height;
    f[4] = n > 0 ? 1 / n : 0;
    f[5] = adj.brightness; f[6] = adj.contrast; f[7] = adj.imageGamma; f[8] = adj.saturation;
    i32[9] = adj.hdrEnabled;
    device.queue.writeBuffer(presentBuf, 0, b);
    const enc = device.createCommandEncoder();
    const pass = enc.beginRenderPass({
      colorAttachments: [{ view: context.getCurrentTexture().createView(), loadOp: 'clear', storeOp: 'store', clearValue: { r: 0, g: 0, b: 0, a: 1 } }],
    });
    pass.setPipeline(presentPipeline);
    pass.setBindGroup(0, S.presentBindGroup);
    pass.draw(3);
    pass.end();
    device.queue.submit([enc.finish()]);
  }

  // Restart accumulation. Bands in flight finish on the GPU, but their results are ignored.
  // keepRow: continue the band sweep where it is (preview), else start at the top row.
  function reset(keepRow = false) {
    S.gen++;
    S.samples = 0;
    if (!keepRow || S.band === 0) { S.band = 0; S.partial = false; } else S.partial = true;
    S.frameSeed = (Math.random() * 0xffffffff) >>> 0;
    S.sampleTimes = [];
  }

  async function setScene(scene) {
    S.pendingScene = scene;
    const files = formulaSetForScene(scene, P, lookup).map(f => {
      const st = src.index[f] && src.index[f].status;
      if (st !== 'ok' && st !== 'override') {    // override = hand port in tools/overrides/
        status(`Formula ${f} is not available in the WGSL port; it runs as an empty iteration.`);
        return null;
      }
      return f;
    }).filter(Boolean);
    const key = files.join('|') || '(none)';
    let program = S.program;
    if (!program || program.key !== key) {
      program = await compileProgram(files);
      if (!program) {                            // keep the previous pipeline, but say so
        if (S.pendingScene === scene) { S.stale = true; canvas.classList.add('stale'); }
        status(`Compile failed: ${S.lastError}. The image still shows the previous scene.`);
        return;
      }
      if (S.pendingScene !== scene) return;      // a newer scene arrived while compiling
      S.program = program;
      S.bindGroup = null;
    }
    S.stale = false;
    canvas.classList.remove('stale');
    if (S.costKey !== key) { S.cost = [0, 0]; S.costKey = key; } // new formulas: cost unknown
    S.scene = scene;
    allocAccum();
    const scaled = tunePreview();              // a new preview size cannot continue the old sweep
    reset(S.preview && !scaled);
    uploadScene(scene, program);
  }

  function resize(cssW, cssH, dpr = 1) {
    const w = Math.max(1, Math.round(cssW * dpr));
    const h = Math.max(1, Math.round(cssH * dpr));
    if (w === S.width && h === S.height && accBuf) return;
    S.width = w; S.height = h;
    canvas.width = w; canvas.height = h;
    allocAccum();
    reset();
    if (S.scene && S.program) uploadScene(S.scene, S.program);
  }

  function setPreview(on) {
    on = !!on;
    if (on === S.preview) return;
    S.preview = on;
    S.presentBindGroup = null;
    tunePreview();
    reset();
    if (S.scene && S.program) uploadScene(S.scene, S.program);
  }

  // band count for a new sample from the cost estimate of this mode
  function bandCount(w, h) {
    const stripes = Math.ceil(h / 8);
    const most = Math.max(1, Math.min(stripes, Math.floor(w * h / MIN_BAND_PIXELS)));
    const c = S.cost[S.preview ? 1 : 0];
    if (S.fixedBands) return Math.min(stripes, S.fixedBands);
    if (!c) return S.preview ? 1 : Math.min(most, 8);   // unknown cost: a few bands (a preview is small)
    return Math.max(1, Math.min(most, Math.ceil(c * w * h / S.budget)));
  }

  // progress: bands done in the running sample (0..1); sampleMs: time since it started
  const info = (compiling, done = false) => ({
    samples: S.samples, done, compiling,
    progress: S.program && S.scene ? S.band / S.bands : 0,
    sampleMs: S.sampleStart && !done ? performance.now() - S.sampleStart : 0,
    stale: !!S.stale,                           // the last setScene failed; the image is older
  });

  // one band of one sample; returns immediately
  function frame() {
    const compiling = S.compiling > 0;
    if (!S.program || !S.scene || !accBuf) return info(compiling);
    if (S.samples >= S.maxSamples) return info(compiling, true);
    // a band of this generation is still running, or the GPU queue is full of stale bands
    if ((S.current && S.current.gen === S.gen) || S.queued >= MAX_QUEUED) return info(compiling);
    ensureBindGroups();

    const [w, h] = renderSize();
    const stripes = Math.ceil(h / 8);
    if (S.band === 0) S.bands = bandCount(w, h);
    const band = S.band, bands = S.bands;
    const myStripes = Math.ceil((stripes - band) / bands);
    const rows = Math.min(h - 8 * band, myStripes * 8);  // an upper bound: the last stripe can be short
    if (band === 0 || S.sampleStart === 0) S.sampleStart = performance.now();
    writePassHeader(band, bands);

    const enc = device.createCommandEncoder();
    const pass = enc.beginComputePass();
    pass.setPipeline(S.program.pipeline);
    pass.setBindGroup(0, S.bindGroup);
    pass.dispatchWorkgroups(Math.ceil(w / 8), myStripes, 1);
    pass.end();
    const lastBand = band === bands - 1;
    if (lastBand) enc.copyBufferToBuffer(accBuf, 0, dispBuf, 0, w * h * 16);
    device.queue.submit([enc.finish()]);

    const token = { gen: S.gen, mode: S.preview ? 1 : 0, t0: performance.now(), stale: S.queued > 0 };
    S.current = token;
    S.queued++;
    S.band = lastBand ? 0 : band + 1;        // the next band may go out as soon as this one is done
    device.queue.onSubmittedWorkDone().then(() => {
      S.queued--;
      if (S.current === token) S.current = null;
      // cost estimate; a band queued behind another one measured the wait too, so it is skipped
      if (!token.stale) {
        const c = (performance.now() - token.t0) / Math.max(1, w * rows);   // ms per pixel
        const old = S.cost[token.mode];
        S.cost[token.mode] = old ? old * 0.5 + c * 0.5 : c;
      }
      if (token.gen !== S.gen) return;         // reset while this band ran: abandoned
      if (!lastBand) return;
      if (S.partial) {
        // a preview sweep that started before the reset: rows mix two scenes, show it once
        S.partial = false;
        present(1);
        return;
      }
      S.samples++;
      S.lastSampleMs = performance.now() - S.sampleStart;
      S.sampleStart = 0;
      S.sampleTimes.push(S.lastSampleMs);
      present();
    });
    return info(compiling);
  }

  function onStatus(fn) { if (typeof fn === 'function') statusListeners.push(fn); }

  // March rays through the current program: rays = [{ o: [x,y,z], d: [x,y,z], max }].
  // Returns the hit distance per ray, or -1 for a miss. The probe pipeline compiles on first use.
  async function probeRays(rays) {
    const prog = S.program;
    if (!prog || !S.scene || !rays.length) return null;
    if (!prog.probe) {
      const t0 = performance.now();
      prog.probe = device.createComputePipelineAsync({
        layout: 'auto', compute: { module: prog.module, entryPoint: 'probeRays' }, label: `mandelbulber probe ${prog.key}`,
      }).then(p => { console.log(`[mandelbulber] probe pipeline ${prog.key} in ${(performance.now() - t0).toFixed(0)} ms`); return p; });
    }
    const pipeline = await prog.probe;
    const data = new Float32Array(rays.length * 8);
    rays.forEach((r, i) => { data.set([...r.o, r.max, ...r.d, 0], i * 8); });
    const buf = device.createBuffer({ size: data.byteLength, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC });
    const read = device.createBuffer({ size: data.byteLength, usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST });
    device.queue.writeBuffer(buf, 0, data);
    const bg = device.createBindGroup({
      layout: pipeline.getBindGroupLayout(0),
      entries: [
        { binding: 0, resource: { buffer: paramsBuf } },
        { binding: 1, resource: { buffer: fractalBuf } },
        { binding: 2, resource: { buffer: seqBuf } },
        { binding: 4, resource: { buffer: buf } },
      ],
    });
    const enc = device.createCommandEncoder();
    const pass = enc.beginComputePass();
    pass.setPipeline(pipeline);
    pass.setBindGroup(0, bg);
    pass.dispatchWorkgroups(Math.ceil(rays.length / 64));
    pass.end();
    enc.copyBufferToBuffer(buf, 0, read, 0, data.byteLength);
    device.queue.submit([enc.finish()]);
    await read.mapAsync(GPUMapMode.READ);
    const out = new Float32Array(read.getMappedRange().slice(0));
    read.unmap(); read.destroy(); buf.destroy();
    return rays.map((_, i) => out[i * 8 + 7]);
  }

  // Frame: rays from a sphere of radius R around the target toward the target find the
  // surface; the result is the center and radius of the hit points. A shape that still
  // encloses the ray origins at the largest R has no finite extent ({ unbounded: true }).
  async function frameView() {
    const scene = S.scene;
    if (!scene || S.pendingScene !== scene) return null;       // a newer scene is compiling
    const main = scene.main || {};
    const t = main.target || { x: 0, y: 0, z: 0 };
    const target = [t.x ?? 0, t.y ?? 0, t.z ?? 0];
    const N = 256, golden = Math.PI * (3 - Math.sqrt(5));
    const dirs = [];
    for (let i = 0; i < N; i++) {
      const z = 1 - (2 * i + 1) / N, r = Math.sqrt(1 - z * z), a = i * golden;
      dirs.push([Math.cos(a) * r, Math.sin(a) * r, z]);
    }
    for (const R of [8, 40, 200]) {
      const rays = dirs.map(u => ({ o: target.map((c, k) => c + u[k] * R), d: u.map(x => -x), max: 2 * R }));
      const hits = await probeRays(rays);
      if (!hits) return null;
      let inside = 0;
      const pts = [];
      hits.forEach((h, i) => {
        if (h < 0) return;
        if (h < R * 1e-4) { inside++; return; }
        pts.push(rays[i].o.map((c, k) => c + rays[i].d[k] * h));
      });
      if (inside > N * 0.25) continue;                          // origins inside the solid: go wider
      if (pts.length < 3) return { empty: true };               // dust or a miss: no fit
      const lo = [0, 1, 2].map(k => Math.min(...pts.map(p => p[k])));
      const hi = [0, 1, 2].map(k => Math.max(...pts.map(p => p[k])));
      const center = lo.map((v, k) => (v + hi[k]) / 2);
      const radius = Math.max(...pts.map(p => Math.hypot(p[0] - center[0], p[1] - center[1], p[2] - center[2])));
      return { center: { x: center[0], y: center[1], z: center[2] }, radius, hits: pts.length, R };
    }
    return { unbounded: true };
  }

  return {
    setScene, resize, frame, reset: () => { reset(); if (S.scene && S.program) uploadScene(S.scene, S.program); },
    setPreview, onStatus,
    // extras for the page, tools and tests
    frameView, probeRays,
    setMaxSamples(n) { S.maxSamples = Math.max(1, n | 0); },
    setBands(n) { S.fixedBands = Math.max(0, n | 0); },   // tests: a fixed band count, 0 = automatic
    setFrameBudget(ms) { S.budget = Math.max(8, +ms || BAND_TARGET_MS); },
    stats() {
      return { samples: S.samples, lastSampleMs: S.lastSampleMs, sampleTimes: S.sampleTimes.slice(),
        compileMs: S.compileMs, bands: S.bands, program: S.program?.key, lastError: S.lastError,
        size: renderSize(), preview: S.preview, previewScale: S.previewScale, budget: S.budget, progress: S.band / S.bands,
        costMsPerMpx: S.cost.map(c => +(c * 1e6).toFixed(1)), queued: S.queued, presents: S.presents };
    },
    device,
    get sources() { return src; },
  };
}
