// ============================================================================
//  HYDROGEN TABLE  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the header formulas with MathJax into static SVG and writes
//  equations.js. The page then shows the same glyph outlines in each
//  browser. KaTeX HTML output broke in Safari: subscripts, fraction
//  denominators and the root did not go below the baseline.
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/hydrogen-table/typeset.mjs
//  The script finds equations.js next to itself.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      formulas ........ "const TEX"    the TeX source of each formula
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const TEX = {
  psi: String.raw`\psi_{n\ell m}(r,\vartheta,\varphi)=\sqrt{\left(\frac{2}{n a_0}\right)^{\!3}\frac{(n-\ell-1)!}{2n\,(n+\ell)!}}\;e^{-\rho/2}\,\rho^{\ell}\,L^{2\ell+1}_{n-\ell-1}(\rho)\,Y_{\ell}^{m}(\vartheta,\varphi)`,
  complex: String.raw`\rho=\frac{2r}{n a_0},\qquad E_n=-\frac{13.6\ \mathrm{eV}}{n^{2}},\qquad \bigl|Y_{\ell}^{m}\bigr|^{2}\ \text{does not depend on}\ \varphi`,
  real: String.raw`Y_{\ell m}^{\mathrm{real}}=\begin{cases}\sqrt{2}\,(-1)^{m}\,\operatorname{Re}Y_{\ell}^{|m|}\;\propto\;\cos m\varphi, & m>0\\[3pt] \sqrt{2}\,(-1)^{m}\,\operatorname{Im}Y_{\ell}^{|m|}\;\propto\;\sin|m|\varphi, & m<0\end{cases}`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const js = `// ============================================================================
//  HYDROGEN TABLE  ·  equation renderer  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//
//  window.HydEq.setKind(kind) swaps the second line. Complex tiles show rho
//  and E_n. Real tiles show how a real orbital comes from Y_l^|m|.
//
//  SECTION MAP   (jump with grep -n "<anchor>" equations.js)
//      formulas ........ "const SVG"  psi, complex and real, as SVG text
//      mount ........... "eqPsi"      the header slots
// ============================================================================
(function(){
  const SVG = ${JSON.stringify(out, null, 2)};
  const put = (id, s) => { const el = document.getElementById(id); if (el) el.innerHTML = s; };
  put('eqPsi', SVG.psi);
  window.HydEq = { setKind(kind){ put('eqRho', SVG[kind] || SVG.complex); } };
  window.HydEq.setKind('complex');
})();
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
for (const [k, s] of Object.entries(out)) console.log(' ', k, s.length, 'bytes', s.match(/width="[^"]+" height="[^"]+"/)[0]);
