// ============================================================================
//  QFT FLOW  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets every formula of the page with MathJax into static SVG and
//  writes equations.js. KaTeX HTML output broke in Safari (see the hydrogen
//  table): subscripts and fraction denominators stayed on the baseline. SVG
//  paths look the same in each browser. Same approach as
//  pages/frqi-quantum-image-lab/typeset.mjs, copied, not imported.
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/qft-flow/typeset.mjs
//  The script finds equations.js next to itself.
//
//  equations.js is a classic script (main.js is not a module). It sets
//  window.QFT_EQ = { key: svg }. main.js puts each SVG into the element
//  with the same data-eq key in index.html.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      colors .......... "const c ="    symbol -> .mN class
//      formulas ........ "const TEX"    [key, display, TeX source]
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

// [key, display, TeX]. key matches data-eq in index.html. display true is a
// block formula, false is inline in a caption.
// Symbol classes. ../../lib/sci.css colors .m1 to .m6. One class per
// quantity, the same in every formula and on the control labels:
//   m1  phase theta(x)          m5  qubit rotation phi_j (the phi sliders)
//   m2  ramp slope alpha        m3  frequency bin k, kappa
//   m4  probability P           m6  detuning delta_j
// N, n, x, j, V and the numbers stay ink.
const c = (k, t) => String.raw`\class{${k}}{${t}}`;
const TH = c('m1', String.raw`\theta`), PH = c('m5', String.raw`\varphi_j`), AL = c('m2', String.raw`\alpha`);
const K = c('m3', 'k'), KA = c('m3', String.raw`\kappa`), P = c('m4', 'P'), DJ = c('m6', String.raw`\delta_j`);

const TEX = [
  ["flow", false, String.raw`${P}(${K})=\bigl|\tfrac{1}{N}\sum_{x} e^{i${TH}(x)}\,e^{-2\pi i ${K}x/N}\bigr|^2`],
  ["in", true , String.raw`|\psi_{\text{in}}\rangle=\frac{1}{\sqrt{N}}\sum_{x=0}^{N-1} e^{\,i${TH}(x)}\,|x\rangle,\qquad ${TH}(x)=\sum_{j=0}^{n-1}${PH}\,x_j,\quad N=2^{\,n}`],
  ["ket-k", false, String.raw`|${K}\rangle`],
  ["amp", true , String.raw`V[${K}]=\langle ${K}|\,\mathrm{QFT}\,|\psi_{\text{in}}\rangle=\frac{1}{N}\sum_{x=0}^{N-1} e^{\,i${TH}(x)}\,e^{-2\pi i\,${K}x/N}`],
  ["vk2", false, String.raw`|V(${KA})|^2`],
  ["prob", true , String.raw`${P}(${K})=\bigl|V[${K}]\bigr|^2,\qquad ${KA}\in[0,N)\ \text{continuous}`],
  ["ramp", true , String.raw`${PH}=${AL}\,2^{\,j}\;\Rightarrow\;${TH}(x)=${AL} x\;\Rightarrow\;\text{peak at }${K}=\frac{${AL} N}{2\pi}`],
  ["j", false, String.raw`j`],
  ["dj", false, String.raw`${DJ}`],
  ["leak", true , String.raw`${P}_{\text{peak}}=\prod_{j=0}^{n-1}\cos^2\!\Bigl(\tfrac{${DJ}}{2}\Bigr)`],
  ["wrap", true , String.raw`V[${K}+N]=V[${K}]\quad\Longleftrightarrow\quad |${K}\rangle\ \text{and}\ |${K}+N\rangle\ \text{label the same bin}`],
  // control labels: the slope alpha, and phi_0 ... phi_19 (setN allows 20 qubits)
  ["alpha", false, AL],
  ...Array.from({ length: 20 }, (_, j) => ["phi" + j, false, c('m5', String.raw`\varphi_{${j}}`)]),
];

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'html'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex, display) {
  const node = doc.convert(tex, { display });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/&/g, '&amp;').replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = {};
for (const [key, display, tex] of TEX) out[key] = svg(tex, display);
const js = `// ============================================================================
//  QFT FLOW  ·  formulas  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each value is static SVG from MathJax, with glyphs as paths. It uses
//  currentColor, so the colour of the [data-eq] element sets the ink.
//  Classic script: it sets window.QFT_EQ before main.js runs.
// ============================================================================
window.QFT_EQ = ${JSON.stringify(out, null, 1)};
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes,', Object.keys(out).length, 'formulas');
