// ============================================================================
//  MATERIAL STUDIO  ·  viewport/environment.js — env.js bindings, env WGSL, frame bind group
// ────────────────────────────────────────────────────────────────────────────
//  Reads env.js each frame and picks one of three environment kinds: 'lib',
//  'tex' or 'proc' (see the viewport.js header). envChunk() writes the WGSL
//  that samples that kind. frameLayout() and ensureFrameBG() make the group 0
//  layout and bind group for it, and keep them until the textures change.
//
//  GREP TARGETS
//      safeEnvBindings ........ env.js getEnvBindings(), null when it throws
//      envState ............... the frame environment description (e.key)
//      envChunk ............... generated WGSL: env_radiance / env_irradiance
//      frameLayout ............ group 0 layout per env key (cached in R.layout)
//      ensureFrameBG .......... group 0 bind group, rebuilt on a texture change
// ============================================================================
import { gpu, device, envMod, R, warnOnce, norm3, idOf } from './state.js';

export function safeEnvBindings() {
  try { return envMod && typeof envMod.getEnvBindings === 'function' ? envMod.getEnvBindings() : null; }
  catch (e) { warnOnce('envthrow', 'getEnvBindings threw: ' + e.message); return null; }
}
function usableTex(t, name) {
  if (!t || typeof t.createView !== 'function') return false;
  if (/32float$/.test(t.format || '') && !gpu.features.float32Filterable) { warnOnce('f32' + name, `${name} is ${t.format} and float32-filterable is missing; ignored`); return false; }
  return true;
}
const dimOf = (t, hint) => hint ? (hint === 'cube' ? 'cube' : '2d') : (t.depthOrArrayLayers === 6 ? 'cube' : '2d');

/** Read env.js and return the frame environment description. */
export function envState() {
  const b = safeEnvBindings();
  const e = { b, kind: 'proc', radDim: '2d', irrMode: 'proc', rad: null, irr: null, mips: 8, sh: null, sun: null, lib: '' };
  if (b && b.specTex && typeof envMod.envWGSL === 'function' && typeof envMod.envBindGroupEntries === 'function') {
    try { e.lib = envMod.envWGSL({ group: 0, binding: 8 }); } catch (err) { warnOnce('envwgsl', 'envWGSL failed: ' + err.message); }
  }
  if (e.lib) {
    e.kind = 'lib'; e.rad = b.specTex; e.irrMode = 'lib';
    e.mips = Math.max(1, b.mipCount || b.specTex.mipLevelCount || 1);
  } else if (b && usableTex(b.radiance, 'radiance')) {
    e.kind = 'tex';
    e.rad = b.radiance;
    e.radDim = dimOf(b.radiance, b.radianceDim || (b.kind === 'cube' ? 'cube' : null));
    e.mips = Math.max(1, b.mipCount || b.radiance.mipLevelCount || 1);
    if (b.irradiance && usableTex(b.irradiance, 'irradiance')) { e.irr = b.irradiance; e.irrMode = dimOf(b.irradiance, b.irradianceDim) === 'cube' ? 'cube' : '2d'; }
    else if (b.sh && b.sh.length >= 27) { e.irrMode = 'sh'; e.sh = b.sh; }
    else e.irrMode = 'rad';
    if (Array.isArray(b.sunDir) && b.sunDir.length === 3) e.sun = norm3(b.sunDir);
  }
  e.key = `${e.kind}|${e.radDim}|${e.irrMode}`;
  return e;
}

/** Generated WGSL for the env bindings 1 and 2 and the two sampling functions. */
export function envChunk(e) {
  if (e.kind === 'lib') {
    return `
// ---- generated by viewport.js envChunk (lib): env.js envWGSL at bindings 8..13
${e.lib}
@group(0) @binding(1) var tRad: texture_2d<f32>;
@group(0) @binding(2) var tIrr: texture_2d<f32>;
fn env_radiance(dir: vec3f, lod: f32) -> vec3f {
  return envSpecular(dir, lod / max(F.env.z - 1.0, 1.0));
}
fn env_irradiance(n: vec3f) -> vec3f {
  return envIrradiance(n);
}
fn env_background(d: vec3f) -> vec3f {
  return envBackground(d);
}
`;
  }
  const radT = e.radDim === 'cube' ? 'texture_cube<f32>' : 'texture_2d<f32>';
  const irrT = e.irrMode === 'cube' ? 'texture_cube<f32>' : 'texture_2d<f32>';
  const co = dim => (dim === 'cube' ? 'd' : 'env_uv(d)');
  let irr;
  if (e.kind === 'proc') irr = 'return sky_proc(n, 1.0) * F.env.y;';
  else if (e.irrMode === 'cube' || e.irrMode === '2d') irr = `let d = env_rot(n);\n  return textureSampleLevel(tIrr, sEnv, ${co(e.irrMode)}, 0.0).rgb * F.env.y;`;
  else if (e.irrMode === 'sh') irr = 'return sh_eval(env_rot(n)) * F.env.y;';
  else irr = `let d = env_rot(n);\n  return textureSampleLevel(tRad, sEnv, ${co(e.radDim)}, max(F.env.z - 1.0, 0.0)).rgb * F.env.y;`;
  const rad = e.kind === 'proc'
    ? 'return sky_proc(env_rot(dir), lod / max(F.env.z - 1.0, 1.0)) * F.env.y;'
    : `let d = env_rot(dir);\n  return textureSampleLevel(tRad, sEnv, ${co(e.radDim)}, lod).rgb * F.env.y;`;
  return `
// ---- generated by viewport.js envChunk (${e.key})
@group(0) @binding(1) var tRad: ${radT};
@group(0) @binding(2) var tIrr: ${irrT};
fn env_radiance(dir: vec3f, lod: f32) -> vec3f {
  ${rad}
}
fn env_irradiance(n: vec3f) -> vec3f {
  ${irr}
}
fn env_background(d: vec3f) -> vec3f {
  return env_radiance(d, F.bgB.x);
}
`;
}

export function frameLayout(e) {
  const k = 'frame|' + e.key;
  if (R.layout[k]) return R.layout[k];
  const VF = GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT;
  R.layout[k] = device.createBindGroupLayout({
    label: 'vp-' + k,
    entries: [
      { binding: 0, visibility: VF, buffer: { type: 'uniform' } },
      { binding: 1, visibility: VF, texture: { sampleType: 'float', viewDimension: e.radDim === 'cube' && e.kind === 'tex' ? 'cube' : '2d' } },
      { binding: 2, visibility: VF, texture: { sampleType: 'float', viewDimension: e.irrMode === 'cube' ? 'cube' : '2d' } },
      { binding: 3, visibility: VF, sampler: { type: 'filtering' } },
      { binding: 4, visibility: VF, texture: { sampleType: 'float', viewDimension: '2d' } },
      { binding: 5, visibility: VF, texture: { sampleType: 'depth', viewDimension: '2d' } },
      { binding: 6, visibility: VF, sampler: { type: 'comparison' } },
      { binding: 7, visibility: VF, sampler: { type: 'filtering' } },
      ...(e.kind === 'lib' ? envMod.envBindGroupLayoutEntries(8, VF) : []),
    ],
  });
  return R.layout[k];
}

/** (Re)build the frame bind group when the env textures change. */
export function ensureFrameBG(e) {
  const id = `${e.key}|${idOf(e.rad)}|${idOf(e.irr)}`;
  if (R.frameBG && R.frameBGKey === id) return;
  const radView = e.kind === 'tex' ? e.rad.createView({ dimension: e.radDim === 'cube' ? 'cube' : '2d' }) : R.dummy2d.createView();
  const irrView = (e.irrMode === 'cube' || e.irrMode === '2d') ? e.irr.createView({ dimension: e.irrMode === 'cube' ? 'cube' : '2d' }) : R.dummy2d.createView();
  R.frameBG = device.createBindGroup({
    label: 'vp-frame-bg',
    layout: frameLayout(e),
    entries: [
      { binding: 0, resource: { buffer: R.frameBuf } },
      { binding: 1, resource: radView },
      { binding: 2, resource: irrView },
      { binding: 3, resource: R.samp.env },
      { binding: 4, resource: R.lutView },
      { binding: 5, resource: R.shadowView },
      { binding: 6, resource: R.samp.shadow },
      { binding: 7, resource: R.samp.clamp },
      ...(e.kind === 'lib' ? envMod.envBindGroupEntries(8) : []),
    ],
  });
  R.frameBGKey = id;
}
