// ============================================================================
//  DOUBLE-SLIT  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the equation panel with MathJax into static SVG and writes
//  equations.js. The page then shows the same glyph outlines in each
//  browser. KaTeX HTML output broke in Safari (see hydrogen-table).
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/double-slit/typeset.mjs
//  The script finds equations.js next to itself.
//
//  COLOURS  (the same tokens as style.css)
//      ψ the field ......... --psi    gold
//      c, α, Δt, Δx ........ --speed  cyan
//      σ, c_a, c_b ......... --loss   coral
//      λ, d, a, m, θ ....... --geom   violet
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      formulas ........ "const TEX"    the TeX source of each formula
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const PSI = '#ffcf6b', SPEED = '#7fd6ff', LOSS = '#ff8f7a', GEOM = '#c7a6ff';
const col = (c, t) => String.raw`{\color{${c}}{${t}}}`;
const psi = s => col(PSI, String.raw`\psi${s || ''}`);

const TEX = {
  wave: String.raw`\frac{\partial^2 ${psi()}}{\partial t^2}+${col(LOSS, String.raw`\sigma`)}\,\frac{\partial ${psi()}}{\partial t}=${col(SPEED, 'c^2')}\,\nabla^2 ${psi()}`,
  step: String.raw`${psi('^{\,n+1}')}=${col(LOSS, 'c_a')}\bigl(2${psi('^{\,n}')}+${col(SPEED, String.raw`\alpha^2`)}\,\nabla_h^2 ${psi('^{\,n}')}\bigr)-${col(LOSS, 'c_b')}\,${psi('^{\,n-1}')}`,
  coef: String.raw`${col(LOSS, 'c_a')}=\frac{1}{1+${col(LOSS, String.raw`\sigma`)}\Delta t/2},\qquad ${col(LOSS, 'c_b')}=\frac{1-${col(LOSS, String.raw`\sigma`)}\Delta t/2}{1+${col(LOSS, String.raw`\sigma`)}\Delta t/2}`,
  courant: String.raw`${col(SPEED, String.raw`\alpha`)}=\frac{${col(SPEED, String.raw`c\,\Delta t`)}}{${col(SPEED, String.raw`\Delta x`)}}\;\le\;\frac{1}{\sqrt{2}}`,
  bright: String.raw`r_2-r_1=${col(GEOM, 'm')}\,${col(GEOM, String.raw`\lambda`)},\qquad ${col(GEOM, 'm')}=0,\pm1,\pm2,\dots`,
  far: String.raw`I(${col(GEOM, String.raw`\theta`)})\;\propto\;\cos^2\!\Bigl(\frac{\pi ${col(GEOM, 'd')}\sin${col(GEOM, String.raw`\theta`)}}{${col(GEOM, String.raw`\lambda`)}}\Bigr)\,\operatorname{sinc}^2\!\Bigl(\frac{\pi ${col(GEOM, 'a')}\sin${col(GEOM, String.raw`\theta`)}}{${col(GEOM, String.raw`\lambda`)}}\Bigr)`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'color'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/\\color\{#[0-9a-f]+\}/g, '').replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const js = `// ============================================================================
//  DOUBLE-SLIT  ·  equation renderer  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  Each element with data-eq="<key>" gets the formula of that key.
//
//  SECTION MAP   (jump with grep -n "<anchor>" equations.js)
//      formulas ........ "const SVG"   ${Object.keys(out).join(', ')}
//      mount ........... "data-eq"     fills the slots at load
// ============================================================================
(function(){
  const SVG = ${JSON.stringify(out, null, 1)};
  document.querySelectorAll('[data-eq]').forEach(el => { const s = SVG[el.dataset.eq]; if (s) el.innerHTML = s; });
})();
`;
const here = fileURLToPath(new URL('.', import.meta.url));
writeFileSync(here + 'equations.js', js);
console.log('wrote equations.js:', Object.keys(out).join(', '), (js.length / 1024).toFixed(1) + ' KB');
