// ============================================================================
//  MAXWELL'S EQUATIONS  ·  interactive explorer
// ----------------------------------------------------------------------------
//  Four canvas scenes, one per law. A law button selects activeEq; switchEq
//  fills the card, the legend and the controls, and seeds the scene. One
//  render(dt) dispatches to the active law's own draw routine each frame.
//  All scene state lives in STATE; controls and drag handlers change it.
//
//  THE FOUR LAWS
//  --------------------------------------------------------------------------
//      0  Gauss ∇·E = ρ/ε₀      charges + a Gaussian surface; flux = enclosed Q
//      1  Gauss ∇·B = 0         a dipole magnet; every closed surface nets zero
//      2  Faraday ∇×E = −∂B/∂t  oscillating B induces a circulating E (Lenz sign)
//      3  Ampère–Maxwell        wire currents give μ₀J·B, plus the capacitor's
//                               displacement current ε₀∂E/∂t circulating B
//
//  COLOUR
//  --------------------------------------------------------------------------
//      COL holds one colour per field: E amber, B cyan, + charge coral,
//      − charge periwinkle, current gold. style.css (--E, --B, ...) and
//      typeset.mjs use the same values, so a term in an equation has the
//      colour of its field on the canvas. A law takes the colour of the
//      field on its left side (LAWS[i].c).
//
//  EQUATIONS
//  --------------------------------------------------------------------------
//      equations.js (GENERATED by typeset.mjs) sets window.MAXWELL_EQ: the
//      MathJax SVG of each differential and integral form. No math library
//      loads at run time. KaTeX HTML broke in Safari.
//
//  SCENE UNITS
//  --------------------------------------------------------------------------
//      All positions and sizes in STATE are scene units, not pixels. The
//      origin is the center of the free area: the canvas area below the
//      law card and above the legend. The scene is SCENE units across.
//      fitScene sets K, the pixels per unit, so the scene fills the free
//      area at any window shape. px(u) and py(v) change units to pixels.
//      toUnits changes pixels to units.
//
//  SCREEN LAYOUT   (the leading marker is an element id)
//  --------------------------------------------------------------------------
//      #panel       title, #laws (one button per law), controls, About
//      #canvas-wrap #sim-canvas, #card, #legend, #readout
//      #dock        phone only: panel button and law buttons
//
//  FRAME PIPELINE
//  --------------------------------------------------------------------------
//      loop(t) ─ render(dt) ─ clear + dots ─▶ renderGauss / renderMonopoles /
//                                             renderFaraday / renderAmpere
//      Field lines are traced once per scene change (gaussCache, dipCache,
//      ampCache) and drawn each frame with dashes that flow along the field.
//
//  SECTION MAP   (jump with grep -n "<anchor>" main.js)
//  --------------------------------------------------------------------------
//      colours ............. "const COL"           field colours
//      laws ................ "const LAWS"          name, colour, text per law
//      scale ............... "function fitScene"    free area, K, px, py, font
//      state ............... "const STATE="        all scene state
//      card ................ "function renderCard"  card, legend, law list
//      readout ............. "function setReadout"  numbers at the base
//      controls ............ "function buildControls"  per-law control markup
//      law switch .......... "function switchEq"    change the active law
//      per-law init ........ "function initEq"      seed a scene on entry
//      physics ............. "function eField"      field formulas
//      actions ............. "function addCharge"   add/clear scene objects
//      draw helpers ........ "DRAW HELPERS"        traceLine, flowLine, body
//      render dispatch ..... "function render"      clear, dots, dispatch
//      Gauss draw .......... "function renderGauss" law 0
//      monopoles draw ...... "function renderMonopoles"  law 1
//      Faraday draw ........ "function renderFaraday"    law 2
//      Ampère draw ......... "function renderAmpere"     law 3
//      drag ................ "function getPos"      pointer picking and drag
//      phone sheet ......... "function setOpen"     dock, sheet, and grip
//      resize .............. "function resize"      canvas sizing and DPR
//      loop ................ "function loop"        per-frame driver
//      screensaver ......... "window.snSaver"      shell saver hook
// ============================================================================
// The drawing canvas and its 2D context. CW/CH are the CSS size; activeEq is the
// index of the currently shown equation (0 to 3).
const canvas=document.getElementById('sim-canvas');
const ctx=canvas.getContext('2d');
let CW=100,CH=100,activeEq=0;

// Field colours as hex (for CSS and the legend) and as "r,g,b" (for canvas
// rgba strings). style.css --E, --B, --Q, --Qn, --J and typeset.mjs C match.
const COL={E:'#ffa552',B:'#4fd6ea',Q:'#ff6f61',Qn:'#8c9cff',J:'#ffd166',ink:'#eef3fb'};
const RGB={E:'255,165,82',B:'79,214,234',Q:'255,111,97',Qn:'140,156,255',J:'255,209,102',ink:'238,243,251',dim:'127,145,173'};
// One record per law: numeral, name, the field colour of its left side,
// the plain line under the formulas, and the About text in the panel.
const LAWS=[
  {num:'I',name:'Gauss\'s law',c:COL.E,
   line:'Electric field lines begin on positive charge and end on negative charge.',
   about:'Coulomb found (1785) that the electric force falls off as the inverse square of distance. Gauss showed that this means the total flux through <em>any</em> closed surface depends only on the charge inside it, not on the shape of the surface. Drag the charges and the surface, or change its radius, and watch the enclosed charge.'},
  {num:'II',name:'No magnetic monopoles',c:COL.B,
   line:'Magnetic field lines never end. Each one closes on itself.',
   about:'No one has ever found an isolated magnetic pole. Cut a magnet in half and you get two smaller magnets, each with a north and a south pole. So every field line that leaves a closed surface also comes back in, and the net flux is <em>always</em> zero. Drag the magnet and turn it.'},
  {num:'III',name:'Faraday\'s law',c:COL.E,
   line:'A changing magnetic field makes the electric field curl around it.',
   about:'Faraday found (1831) that a moving magnet drives a current in a coil. The changing flux of B makes an electric field that circulates around it. The minus sign is Lenz\'s law: the induced field opposes the change. Generators, transformers and induction cooktops all work this way.'},
  {num:'IV',name:'Ampère–Maxwell law',c:COL.B,
   line:'Currents, and changing electric fields, make the magnetic field curl around them.',
   about:'Ampère showed (1825) that a current makes a magnetic field that circulates around it. Maxwell (1862) added the term <em>ε₀ ∂E/∂t</em>: a changing electric field acts like a current, even across the empty gap of a capacitor. With that term, the equations predict waves that move at the speed of light. Light is one of them.'},
];

/* ═══ SCALE ═══ */
// The scene is SCENE units across. FX, FY are the pixel center of the free
// area. K is pixels per unit. T is the stroke scale: it follows K but does not
// go below 1, so lines stay visible on small screens.
const SCENE=380;
let FX=50,FY=50,K=1,T=1;
const px=u=>FX+u*K, py=v=>FY+v*K;
function toUnits(x,y){return[(x-FX)/K,(y-FY)/K];}
// Find the free area below the law card and above the legend, and fit the
// scene in it. If the card leaves less than 45% of the height, use the full
// canvas.
function fitScene(){
  const card=document.getElementById('card');
  const pad=Math.max(10,Math.min(CW,CH)*0.02);
  let top=card?card.offsetTop+card.offsetHeight+pad:pad;
  if(CH-top<CH*0.45)top=pad;
  const base=CW<560?64:56;   // the legend and readout row
  const w=CW-2*pad,h=CH-top-base;
  FX=CW/2;FY=top+h/2;
  K=Math.max(0.5,Math.min(w,h)/SCENE);
  T=Math.max(1,K);
}
// Canvas font for a label of base size b px. The size follows K, but it is
// never less than b and never more than 2.4 b.
function font(b,w='500'){return`${w} ${Math.round(Math.min(b*2,Math.max(b,b*K)))}px "IBM Plex Mono", ui-monospace, monospace`;}

// All scene state, grouped by equation, in scene units. Gauss holds the charge
// list and the Gaussian surface; monopoles hold the dipole pose; Faraday holds
// the drive rate and phase clock; Ampère holds the wire list and its clock.
// Angles are in radians.
const STATE={
  // Eq 0: Gauss - charges
  charges:[],
  gaussR:110,
  gaussX:0,gaussY:0,
  // Eq 1: No monopoles - dipole
  dipX:0,dipY:0,dipAngle:0,dipStr:2,
  // Eq 2: Faraday - changing B
  faradayRate:1.0,faradayTime:0,faradayR:80,
  // Eq 3: Ampere - wire current
  ampWires:[],ampTime:0,
  // Shared
  showArrows:true,showTracers:true,
};

// Paint a range input's filled track via the --pct custom property.
function sg(el){const pct=(el.value-el.min)/(el.max-el.min)*100;el.style.setProperty('--pct',pct+'%');}

/* ═══ CARD ═══ */
// The legend items of each law: [label, colour, kind]. kind is 'line' (a
// field), 'dot' (a body) or 'dash' (a surface or loop).
const LEGEND=[
  [['E field',COL.E,'line'],['+ charge',COL.Q,'dot'],['− charge',COL.Qn,'dot'],['Gaussian surface',COL.ink,'dash']],
  [['B field',COL.B,'line'],['north pole',COL.Q,'dot'],['south pole',COL.Qn,'dot'],['closed surface',COL.ink,'dash']],
  [['B, out of or into the page',COL.B,'dot'],['induced E',COL.E,'line']],
  [['B field',COL.B,'line'],['current I',COL.J,'dot'],['E in the gap',COL.E,'line'],['Amperian loop',COL.J,'dash']],
];
// Fill the law list once. Each button shows the numeral, the name and the
// differential form, and takes the colour of its field (--lc).
function buildLaws(){
  const host=document.getElementById('laws');
  const eq=window.MAXWELL_EQ||[];
  host.innerHTML=LAWS.map((l,i)=>`<button class="law" data-eq="${i}" style="--lc:${l.c}" onclick="switchEq(${i})" aria-label="${l.name}">
    <span class="num">${l.num}</span><span class="name">${l.name}</span><span class="form">${eq[i]?eq[i].d:''}</span></button>`).join('');
  document.querySelectorAll('#dockEqs button').forEach(b=>b.style.setProperty('--lc',LAWS[+b.dataset.eq].c));
}
// Fill the card and the legend for the active law, and mark its button.
function renderCard(){
  const l=LAWS[activeEq],eq=(window.MAXWELL_EQ||[])[activeEq];
  document.body.dataset.eq=activeEq;
  document.getElementById('card-num').textContent=l.num;
  document.getElementById('card-name').textContent=l.name;
  document.getElementById('card-eq').innerHTML=eq?eq.d:'';
  document.getElementById('card-int').innerHTML=eq?eq.i:'';
  document.getElementById('card-line').textContent=l.line;
  document.getElementById('legend').innerHTML=LEGEND[activeEq].map(([t,c,k])=>
    `<li><span class="sw${k==='line'?'':' '+k}" style="--sw:${c}"></span>${t}</li>`).join('');
  document.querySelectorAll('.law').forEach(b=>b.classList.toggle('active',+b.dataset.eq===activeEq));
}
// The readout at the base of the canvas. Only a changed string touches the
// DOM, so a frame that shows the same numbers costs nothing.
let readoutHTML='';
function setReadout(html){
  if(html===readoutHTML)return;
  readoutHTML=html;document.getElementById('readout').innerHTML=html;
}
// Signed value with a real minus sign.
const sgn=(v,d=0)=>(v<0?'−':v>0?'+':'')+Math.abs(v).toFixed(d);

// Rebuild the controls and the About text for the active law. Each case
// injects the widgets that law needs, wired through inline handlers that
// write STATE. Each slider also writes its value into the .val span.
/* ═══ CONTROLS PER EQUATION ═══ */
function buildControls(){
  const area=document.getElementById('ctrl-area');
  document.getElementById('about-text').innerHTML=LAWS[activeEq].about;
  switch(activeEq){
    // Gauss: add charges of either sign and resize the Gaussian surface.
    case 0:
      area.innerHTML=`
        <div class="btn-row">
          <button class="tog-btn" onclick="addCharge(1)"><span class="sw" style="--sw:${COL.Q}"></span>Add +q</button>
          <button class="tog-btn" onclick="addCharge(-1)"><span class="sw" style="--sw:${COL.Qn}"></span>Add −q</button>
        </div>
        <div class="mag-row"><span class="mag-row-lbl">Surface</span>
          <input type="range" min="30" max="180" value="${STATE.gaussR}" step="5" aria-label="Surface radius" oninput="STATE.gaussR=+this.value;this.nextElementSibling.textContent=this.value;sg(this)">
          <span class="val">${STATE.gaussR}</span></div>
        <button class="tog-btn quiet" onclick="clearCharges()">Clear the charges</button>`;
      break;
    // No monopoles: set the dipole strength and orientation angle.
    case 1:
      area.innerHTML=`
        <div class="mag-row"><span class="mag-row-lbl">Strength</span>
          <input type="range" min="0.5" max="5" value="${STATE.dipStr}" step="0.1" aria-label="Dipole strength" oninput="STATE.dipStr=+this.value;this.nextElementSibling.textContent=(+this.value).toFixed(1);sg(this)">
          <span class="val">${STATE.dipStr.toFixed(1)}</span></div>
        <div class="mag-row"><span class="mag-row-lbl">Angle</span>
          <input type="range" min="-3.14" max="3.14" value="${STATE.dipAngle}" step="0.05" aria-label="Dipole angle" oninput="STATE.dipAngle=+this.value;this.nextElementSibling.textContent=(this.value*180/Math.PI).toFixed(0)+'°';sg(this)">
          <span class="val">${(STATE.dipAngle*180/Math.PI).toFixed(0)}°</span></div>
        <p class="hint">Drag the magnet across the surface. The flux stays zero.</p>`;
      break;
    // Faraday: set how fast B oscillates and the field region radius.
    case 2:
      area.innerHTML=`
        <div class="mag-row"><span class="mag-row-lbl">Rate</span>
          <input type="range" min="-3" max="3" value="${STATE.faradayRate}" step="0.1" aria-label="Rate" oninput="STATE.faradayRate=+this.value;this.nextElementSibling.textContent=(+this.value).toFixed(1);sg(this)">
          <span class="val">${STATE.faradayRate.toFixed(1)}</span></div>
        <div class="mag-row"><span class="mag-row-lbl">Radius</span>
          <input type="range" min="30" max="140" value="${STATE.faradayR}" step="5" aria-label="Radius" oninput="STATE.faradayR=+this.value;this.nextElementSibling.textContent=this.value;sg(this)">
          <span class="val">${STATE.faradayR}</span></div>
        <p class="hint">Set the rate to 0 and the induced field goes away: only a change of B counts.</p>`;
      break;
    // Ampère–Maxwell: add current-carrying wires (current out of or into plane).
    case 3:
      area.innerHTML=`
        <div class="btn-row">
          <button class="tog-btn" onclick="addAmpWire(1)"><span class="sw" style="--sw:${COL.J}"></span>Wire, I out ⊙</button>
          <button class="tog-btn" onclick="addAmpWire(-1)"><span class="sw" style="--sw:${COL.J}"></span>Wire, I in ⊗</button>
        </div>
        <button class="tog-btn quiet" onclick="STATE.ampWires=[];STATE.ampTracers=[]">Clear the wires</button>
        <p class="hint">Drag a wire left or right. The capacitor below has no current in its gap, but its changing E still makes B.</p>`;
      break;
  }
  area.querySelectorAll('input[type=range]').forEach(sg);
}

// Switch the active law: mark its button and dock button, and refresh the
// card, controls, and scene. The card height can change, so fit the scene
// again.
/* ═══ EQUATION SWITCH ═══ */
function switchEq(idx){
  activeEq=idx;
  document.querySelectorAll('#dockEqs button').forEach(t=>t.classList.toggle('on',+t.dataset.eq===idx));
  renderCard();
  buildControls();
  initEq();
  fitScene();
}

// Seed a tab's scene when it becomes active: place default charges and the
// surface, center the dipole, or place a first wire. Units, so no reseed on
// resize.
/* ═══ INIT PER EQUATION ═══ */
const WIRE_Y=-70;   // the wire row, above the capacitor
function initEq(){
  switch(activeEq){
    case 0:
      if(!STATE.charges.length){
        STATE.charges=[{x:-55,y:0,q:1},{x:55,y:0,q:-1}];
      }
      STATE.gaussX=0;STATE.gaussY=0;
      break;
    case 1:
      STATE.dipX=0;STATE.dipY=0;
      break;
    case 2:
      break;
    case 3:
      if(!STATE.ampWires.length){
        STATE.ampWires=[{x:0,y:WIRE_Y,I:2}];
      }
      break;
  }
}

// Field formulas. All are 2D and use scene units; the numeric constants are
// tuned for visible arrow lengths, not physical units.
/* ═══ PHYSICS ═══ */
// Electric field of a point charge: magnitude q/r² (Coulomb inverse square),
// pointing away from a positive charge. Zero inside r² = 100 to avoid the
// singularity at the charge.
function eField(px,py,cx,cy,q){
  const dx=px-cx,dy=py-cy,r2=dx*dx+dy*dy;
  if(r2<100)return[0,0];
  const r=Math.sqrt(r2),F=q*12000/(r2);
  return[F*dx/r,F*dy/r];
}
// Superpose the field of every charge.
function totalE(px,py){
  let Ex=0,Ey=0;
  for(const c of STATE.charges){const[ex,ey]=eField(px,py,c.x,c.y,c.q);Ex+=ex;Ey+=ey;}
  return[Ex,Ey];
}
// Magnetic dipole field: the standard 3(m·r̂)r̂ − m form, falling off as 1/r³,
// with moment (mx,my) and strength str. Zero near the dipole.
function dipField(px,py,dx0,dy0,mx,my,str){
  const dx=px-dx0,dy=py-dy0,r2=dx*dx+dy*dy;
  if(r2<100)return[0,0];
  const r=Math.sqrt(r2),r3=r2*r,r5=r3*r2;
  const mdotr=mx*dx+my*dy;
  return[(3*mdotr*dx/r5-mx/r3)*str*100000,(3*mdotr*dy/r5-my/r3)*str*100000];
}
// Dipole field at the current pose, moment set by the angle control.
function totalB_dip(px,py){
  const mx=Math.cos(STATE.dipAngle),my=Math.sin(STATE.dipAngle);
  return dipField(px,py,STATE.dipX,STATE.dipY,mx,my,STATE.dipStr);
}
// Magnetic field of a straight wire (Biot–Savart): magnitude μ₀I/2πr, tangent to
// circles around the wire. The canvas y axis points down, so for a current
// out of the page (I > 0) the right-hand rule gives (dy, −dx)/r: counter-
// clockwise on the screen.
function wireB(px,py,wx,wy,I){
  const dx=px-wx,dy=py-wy,r2=dx*dx+dy*dy;
  if(r2<25)return[0,0];
  const r=Math.sqrt(r2),B=I*5/(r*6.2832); // 5x boost for visibility
  return[dy/r*B,-dx/r*B];
}
// Superpose the field of every wire.
function totalB_amp(px,py){
  let Bx=0,By=0;
  for(const w of STATE.ampWires){const[bx,by]=wireB(px,py,w.x,w.y,w.I);Bx+=bx;By+=by;}
  return[Bx,By];
}

// Scene actions invoked from the control buttons.
/* ═══ ACTIONS ═══ */
// Add a charge of sign q near the center with a small random offset.
function addCharge(q){
  STATE.charges.push({x:(Math.random()-0.5)*120,y:(Math.random()-0.5)*120,q});
}
// Remove all charges.
function clearCharges(){STATE.charges=[];}
// Add a wire with current direction dir, searching outward in rings for a free
// slot so wires do not overlap. Stay inside the visible width.
function addAmpWire(dir){
  const half=Math.max(60,(CW/2-30)/K);
  let x=0,placed=false;
  for(let ring=0;ring<8&&!placed;ring++){
    for(const tx of(ring===0?[0]:[-ring*60,ring*60])){
      if(Math.abs(tx)>half)continue;
      let ok=true;
      for(const w of STATE.ampWires)if(Math.abs(tx-w.x)<50){ok=false;break;}
      if(ok){x=tx;placed=true;break;}
    }
  }
  STATE.ampWires.push({x,y:WIRE_Y,I:dir*2});
}

/* ═══ DRAW HELPERS ═══ */
// The scene clock for the flow animation, in seconds.
let flowT=0;
// The visible area in units, with a margin. Field lines stop outside it.
function viewBox(m=40){const[l,t]=toUnits(0,0),[r,b]=toUnits(CW,CH);return{l:l-m,t:t-m,r:r+m,b:b+m};}
// A cache key for anything that depends on the scene fit.
const fitKey=()=>`${CW}|${CH}|${FX.toFixed(1)}|${FY.toFixed(1)}|${K.toFixed(4)}`;

// Integrate one field line from (x,y) in units with midpoint (RK2) steps
// along the unit field, in direction dir (+1 along, -1 against). The step
// grows with the distance from the origin of the scene, so far loops stay
// cheap. stop(x,y) ends the line (for example at a sink). Returns points
// in units.
function traceLine(field,x,y,dir,stop,box,maxSteps=900){
  const pts=[[x,y]];
  for(let i=0;i<maxSteps;i++){
    const h=Math.max(1.6,Math.hypot(x,y)*0.025)*dir;
    let[fx,fy]=field(x,y);let m=Math.hypot(fx,fy);if(m<1e-9)break;
    const mx=x+fx/m*h*0.5,my=y+fy/m*h*0.5;
    [fx,fy]=field(mx,my);m=Math.hypot(fx,fy);if(m<1e-9)break;
    x+=fx/m*h;y+=fy/m*h;pts.push([x,y]);
    if(stop&&stop(x,y))break;
    if(x<box.l||x>box.r||y<box.t||y>box.b)break;
  }
  return pts;
}
// Stroke a line of unit points as a smooth path (quadratic midpoints).
function pathUnits(pts){
  ctx.beginPath();
  if(pts.length<2)return;
  ctx.moveTo(px(pts[0][0]),py(pts[0][1]));
  for(let i=1;i<pts.length-1;i++){
    const xm=(pts[i][0]+pts[i+1][0])/2,ym=(pts[i][1]+pts[i+1][1])/2;
    ctx.quadraticCurveTo(px(pts[i][0]),py(pts[i][1]),px(xm),py(ym));
  }
  const L=pts[pts.length-1];ctx.lineTo(px(L[0]),py(L[1]));
}
// A field line: a faint base line and bright dashes that flow along it at
// speed (px/s). The dashes show the direction of the field.
function flowLine(pts,rgb,alpha,speed=40){
  if(pts.length<2)return;
  pathUnits(pts);
  ctx.setLineDash([]);
  ctx.strokeStyle=`rgba(${rgb},${0.22*alpha})`;ctx.lineWidth=1.1*T;ctx.stroke();
  ctx.setLineDash([7*T,15*T]);ctx.lineDashOffset=-flowT*speed;
  ctx.strokeStyle=`rgba(${rgb},${0.9*alpha})`;ctx.lineWidth=1.7*T;ctx.stroke();
  ctx.setLineDash([]);ctx.lineDashOffset=0;
}
// A small filled arrowhead at pixel (x,y), pointing along (nx,ny).
function head(x,y,nx,ny,s,fill){
  ctx.beginPath();ctx.moveTo(x+nx*s,y+ny*s);ctx.lineTo(x-nx*s*0.6-ny*s*0.62,y-ny*s*0.6+nx*s*0.62);
  ctx.lineTo(x-nx*s*0.6+ny*s*0.62,y-ny*s*0.6-nx*s*0.62);ctx.closePath();ctx.fillStyle=fill;ctx.fill();
}
// A glowing body (charge, wire, pole): a soft halo, a shaded sphere and a
// thin rim. r is in pixels.
function body(x,y,r,rgb){
  const halo=ctx.createRadialGradient(x,y,r*0.6,x,y,r*3);
  halo.addColorStop(0,`rgba(${rgb},0.28)`);halo.addColorStop(1,`rgba(${rgb},0)`);
  ctx.fillStyle=halo;ctx.beginPath();ctx.arc(x,y,r*3,0,Math.PI*2);ctx.fill();
  const g=ctx.createRadialGradient(x-r*0.35,y-r*0.4,r*0.1,x,y,r);
  g.addColorStop(0,'rgba(255,255,255,0.95)');g.addColorStop(0.35,`rgba(${rgb},1)`);g.addColorStop(1,`rgba(${rgb},0.75)`);
  ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle='rgba(255,255,255,0.35)';ctx.lineWidth=1;ctx.stroke();
}
// The sign on a body, drawn as strokes (no font): '+', '-', 'out' (a dot)
// or 'in' (a cross).
function sign(x,y,r,kind,rgb='10,12,18'){
  ctx.strokeStyle=`rgba(${rgb},0.9)`;ctx.fillStyle=`rgba(${rgb},0.9)`;ctx.lineWidth=Math.max(1.6,r*0.16);ctx.lineCap='round';
  const a=r*0.45;ctx.beginPath();
  if(kind==='+'||kind==='-'){ctx.moveTo(x-a,y);ctx.lineTo(x+a,y);}
  if(kind==='+'){ctx.moveTo(x,y-a);ctx.lineTo(x,y+a);}
  if(kind==='in'){const b=a*0.8;ctx.moveTo(x-b,y-b);ctx.lineTo(x+b,y+b);ctx.moveTo(x+b,y-b);ctx.lineTo(x-b,y+b);}
  ctx.stroke();
  if(kind==='out'){ctx.beginPath();ctx.arc(x,y,r*0.22,0,Math.PI*2);ctx.fill();}
  ctx.lineCap='butt';
}
// An out-of-page (dot) or into-page (cross) glyph for a field, r in px.
function perpGlyph(x,y,r,out,rgb,alpha){
  ctx.strokeStyle=`rgba(${rgb},${alpha})`;ctx.fillStyle=`rgba(${rgb},${alpha})`;ctx.lineWidth=Math.max(1,r*0.14);
  ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();
  if(out){ctx.beginPath();ctx.arc(x,y,r*0.3,0,Math.PI*2);ctx.fill();}
  else{const b=r*0.55;ctx.beginPath();ctx.moveTo(x-b,y-b);ctx.lineTo(x+b,y+b);ctx.moveTo(x+b,y-b);ctx.lineTo(x-b,y+b);ctx.stroke();}
}
// A dashed closed curve (surface or loop) in rgb.
function dashedRing(x,y,r,rgb,alpha){
  ctx.setLineDash([5*T,6*T]);ctx.strokeStyle=`rgba(${rgb},${alpha})`;ctx.lineWidth=1.3*T;
  ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);
}
// A small caps label at pixel (x,y).
function label(t,x,y,rgb='238,243,251',alpha=0.5,align='center'){
  ctx.font=font(10.5);ctx.textAlign=align;ctx.textBaseline='alphabetic';
  ctx.fillStyle=`rgba(${rgb},${alpha})`;
  if('letterSpacing' in ctx)ctx.letterSpacing='2px';
  ctx.fillText(t,x,y);
  if('letterSpacing' in ctx)ctx.letterSpacing='0px';
}

// Per-frame draw: clear, paint the background dots, then dispatch to the
// active law's own renderer.
/* ═══ RENDER ═══ */
function render(dt){
  flowT+=dt;
  ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.restore();
  ctx.fillStyle='#0a0c12';ctx.fillRect(0,0,CW,CH);
  // A faint glow of the law colour at the scene centre.
  const lc=activeEq===1||activeEq===3?RGB.B:RGB.E;
  const gl=ctx.createRadialGradient(FX,FY,0,FX,FY,Math.max(CW,CH)*0.55);
  gl.addColorStop(0,`rgba(${lc},0.045)`);gl.addColorStop(1,`rgba(${lc},0)`);
  ctx.fillStyle=gl;ctx.fillRect(0,0,CW,CH);
  // Dot grid, 40 units apart, on the scene origin.
  const g=40*K;
  ctx.fillStyle='rgba(150,200,255,0.10)';
  for(let x=((FX%g)+g)%g;x<CW;x+=g)for(let y=((FY%g)+g)%g;y<CH;y+=g)ctx.fillRect(x-0.6,y-0.6,1.2,1.2);

  switch(activeEq){
    case 0:renderGauss(dt);break;
    case 1:renderMonopoles(dt);break;
    case 2:renderFaraday(dt);break;
    case 3:renderAmpere(dt);break;
  }
}

// Law 0. E field lines from each positive charge to the negative charges
// (or out of view), with dashes that flow along E. Lines from a negative
// charge are traced back only where they do not start on a positive charge,
// so each line is drawn once. The Gaussian surface is a dashed ring; ticks
// on it show the sign of E·n̂. The enclosed charge goes to the readout.
/* ── EQ 0: GAUSS'S LAW ── */
let gaussCache={key:'',lines:[]};
const QR=12;   // the charge radius in units; field lines stop inside it
function gaussLines(){
  const key=fitKey()+JSON.stringify(STATE.charges);
  if(gaussCache.key===key)return gaussCache.lines;
  const box=viewBox(),lines=[],N=16;
  const near=(x,y,q)=>STATE.charges.some(c=>c.q===q&&(x-c.x)**2+(y-c.y)**2<QR*QR);
  for(const c of STATE.charges){
    for(let i=0;i<N;i++){
      const a=(i+0.5)/N*Math.PI*2,x=c.x+Math.cos(a)*QR,y=c.y+Math.sin(a)*QR;
      if(c.q>0)lines.push(traceLine(totalE,x,y,1,(u,v)=>near(u,v,-1),box));
      else{
        const p=traceLine(totalE,x,y,-1,(u,v)=>near(u,v,1),box);
        const L=p[p.length-1];
        if(!near(L[0],L[1],1))lines.push(p.reverse());
      }
    }
  }
  gaussCache={key,lines};
  return lines;
}
function renderGauss(dt){
  const gx=px(STATE.gaussX),gy=py(STATE.gaussY),gR=STATE.gaussR*K;
  let Qenc=0;
  for(const c of STATE.charges){
    const dx=c.x-STATE.gaussX,dy=c.y-STATE.gaussY;
    if(dx*dx+dy*dy<STATE.gaussR*STATE.gaussR)Qenc+=c.q;
  }
  // A faint tint inside the surface in the colour of the enclosed charge.
  if(Qenc!==0){ctx.fillStyle=`rgba(${Qenc>0?RGB.Q:RGB.Qn},0.05)`;ctx.beginPath();ctx.arc(gx,gy,gR,0,Math.PI*2);ctx.fill();}

  ctx.save();ctx.globalCompositeOperation='lighter';
  for(const l of gaussLines())flowLine(l,RGB.E,0.8,38);
  ctx.restore();

  // The surface, and a tick per 15 degrees for the sign of E·n̂.
  dashedRing(gx,gy,gR,RGB.ink,0.5);
  for(let i=0;i<24;i++){
    const a=i/24*Math.PI*2,nr=Math.cos(a),nt=Math.sin(a);
    const[Ex,Ey]=totalE(STATE.gaussX+nr*STATE.gaussR,STATE.gaussY+nt*STATE.gaussR);
    const f=Ex*nr+Ey*nt;if(Math.abs(f)<0.02)continue;
    const len=Math.min(14,4+Math.abs(f)*4)*T,d=f>0?1:-1;
    const sx=gx+nr*gR,sy=gy+nt*gR,ex=sx+nr*len*d,ey=sy+nt*len*d;
    ctx.strokeStyle=`rgba(${RGB.ink},0.55)`;ctx.lineWidth=1.2*T;
    ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);ctx.stroke();
    head(ex,ey,nr*d,nt*d,3.2*T,`rgba(${RGB.ink},0.65)`);
  }
  label('GAUSSIAN SURFACE',gx,gy-gR-12*T);

  for(const c of STATE.charges){
    const x=px(c.x),y=py(c.y),r=Math.max(10,QR*K);
    body(x,y,r,c.q>0?RGB.Q:RGB.Qn);sign(x,y,r,c.q>0?'+':'-');
  }
  setReadout(`<span class="r"><i>Q</i><sub>enc</sub> = <b>${sgn(Qenc)}</b> q</span>`+
    `<span class="r">${STATE.charges.length} charge${STATE.charges.length===1?'':'s'} in the scene</span>`+
    `<span class="note">${Qenc===0?'Net flux through the surface: zero':'Net flux '+(Qenc>0?'outward':'inward')+', Φ = Q<sub>enc</sub>/ε₀'}</span>`);
}

// Law 1. Field lines of the dipole, traced from its north face round to its
// south face, then closed through the bar. Each line is a closed loop. The
// readout counts how often the closed lines cross the surface outward and
// inward; for a closed loop the two counts are equal.
/* ── EQ 1: NO MONOPOLES ── */
let dipCache={key:'',lines:[],out:0,inn:0};
const DIP_SR=125;   // the closed surface radius in units
function dipoleLines(){
  const key=fitKey()+[STATE.dipX,STATE.dipY,STATE.dipAngle].map(v=>v.toFixed(3)).join(',');
  if(dipCache.key===key)return dipCache;
  const mx=Math.cos(STATE.dipAngle),my=Math.sin(STATE.dipAngle),box=viewBox(400);
  const lines=[],r0=40;
  // Seeds on a circle just outside the bar, on the north side, from 18 to
  // 62 degrees off the axis, on both sides of it. A dipole line reaches
  // r0/sin²θ, so these loops span from the bar to the edge of the view.
  for(const side of[1,-1])for(const deg of[18,24,30,37,44,52,62]){
    const th=deg*Math.PI/180*side;
    const ax=mx*Math.cos(th)-my*Math.sin(th),ay=mx*Math.sin(th)+my*Math.cos(th);
    const x=STATE.dipX+ax*r0,y=STATE.dipY+ay*r0;
    const p=traceLine(totalB_dip,x,y,1,(u,v)=>(u-STATE.dipX)**2+(v-STATE.dipY)**2<r0*r0*0.8,box,2400);
    // Close the loop through the bar: from the south end back to the seed.
    const L=p[p.length-1];
    if((L[0]-STATE.dipX)**2+(L[1]-STATE.dipY)**2<r0*r0)p.push([STATE.dipX-mx*8,STATE.dipY-my*8],[STATE.dipX+mx*8,STATE.dipY+my*8],[x,y]);
    lines.push(p);
  }
  // Count the crossings of the closed surface by the closed lines.
  let out=0,inn=0;
  for(const p of lines){
    for(let i=1;i<p.length;i++){
      const a=Math.hypot(p[i-1][0]-STATE.dipX,p[i-1][1]-STATE.dipY)<DIP_SR,b=Math.hypot(p[i][0]-STATE.dipX,p[i][1]-STATE.dipY)<DIP_SR;
      if(a&&!b)out++;else if(!a&&b)inn++;
    }
  }
  dipCache={key,lines,out,inn};
  return dipCache;
}
function renderMonopoles(dt){
  const D=dipoleLines(),dx=px(STATE.dipX),dy=py(STATE.dipY);
  ctx.save();ctx.globalCompositeOperation='lighter';
  for(const l of D.lines)flowLine(l,RGB.B,0.8,36);
  ctx.restore();
  dashedRing(dx,dy,DIP_SR*K,RGB.ink,0.45);
  label('CLOSED SURFACE',dx,dy-DIP_SR*K-12*T);

  // The bar magnet, 70 by 24 units: north half coral, south half periwinkle.
  ctx.save();ctx.translate(dx,dy);ctx.rotate(STATE.dipAngle);ctx.scale(K,K);
  const shade=(x0,x1,rgb)=>{const g=ctx.createLinearGradient(0,-12,0,12);g.addColorStop(0,`rgba(${rgb},1)`);g.addColorStop(1,`rgba(${rgb},0.65)`);ctx.fillStyle=g;ctx.fillRect(x0,-12,x1-x0,24);};
  ctx.shadowColor='rgba(0,0,0,0.6)';ctx.shadowBlur=14;
  ctx.beginPath();ctx.roundRect?ctx.roundRect(-35,-12,70,24,5):ctx.rect(-35,-12,70,24);ctx.save();ctx.clip();
  ctx.shadowBlur=0;shade(0,35,RGB.Q);shade(-35,0,RGB.Qn);ctx.restore();
  ctx.strokeStyle='rgba(255,255,255,0.35)';ctx.lineWidth=1/K;ctx.stroke();
  ctx.shadowBlur=0;
  ctx.font='600 13px "Space Grotesk", sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';
  ctx.fillStyle='rgba(10,12,18,0.85)';ctx.fillText('N',17.5,0.5);ctx.fillText('S',-17.5,0.5);
  ctx.restore();

  setReadout(`<span class="r">lines out <b>${D.out}</b> &nbsp; lines in <b>${D.inn}</b></span>`+
    `<span class="r"><i>Φ</i><sub>B</sub> = <b>0</b></span><span class="note">Every line that leaves the surface comes back in</span>`);
}

// Law 2. A disc of uniform B that oscillates, shown as out-of-page dots or
// into-page crosses. Its change induces E on circles round the centre:
// E = (r/2)|∂B/∂t| inside the disc and (R²/2r)|∂B/∂t| outside it. The
// dashes flow at a speed set by E. By Lenz's law, E turns clockwise on the
// screen while the out-of-page flux grows.
/* ── EQ 2: FARADAY'S LAW ── */
function renderFaraday(dt){
  STATE.faradayTime+=dt*STATE.faradayRate;
  const cx=FX,cy=FY,Ru=STATE.faradayR,R=Ru*K;
  const Bval=Math.sin(STATE.faradayTime*2);
  const dBdt=Math.cos(STATE.faradayTime*2)*STATE.faradayRate*2;
  const Eind=Math.abs(dBdt)*0.5;
  const s=dBdt>0?1:-1;   // +1: clockwise on the screen

  // The B region: a soft disc, and glyphs whose size and alpha follow |B|.
  const disc=ctx.createRadialGradient(cx,cy,0,cx,cy,R);
  disc.addColorStop(0,`rgba(${RGB.B},${0.04+Math.abs(Bval)*0.14})`);disc.addColorStop(1,`rgba(${RGB.B},${0.02+Math.abs(Bval)*0.06})`);
  ctx.fillStyle=disc;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle=`rgba(${RGB.B},0.35)`;ctx.lineWidth=1*T;ctx.stroke();
  const step=24,n=Math.floor(Ru/step);
  for(let i=-n;i<=n;i++)for(let j=-n;j<=n;j++){
    if((i*i+j*j)*step*step>(Ru-8)*(Ru-8))continue;
    perpGlyph(cx+i*step*K,cy+j*step*K,(3+3.5*Math.abs(Bval))*Math.min(K,1.6),Bval>=0,RGB.B,0.25+Math.abs(Bval)*0.6);
  }

  // Induced E on circles inside and outside the disc.
  if(Eind>0.01){
    const radii=[];for(let k=1;k<=2;k++)radii.push(Ru*k/3);
    for(let r=Ru+22;r<Ru+170;r+=34)radii.push(r);
    const Emax=Ru/2*Math.abs(dBdt);
    ctx.save();ctx.globalCompositeOperation='lighter';
    for(const r of radii){
      const E=(r<Ru?r/2:Ru*Ru/(2*r))*Math.abs(dBdt),a=Math.min(1,0.25+0.75*E/Math.max(Emax,1e-6));
      const pts=[];for(let k=0;k<=96;k++){const t=k/96*Math.PI*2*s;pts.push([Math.cos(t)*r,Math.sin(t)*r]);}
      flowLine(pts,RGB.E,a,10+E*60);
      // Four arrowheads show the sense when the flow is slow.
      for(let q=0;q<4;q++){
        const t=q*Math.PI/2+Math.PI/4,x=cx+Math.cos(t)*r*K,y=cy+Math.sin(t)*r*K;
        head(x,y,-Math.sin(t)*s,Math.cos(t)*s,3.6*T,`rgba(${RGB.E},${0.85*a})`);
      }
    }
    ctx.restore();
  }
  setReadout(`<span class="r"><i>B</i> = <b>${sgn(Bval,2)}</b> ${Bval>=0?'out of the page':'into the page'}</span>`+
    `<span class="r"><i>∂B/∂t</i> = <b>${sgn(dBdt,2)}</b> &nbsp; |<i>E</i>| at the rim = <b>${Eind.toFixed(2)}</b></span>`+
    `<span class="note">${Math.abs(dBdt)<0.1?'B does not change, so no E is induced':'E turns '+(s>0?'clockwise':'counterclockwise')+', against the change of flux'}</span>`);
}

// Law 3. Two halves of the same law. Part 1: wire currents (out of or into
// the page) make B on closed curves round them. The B lines are level
// curves of A = Σ -I ln r (marching squares), and tracers flow along B.
// An Amperian loop round the first wire shows the circulation. Part 2: a
// charging capacitor. Its changing E in the gap is the displacement
// current ε₀∂E/∂t, and B turns round the gap on a ring seen at a tilt:
// out of the page on one side, into it on the other.
/* ── EQ 3: AMPERE-MAXWELL ── */
let ampCache={key:'',segs:[]};
function ampereContours(){
  const key=fitKey()+JSON.stringify(STATE.ampWires.map(w=>[w.x,w.y,w.I]));
  if(ampCache.key===key)return ampCache.segs;
  const cell=8,nx=Math.ceil(CW/cell)+1,ny=Math.ceil(CH/cell)+1,A=new Float32Array(nx*ny);
  let Imax=0;for(const w of STATE.ampWires)Imax=Math.max(Imax,Math.abs(w.I));
  for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){
    const[u,v]=toUnits(i*cell,j*cell);let a=0;
    for(const w of STATE.ampWires)a-=w.I*Math.log(Math.max(4,Math.hypot(u-w.x,v-w.y)));
    A[j*nx+i]=a;
  }
  // Levels every dA. For one wire the curves are circles whose radii grow
  // in a fixed ratio, dense near the wire and sparse far away.
  const dA=0.42*Imax,segs=[];
  if(dA>0){
    let lo=Infinity,hi=-Infinity;for(const a of A){if(a<lo)lo=a;if(a>hi)hi=a;}
    for(let lv=Math.ceil(lo/dA)*dA;lv<hi;lv+=dA){
      for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){
        const a=A[j*nx+i]-lv,b=A[j*nx+i+1]-lv,c=A[(j+1)*nx+i+1]-lv,d=A[(j+1)*nx+i]-lv;
        const e=[];const X=i*cell,Y=j*cell;
        if((a>0)!==(b>0))e.push([X+cell*a/(a-b),Y]);
        if((b>0)!==(c>0))e.push([X+cell,Y+cell*b/(b-c)]);
        if((c>0)!==(d>0))e.push([X+cell*(1-c/(c-d)),Y+cell]);
        if((d>0)!==(a>0))e.push([X,Y+cell*(1-d/(d-a))]);
        if(e.length>=2)segs.push(e[0][0],e[0][1],e[1][0],e[1][1]);
        if(e.length===4)segs.push(e[2][0],e[2][1],e[3][0],e[3][1]);
      }
    }
  }
  ampCache={key,segs};
  return segs;
}
function renderAmpere(dt){
  STATE.ampTime=(STATE.ampTime||0)+dt;

  // ── PART 1: wire currents → B on closed curves (μ₀J term) ──
  if(STATE.ampWires.length>0){
    const segs=ampereContours();
    ctx.strokeStyle=`rgba(${RGB.B},0.2)`;ctx.lineWidth=1*T;ctx.beginPath();
    for(let i=0;i<segs.length;i+=4){ctx.moveTo(segs[i],segs[i+1]);ctx.lineTo(segs[i+2],segs[i+3]);}
    ctx.stroke();

    // Tracers: short comets that flow along B.
    if(!STATE.ampTracers)STATE.ampTracers=[];
    for(const w of STATE.ampWires){
      if(Math.random()<0.45){
        const a=Math.random()*Math.PI*2,r=18+Math.random()*110;
        STATE.ampTracers.push({x:w.x+Math.cos(a)*r,y:w.y+Math.sin(a)*r,trail:[],age:0,maxAge:2+Math.random()*2});
      }
    }
    const speed=90,[uL,uT]=toUnits(-10,-10),[uR,uB]=toUnits(CW+10,CH+10);
    ctx.save();ctx.globalCompositeOperation='lighter';ctx.lineCap='round';
    for(let i=STATE.ampTracers.length-1;i>=0;i--){
      const tr=STATE.ampTracers[i];tr.age+=dt;
      const[Bx,By]=totalB_amp(tr.x,tr.y),Bm=Math.hypot(Bx,By);
      if(Bm>1e-6){tr.x+=Bx/Bm*speed*dt;tr.y+=By/Bm*speed*dt;}
      tr.trail.unshift([tr.x,tr.y]);if(tr.trail.length>16)tr.trail.pop();
      if(tr.age>tr.maxAge||tr.x<uL||tr.x>uR||tr.y<uT||tr.y>uB){STATE.ampTracers.splice(i,1);continue;}
      const tl=tr.trail.length;if(tl<2)continue;
      const ageA=tr.age<0.25?tr.age/0.25:tr.age>tr.maxAge*0.7?(tr.maxAge-tr.age)/(tr.maxAge*0.3):1;
      for(let k=0;k<tl-1;k++){
        const a0=(1-k/tl)*ageA;if(a0<0.03)continue;
        ctx.strokeStyle=`rgba(${RGB.B},${a0*0.75})`;ctx.lineWidth=Math.max(0.6,2.2*a0)*T;
        ctx.beginPath();ctx.moveTo(px(tr.trail[k][0]),py(tr.trail[k][1]));ctx.lineTo(px(tr.trail[k+1][0]),py(tr.trail[k+1][1]));ctx.stroke();
      }
    }
    if(STATE.ampTracers.length>500)STATE.ampTracers.splice(0,STATE.ampTracers.length-500);
    ctx.restore();

    // The Amperian loop round the first wire, with its sense: by the right
    // hand rule, counterclockwise on the screen for a current out of it.
    const w0=STATE.ampWires[0],wx=px(w0.x),wy=py(w0.y),loopR=62*K,s=w0.I>0?1:-1;
    dashedRing(wx,wy,loopR,RGB.J,0.55);
    for(let i=0;i<8;i++){
      const a=i/8*Math.PI*2+STATE.ampTime*0.35*s*-1;
      head(wx+Math.cos(a)*loopR,wy+Math.sin(a)*loopR,Math.sin(a)*s,-Math.cos(a)*s,4*T,`rgba(${RGB.J},0.8)`);
    }
    label('AMPERIAN LOOP',wx,wy-loopR-12*T,RGB.J,0.6);
  }

  // ── PART 2: displacement current (ε₀ ∂E/∂t term) ──
  const cx=px(0),capY=py(105),capGap=46*K,plateW=110*K,plateH=7*K;
  const capCharge=Math.sin(STATE.ampTime*1.5)*0.8;
  const dEdt=Math.cos(STATE.ampTime*1.5)*1.5*0.8;
  const top=capCharge>=0?RGB.Q:RGB.Qn,bot=capCharge>=0?RGB.Qn:RGB.Q;
  // The B ring round the gap: an ellipse seen from a little above. s>0: E
  // points down and grows, so B is out of the page on the right side.
  const s=dEdt>0?1:-1,ra=plateW*0.72,rb=ra*0.24,bA=Math.min(1,Math.abs(dEdt)/1.2);
  const ring=(from,to,alpha)=>{
    const pts=[];for(let k=0;k<=48;k++){const t=from+(to-from)*k/48;pts.push([(cx+Math.cos(t)*ra-FX)/K,(capY+Math.sin(t)*rb-FY)/K]);}
    if(s<0)pts.reverse();
    flowLine(pts,RGB.B,alpha,12+30*Math.abs(dEdt));
  };
  ctx.save();ctx.globalCompositeOperation='lighter';
  if(bA>0.08)ring(Math.PI,Math.PI*2,0.45*bA);   // the back half, behind the gap
  ctx.restore();

  // Plates, with the charge sign in their colour.
  const plate=(y,rgb)=>{const g=ctx.createLinearGradient(0,y,0,y+plateH);g.addColorStop(0,'rgba(220,228,240,0.85)');g.addColorStop(1,'rgba(120,132,150,0.85)');
    ctx.fillStyle=g;ctx.beginPath();ctx.roundRect?ctx.roundRect(cx-plateW/2,y,plateW,plateH,2):ctx.rect(cx-plateW/2,y,plateW,plateH);ctx.fill();
    if(Math.abs(capCharge)>0.08){ctx.fillStyle=`rgba(${rgb},${0.25+Math.abs(capCharge)*0.7})`;ctx.fillRect(cx-plateW/2+2,y+(rgb===top?plateH-2:0),plateW-4,2);}};
  plate(capY-capGap/2-plateH,top);plate(capY+capGap/2,bot);
  // E in the gap: five lines from the + plate to the − plate.
  if(Math.abs(capCharge)>0.05){
    const dir=capCharge>0?1:-1,eA=Math.min(1,Math.abs(capCharge)*1.2);
    ctx.save();ctx.globalCompositeOperation='lighter';
    for(let i=0;i<5;i++){
      const ex=(cx-plateW/3+i*(plateW*2/3)/4-FX)/K,y0=(capY-capGap/2+2*K-FY)/K,y1=(capY+capGap/2-2*K-FY)/K;
      flowLine(dir>0?[[ex,y0],[ex,y1]]:[[ex,y1],[ex,y0]],RGB.E,eA,26);
    }
    ctx.restore();
  }
  ctx.save();ctx.globalCompositeOperation='lighter';
  if(bA>0.08){
    ring(0,Math.PI,0.95*bA);   // the front half, in front of the gap
    perpGlyph(cx+ra,capY,5*T,s>0,RGB.B,0.9*bA);perpGlyph(cx-ra,capY,5*T,s<0,RGB.B,0.9*bA);
  }
  ctx.restore();
  label('CAPACITOR',cx,capY-capGap/2-plateH-12*T);

  // Wires on top: a gold body with the direction of I.
  for(const w of STATE.ampWires){
    const x=px(w.x),y=py(w.y),r=Math.max(10,12*K);
    body(x,y,r,RGB.J);sign(x,y,r,w.I>0?'out':'in');
    ctx.font=font(11);ctx.textAlign='center';ctx.textBaseline='top';ctx.fillStyle=`rgba(${RGB.J},0.8)`;
    ctx.fillText(`${Math.abs(w.I)} A ${w.I>0?'out':'in'}`,x,y+r+8*T);
  }

  const Ienc=STATE.ampWires.length?STATE.ampWires[0].I:0;
  setReadout((STATE.ampWires.length?`<span class="r">loop: <i>I</i><sub>enc</sub> = <b>${sgn(Ienc)}</b> A</span>`:'')+
    `<span class="r">gap: <i>∂E/∂t</i> = <b>${sgn(dEdt,2)}</b></span>`+
    `<span class="note">${Math.abs(dEdt)>0.1?'No charge crosses the gap, but B still turns round it':'E is not changing, so the gap makes no B'}</span>`);
}

// Pointer dragging. onDown picks the nearest draggable object for the active tab
// (a charge or the surface, the dipole, or a wire); onMove updates its position;
// release clears the grab. getPos maps a mouse or touch event to scene units.
// The pick radius is at least 24px, so a finger can hit small objects.
/* ═══ DRAG ═══ */
let dragObj=null,dragOff=[0,0];
function getPos(e){const r=canvas.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return toUnits(t.clientX-r.left,t.clientY-r.top);}
canvas.addEventListener('mousedown',onDown);canvas.addEventListener('touchstart',onDown,{passive:false});
function onDown(e){
  e.preventDefault();const[x,y]=getPos(e);
  const hit=(u)=>Math.max(u,24/K)**2;
  if(activeEq===0){
    // Drag charges or gaussian surface
    for(const c of STATE.charges){if((x-c.x)**2+(y-c.y)**2<hit(20)){dragObj={type:'charge',ref:c};dragOff=[c.x-x,c.y-y];return;}}
    if((x-STATE.gaussX)**2+(y-STATE.gaussY)**2<(STATE.gaussR+20)**2){dragObj={type:'gauss'};dragOff=[STATE.gaussX-x,STATE.gaussY-y];return;}
  }
  if(activeEq===1){
    if((x-STATE.dipX)**2+(y-STATE.dipY)**2<hit(40)){dragObj={type:'dip'};dragOff=[STATE.dipX-x,STATE.dipY-y];return;}
  }
  if(activeEq===3){
    for(const w of STATE.ampWires){if((x-w.x)**2+(y-w.y)**2<hit(22)){dragObj={type:'ampw',ref:w};dragOff=[w.x-x,0];return;}}
  }
}
window.addEventListener('mousemove',onMove);window.addEventListener('touchmove',onMove,{passive:false});
function onMove(e){
  if(!dragObj)return;e.preventDefault();const[x,y]=getPos(e);
  switch(dragObj.type){
    case'charge':dragObj.ref.x=x+dragOff[0];dragObj.ref.y=y+dragOff[1];break;
    case'gauss':STATE.gaussX=x+dragOff[0];STATE.gaussY=y+dragOff[1];break;
    case'dip':STATE.dipX=x+dragOff[0];STATE.dipY=y+dragOff[1];break;
    case'ampw':dragObj.ref.x=x+dragOff[0];break;
  }
}
window.addEventListener('mouseup',()=>dragObj=null);
window.addEventListener('touchend',()=>dragObj=null);

// Phone sheet. The dock button opens and closes the panel. A tap on the grip
// switches half and full height. A drag up gives full height. A drag down
// gives half height, then closes. On wide screens the panel is always open.
/* ═══ PHONE SHEET ═══ */
const PHONE_Q=window.matchMedia('(max-width:768px), (max-height:500px) and (pointer:coarse)');
const panel=document.getElementById('panel'),dockPanel=document.getElementById('dockPanel');
function setOpen(open){
  panel.classList.toggle('open',open);
  if(!open)panel.classList.remove('full');
  dockPanel.classList.toggle('on',open);
  dockPanel.setAttribute('aria-expanded',String(open));
}
dockPanel.addEventListener('click',()=>setOpen(!panel.classList.contains('open')));
setOpen(false);
PHONE_Q.addEventListener('change',()=>setOpen(false));
{
  const grip=document.getElementById('sheetGrip');
  let gripY=null;
  grip.addEventListener('pointerdown',e=>{gripY=e.clientY;try{grip.setPointerCapture(e.pointerId);}catch(x){}});
  grip.addEventListener('pointerup',e=>{
    if(gripY===null)return;
    const dy=e.clientY-gripY;gripY=null;
    if(Math.abs(dy)<8)panel.classList.toggle('full');
    else if(dy<-40)panel.classList.add('full');
    else if(dy>40){if(panel.classList.contains('full'))panel.classList.remove('full');else setOpen(false);}
  });
  grip.addEventListener('pointercancel',()=>{gripY=null;});
}

// Fit the canvas to its wrapper and scale the backing store by device pixel
// ratio (capped at 2). Then fit the scene to the free area. A change to the
// wrapper or to the card height calls resize again.
/* ═══ RESIZE ═══ */
function resize(){
  const w=document.getElementById('canvas-wrap');
  CW=w.clientWidth;CH=w.clientHeight;
  if(CW<10)CW=300;if(CH<10)CH=300;
  const dpr=Math.min(devicePixelRatio,2);
  canvas.width=Math.round(CW*dpr);canvas.height=Math.round(CH*dpr);
  ctx.setTransform(dpr,0,0,dpr,0,0);
  fitScene();
}
if(window.ResizeObserver){
  const ro=new ResizeObserver(()=>resize());
  ro.observe(document.getElementById('canvas-wrap'));
  ro.observe(document.getElementById('card'));
}else window.addEventListener('resize',resize);

// The animation loop: measure the frame delta and render the active law.
/* ═══ LOOP ═══ */
let lastTime=0;
function loop(time){
  requestAnimationFrame(loop);
  const dt=Math.min((time-lastTime)/1000,0.05);lastTime=time;
  render(dt);
}

// Boot after a short delay so layout settles: size the canvas, open the first
// equation, and start the loop. Fit again when the web fonts load, because
// the card height changes.
/* ═══ INIT ═══ */
setTimeout(()=>{
  buildLaws();
  resize();
  switchEq(0);
  requestAnimationFrame(loop);
},50);
if(document.fonts&&document.fonts.ready)document.fonts.ready.then(()=>fitScene());

// Screensaver hook for the shell (lib/screensaver.js). enter() hides the GUI
// and makes #canvas-wrap fill the window, so the observer calls resize(). The
// card stays in the layout but is hidden, so fitScene keeps its band free.
// The hook then draws the law name and the differential form into that band
// on the canvas, because a recording holds only the canvas. The autopilot
// shows each law for max(15, seconds/4) s, from opts.seed % 4. It fades the
// canvas to the background colour across each law switch. Each law moves
// slowly: the charges turn and the surface drifts, the magnet turns, and the
// Faraday and Ampère clocks run. calm 1 runs the scene clock at 0.4.
/* ═══ SCREENSAVER ═══ */
window.snSaver={async enter(opts){
  while(!lastTime)await new Promise(r=>setTimeout(r,50));
  const calm=Math.max(0,Math.min(1,+opts.calm||0)),sp=1-0.6*calm;
  const hold=Math.max(15,(+opts.seconds||60)/4),FADE=0.9;
  const st=document.createElement('style');
  st.textContent='html.saver #panel,html.saver .topbar,html.saver #dock,html.saver #readout,html.saver #legend,html.saver .card-int,html.saver .card-line{display:none!important}'+
    'html.saver #card{visibility:hidden}html.saver #canvas-wrap{position:fixed;inset:0;z-index:1}html.saver #canvas-wrap::after{display:none}html.saver #sim-canvas{cursor:none}';
  document.head.appendChild(st);document.documentElement.classList.add('saver');
  // The differential form of each law as an image, from the MathJax SVG.
  const eqImg=(window.MAXWELL_EQ||[]).map(e=>{
    const svg=e.d.replace(/currentColor/g,COL.ink).replace(/ (role|style|aria-label|focusable)="[^"]*"/g,'');
    const m=/viewBox="([^"]*)"/.exec(svg),vb=m?m[1].split(/\s+/).map(Number):[0,0,4,1];
    const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);
    return{img,vb};
  });
  STATE.charges=[{x:-55,y:0,q:1},{x:55,y:0,q:-1}];STATE.ampWires=[{x:0,y:WIRE_Y,I:2}];
  STATE.faradayRate=1;STATE.gaussR=70;
  let law=(opts.seed>>>0)%4,clock=0,tLaw=0,phi=0;
  switchEq(law);
  const base=render;
  render=function(dt){
    clock+=dt*sp;tLaw+=dt;
    if(tLaw>hold){tLaw=0;law=(law+1)%4;switchEq(law);}
    // Slow motion of the active scene, in scene units.
    if(activeEq===0){
      phi=clock*0.06;
      const c=Math.cos(phi)*55,s=Math.sin(phi)*55;
      STATE.charges[0].x=-c;STATE.charges[0].y=-s;STATE.charges[1].x=c;STATE.charges[1].y=s;
      STATE.gaussX=100*Math.sin(clock*0.19);STATE.gaussY=35*Math.sin(clock*0.13);
    }else if(activeEq===1){
      STATE.dipAngle=0.6*Math.sin(clock*0.11)+clock*0.05;
      STATE.dipX=30*Math.sin(clock*0.07);
    }
    base(dt*sp);
    drawCaption();
    // Fade out before a switch and in after it.
    const f=Math.max(0,1-tLaw/FADE,1-(hold-tLaw)/FADE);
    if(f>0){ctx.fillStyle=`rgba(10,12,18,${Math.min(1,f)})`;ctx.fillRect(0,0,CW,CH);}
  };
  // The law name and form at the card position, and the plain line at the base.
  function drawCaption(){
    const l=LAWS[activeEq],e=eqImg[activeEq],x=34,em=parseFloat(getComputedStyle(document.documentElement).fontSize)||16;
    if('letterSpacing' in ctx)ctx.letterSpacing='0.2em';
    ctx.textAlign='left';ctx.textBaseline='top';
    ctx.font=`500 ${Math.round(0.7*em)}px "IBM Plex Mono", ui-monospace, monospace`;ctx.fillStyle=l.c;
    ctx.fillText(`${l.num}   ${l.name.toUpperCase()}`,x,26);
    if('letterSpacing' in ctx)ctx.letterSpacing='0px';
    // MathJax units are 1/1000 em at the card font size, on a shared baseline.
    if(e&&e.img.complete&&e.img.naturalWidth){const k=2.35*em/1000,y0=26+0.7*em+12+1.15*2.35*em;ctx.drawImage(e.img,x,y0+e.vb[1]*k,e.vb[2]*k,e.vb[3]*k);}
    ctx.textBaseline='alphabetic';
    ctx.font=`italic 400 ${Math.round(1.15*em)}px "Instrument Serif", Georgia, serif`;ctx.fillStyle=`rgba(${RGB.ink},0.72)`;
    ctx.fillText(l.line,x,CH-26);
  }
  return{canvas,warmupMs:1500};
}};
