// ============================================================================
//  MAXWELL'S EQUATIONS  ·  interactive explorer
// ----------------------------------------------------------------------------
//  Four canvas scenes, one per law. A law button selects activeEq; switchEq
//  fills the card, the legend and the controls, and seeds the scene. One
//  render(dt) dispatches to the active law's own draw routine each frame.
//  All scene state lives in STATE; controls and drag handlers change it.
//
//  THE FOUR LAWS
//  --------------------------------------------------------------------------
//      0  Gauss ∇·E = ρ/ε₀      charges + a Gaussian surface; flux = enclosed Q
//      1  Gauss ∇·B = 0         a dipole magnet; every closed surface nets zero
//      2  Faraday ∇×E = −∂B/∂t  oscillating B induces a circulating E (Lenz sign)
//      3  Ampère–Maxwell        wire currents give μ₀J·B, plus the capacitor's
//                               displacement current ε₀∂E/∂t circulating B
//
//  COLOUR
//  --------------------------------------------------------------------------
//      COL holds one colour per field: E amber, B cyan, + charge coral,
//      − charge periwinkle, current gold. style.css (--E, --B, ...) and
//      typeset.mjs use the same values, so a term in an equation has the
//      colour of its field on the canvas. A law takes the colour of the
//      field on its left side (LAWS[i].c).
//
//  EQUATIONS
//  --------------------------------------------------------------------------
//      equations.js (GENERATED by typeset.mjs) sets window.MAXWELL_EQ: the
//      MathJax SVG of each differential and integral form. No math library
//      loads at run time. KaTeX HTML broke in Safari.
//
//  SCENE UNITS
//  --------------------------------------------------------------------------
//      All positions and sizes in STATE are scene units, not pixels. The
//      origin is the center of the free area: the canvas area below the
//      law card and above the legend. The scene is SCENE units across.
//      fitScene sets K, the pixels per unit, so the scene fills the free
//      area at any window shape. px(u) and py(v) change units to pixels.
//      toUnits changes pixels to units.
//
//  SCREEN LAYOUT   (the leading marker is an element id)
//  --------------------------------------------------------------------------
//      #panel       title, #laws (one button per law), controls, About
//      #canvas-wrap #sim-canvas, #card, #legend, #readout
//      #dock        phone only: panel button and law buttons
//
//  FRAME PIPELINE
//  --------------------------------------------------------------------------
//      loop(t) ─ render(dt) ─ clear + grid ─▶ renderGauss / renderMonopoles /
//                                             renderFaraday / renderAmpere
//
//  SECTION MAP   (jump with grep -n "<anchor>" main.js)
//  --------------------------------------------------------------------------
//      colours ............. "const COL"           field colours
//      laws ................ "const LAWS"          name, colour, text per law
//      scale ............... "function fitScene"    free area, K, px, py, font
//      state ............... "const STATE="        all scene state
//      card ................ "function renderCard"  card, legend, law list
//      readout ............. "function setReadout"  numbers at the base
//      controls ............ "function buildControls"  per-law control markup
//      law switch .......... "function switchEq"    change the active law
//      per-law init ........ "function initEq"      seed a scene on entry
//      physics ............. "function eField"      field formulas
//      actions ............. "function addCharge"   add/clear scene objects
//      arrow ............... "function arrow"       one field arrow
//      render dispatch ..... "function render"      clear, grid, dispatch
//      Gauss draw .......... "function renderGauss" law 0
//      monopoles draw ...... "function renderMonopoles"  law 1
//      Faraday draw ........ "function renderFaraday"    law 2
//      Ampère draw ......... "function renderAmpere"     law 3
//      drag ................ "function getPos"      pointer picking and drag
//      phone sheet ......... "function setOpen"     dock, sheet, and grip
//      resize .............. "function resize"      canvas sizing and DPR
//      loop ................ "function loop"        per-frame driver
// ============================================================================
// The drawing canvas and its 2D context. CW/CH are the CSS size; activeEq is the
// index of the currently shown equation (0 to 3).
const canvas=document.getElementById('sim-canvas');
const ctx=canvas.getContext('2d');
let CW=100,CH=100,activeEq=0;

// Field colours as hex (for CSS and the legend) and as "r,g,b" (for canvas
// rgba strings). style.css --E, --B, --Q, --Qn, --J and typeset.mjs C match.
const COL={E:'#ffa552',B:'#4fd6ea',Q:'#ff6f61',Qn:'#8c9cff',J:'#ffd166',ink:'#eef3fb'};
const RGB={E:'255,165,82',B:'79,214,234',Q:'255,111,97',Qn:'140,156,255',J:'255,209,102',ink:'238,243,251',dim:'127,145,173'};
// One record per law: numeral, name, the field colour of its left side,
// the plain line under the formulas, and the About text in the panel.
const LAWS=[
  {num:'I',name:'Gauss\'s law',c:COL.E,
   line:'Electric field lines begin on positive charge and end on negative charge.',
   about:'Coulomb found (1785) that the electric force falls off as the inverse square of distance. Gauss showed that this means the total flux through <em>any</em> closed surface depends only on the charge inside it, not on the shape of the surface. Drag the charges and the surface, or change its radius, and watch the enclosed charge.'},
  {num:'II',name:'No magnetic monopoles',c:COL.B,
   line:'Magnetic field lines never end. Each one closes on itself.',
   about:'No one has ever found an isolated magnetic pole. Cut a magnet in half and you get two smaller magnets, each with a north and a south pole. So every field line that leaves a closed surface also comes back in, and the net flux is <em>always</em> zero. Drag the magnet and turn it.'},
  {num:'III',name:'Faraday\'s law',c:COL.E,
   line:'A changing magnetic field makes the electric field curl around it.',
   about:'Faraday found (1831) that a moving magnet drives a current in a coil. The changing flux of B makes an electric field that circulates around it. The minus sign is Lenz\'s law: the induced field opposes the change. Generators, transformers and induction cooktops all work this way.'},
  {num:'IV',name:'Ampère–Maxwell law',c:COL.B,
   line:'Currents, and changing electric fields, make the magnetic field curl around them.',
   about:'Ampère showed (1825) that a current makes a magnetic field that circulates around it. Maxwell (1862) added the term <em>ε₀ ∂E/∂t</em>: a changing electric field acts like a current, even across the empty gap of a capacitor. With that term, the equations predict waves that move at the speed of light. Light is one of them.'},
];

/* ═══ SCALE ═══ */
// The scene is SCENE units across. FX, FY are the pixel center of the free
// area. K is pixels per unit. T is the stroke scale: it follows K but does not
// go below 1, so lines stay visible on small screens.
const SCENE=380;
let FX=50,FY=50,K=1,T=1;
const px=u=>FX+u*K, py=v=>FY+v*K;
function toUnits(x,y){return[(x-FX)/K,(y-FY)/K];}
// Find the free area below the law card and above the legend, and fit the
// scene in it. If the card leaves less than 45% of the height, use the full
// canvas.
function fitScene(){
  const card=document.getElementById('card');
  const pad=Math.max(10,Math.min(CW,CH)*0.02);
  let top=card?card.offsetTop+card.offsetHeight+pad:pad;
  if(CH-top<CH*0.45)top=pad;
  const base=CW<560?64:56;   // the legend and readout row
  const w=CW-2*pad,h=CH-top-base;
  FX=CW/2;FY=top+h/2;
  K=Math.max(0.5,Math.min(w,h)/SCENE);
  T=Math.max(1,K);
}
// Canvas font for a label of base size b px. The size follows K, but it is
// never less than b and never more than 2.4 b.
function font(b,w='500'){return`${w} ${Math.round(Math.min(b*2,Math.max(b,b*K)))}px "IBM Plex Mono", ui-monospace, monospace`;}

// All scene state, grouped by equation, in scene units. Gauss holds the charge
// list and the Gaussian surface; monopoles hold the dipole pose; Faraday holds
// the drive rate and phase clock; Ampère holds the wire list and its clock.
// Angles are in radians.
const STATE={
  // Eq 0: Gauss - charges
  charges:[],
  gaussR:110,
  gaussX:0,gaussY:0,
  // Eq 1: No monopoles - dipole
  dipX:0,dipY:0,dipAngle:0,dipStr:2,
  // Eq 2: Faraday - changing B
  faradayRate:1.0,faradayTime:0,faradayR:80,
  // Eq 3: Ampere - wire current
  ampWires:[],ampTime:0,
  // Shared
  showArrows:true,showTracers:true,
};

// Paint a range input's filled track via the --pct custom property.
function sg(el){const pct=(el.value-el.min)/(el.max-el.min)*100;el.style.setProperty('--pct',pct+'%');}

/* ═══ CARD ═══ */
// The legend items of each law: [label, colour, kind]. kind is 'line' (a
// field), 'dot' (a body) or 'dash' (a surface or loop).
const LEGEND=[
  [['E field',COL.E,'line'],['+ charge',COL.Q,'dot'],['− charge',COL.Qn,'dot'],['Gaussian surface',COL.ink,'dash']],
  [['B field',COL.B,'line'],['north pole',COL.Q,'dot'],['south pole',COL.Qn,'dot'],['closed surface',COL.ink,'dash']],
  [['B, out of or into the page',COL.B,'dot'],['induced E',COL.E,'line']],
  [['B field',COL.B,'line'],['current I',COL.J,'dot'],['E in the gap',COL.E,'line'],['Amperian loop',COL.J,'dash']],
];
// Fill the law list once. Each button shows the numeral, the name and the
// differential form, and takes the colour of its field (--lc).
function buildLaws(){
  const host=document.getElementById('laws');
  const eq=window.MAXWELL_EQ||[];
  host.innerHTML=LAWS.map((l,i)=>`<button class="law" data-eq="${i}" style="--lc:${l.c}" onclick="switchEq(${i})" aria-label="${l.name}">
    <span class="num">${l.num}</span><span class="name">${l.name}</span><span class="form">${eq[i]?eq[i].d:''}</span></button>`).join('');
  document.querySelectorAll('#dockEqs button').forEach(b=>b.style.setProperty('--lc',LAWS[+b.dataset.eq].c));
}
// Fill the card and the legend for the active law, and mark its button.
function renderCard(){
  const l=LAWS[activeEq],eq=(window.MAXWELL_EQ||[])[activeEq];
  document.body.dataset.eq=activeEq;
  document.getElementById('card-num').textContent=l.num;
  document.getElementById('card-name').textContent=l.name;
  document.getElementById('card-eq').innerHTML=eq?eq.d:'';
  document.getElementById('card-int').innerHTML=eq?eq.i:'';
  document.getElementById('card-line').textContent=l.line;
  document.getElementById('legend').innerHTML=LEGEND[activeEq].map(([t,c,k])=>
    `<li><span class="sw${k==='line'?'':' '+k}" style="--sw:${c}"></span>${t}</li>`).join('');
  document.querySelectorAll('.law').forEach(b=>b.classList.toggle('active',+b.dataset.eq===activeEq));
}
// The readout at the base of the canvas. Only a changed string touches the
// DOM, so a frame that shows the same numbers costs nothing.
let readoutHTML='';
function setReadout(html){
  if(html===readoutHTML)return;
  readoutHTML=html;document.getElementById('readout').innerHTML=html;
}
// Signed value with a real minus sign.
const sgn=(v,d=0)=>(v<0?'−':v>0?'+':'')+Math.abs(v).toFixed(d);

// Rebuild the controls and the About text for the active law. Each case
// injects the widgets that law needs, wired through inline handlers that
// write STATE. Each slider also writes its value into the .val span.
/* ═══ CONTROLS PER EQUATION ═══ */
function buildControls(){
  const area=document.getElementById('ctrl-area');
  document.getElementById('about-text').innerHTML=LAWS[activeEq].about;
  switch(activeEq){
    // Gauss: add charges of either sign and resize the Gaussian surface.
    case 0:
      area.innerHTML=`
        <div class="btn-row">
          <button class="tog-btn" onclick="addCharge(1)"><span class="sw" style="--sw:${COL.Q}"></span>Add +q</button>
          <button class="tog-btn" onclick="addCharge(-1)"><span class="sw" style="--sw:${COL.Qn}"></span>Add −q</button>
        </div>
        <div class="mag-row"><span class="mag-row-lbl">Surface</span>
          <input type="range" min="30" max="180" value="${STATE.gaussR}" step="5" aria-label="Surface radius" oninput="STATE.gaussR=+this.value;this.nextElementSibling.textContent=this.value;sg(this)">
          <span class="val">${STATE.gaussR}</span></div>
        <button class="tog-btn quiet" onclick="clearCharges()">Clear the charges</button>`;
      break;
    // No monopoles: set the dipole strength and orientation angle.
    case 1:
      area.innerHTML=`
        <div class="mag-row"><span class="mag-row-lbl">Strength</span>
          <input type="range" min="0.5" max="5" value="${STATE.dipStr}" step="0.1" aria-label="Dipole strength" oninput="STATE.dipStr=+this.value;this.nextElementSibling.textContent=(+this.value).toFixed(1);sg(this)">
          <span class="val">${STATE.dipStr.toFixed(1)}</span></div>
        <div class="mag-row"><span class="mag-row-lbl">Angle</span>
          <input type="range" min="-3.14" max="3.14" value="${STATE.dipAngle}" step="0.05" aria-label="Dipole angle" oninput="STATE.dipAngle=+this.value;this.nextElementSibling.textContent=(this.value*180/Math.PI).toFixed(0)+'°';sg(this)">
          <span class="val">${(STATE.dipAngle*180/Math.PI).toFixed(0)}°</span></div>
        <p class="hint">Drag the magnet across the surface. The flux stays zero.</p>`;
      break;
    // Faraday: set how fast B oscillates and the field region radius.
    case 2:
      area.innerHTML=`
        <div class="mag-row"><span class="mag-row-lbl">Rate</span>
          <input type="range" min="-3" max="3" value="${STATE.faradayRate}" step="0.1" aria-label="Rate" oninput="STATE.faradayRate=+this.value;this.nextElementSibling.textContent=(+this.value).toFixed(1);sg(this)">
          <span class="val">${STATE.faradayRate.toFixed(1)}</span></div>
        <div class="mag-row"><span class="mag-row-lbl">Radius</span>
          <input type="range" min="30" max="140" value="${STATE.faradayR}" step="5" aria-label="Radius" oninput="STATE.faradayR=+this.value;this.nextElementSibling.textContent=this.value;sg(this)">
          <span class="val">${STATE.faradayR}</span></div>
        <p class="hint">Set the rate to 0 and the induced field goes away: only a change of B counts.</p>`;
      break;
    // Ampère–Maxwell: add current-carrying wires (current out of or into plane).
    case 3:
      area.innerHTML=`
        <div class="btn-row">
          <button class="tog-btn" onclick="addAmpWire(1)"><span class="sw" style="--sw:${COL.J}"></span>Wire, I out ⊙</button>
          <button class="tog-btn" onclick="addAmpWire(-1)"><span class="sw" style="--sw:${COL.J}"></span>Wire, I in ⊗</button>
        </div>
        <button class="tog-btn quiet" onclick="STATE.ampWires=[];STATE.ampTracers=[]">Clear the wires</button>
        <p class="hint">Drag a wire left or right. The capacitor below has no current in its gap, but its changing E still makes B.</p>`;
      break;
  }
  area.querySelectorAll('input[type=range]').forEach(sg);
}

// Switch the active law: mark its button and dock button, and refresh the
// card, controls, and scene. The card height can change, so fit the scene
// again.
/* ═══ EQUATION SWITCH ═══ */
function switchEq(idx){
  activeEq=idx;
  document.querySelectorAll('#dockEqs button').forEach(t=>t.classList.toggle('on',+t.dataset.eq===idx));
  renderCard();
  buildControls();
  initEq();
  fitScene();
}

// Seed a tab's scene when it becomes active: place default charges and the
// surface, center the dipole, or place a first wire. Units, so no reseed on
// resize.
/* ═══ INIT PER EQUATION ═══ */
const WIRE_Y=-70;   // the wire row, above the capacitor
function initEq(){
  switch(activeEq){
    case 0:
      if(!STATE.charges.length){
        STATE.charges=[{x:-55,y:0,q:1},{x:55,y:0,q:-1}];
      }
      STATE.gaussX=0;STATE.gaussY=0;
      break;
    case 1:
      STATE.dipX=0;STATE.dipY=0;
      break;
    case 2:
      break;
    case 3:
      if(!STATE.ampWires.length){
        STATE.ampWires=[{x:0,y:WIRE_Y,I:2}];
      }
      break;
  }
}

// Field formulas. All are 2D and use scene units; the numeric constants are
// tuned for visible arrow lengths, not physical units.
/* ═══ PHYSICS ═══ */
// Electric field of a point charge: magnitude q/r² (Coulomb inverse square),
// pointing away from a positive charge. Zero inside r² = 100 to avoid the
// singularity at the charge.
function eField(px,py,cx,cy,q){
  const dx=px-cx,dy=py-cy,r2=dx*dx+dy*dy;
  if(r2<100)return[0,0];
  const r=Math.sqrt(r2),F=q*12000/(r2);
  return[F*dx/r,F*dy/r];
}
// Superpose the field of every charge.
function totalE(px,py){
  let Ex=0,Ey=0;
  for(const c of STATE.charges){const[ex,ey]=eField(px,py,c.x,c.y,c.q);Ex+=ex;Ey+=ey;}
  return[Ex,Ey];
}
// Magnetic dipole field: the standard 3(m·r̂)r̂ − m form, falling off as 1/r³,
// with moment (mx,my) and strength str. Zero near the dipole.
function dipField(px,py,dx0,dy0,mx,my,str){
  const dx=px-dx0,dy=py-dy0,r2=dx*dx+dy*dy;
  if(r2<100)return[0,0];
  const r=Math.sqrt(r2),r3=r2*r,r5=r3*r2;
  const mdotr=mx*dx+my*dy;
  return[(3*mdotr*dx/r5-mx/r3)*str*100000,(3*mdotr*dy/r5-my/r3)*str*100000];
}
// Dipole field at the current pose, moment set by the angle control.
function totalB_dip(px,py){
  const mx=Math.cos(STATE.dipAngle),my=Math.sin(STATE.dipAngle);
  return dipField(px,py,STATE.dipX,STATE.dipY,mx,my,STATE.dipStr);
}
// Magnetic field of a straight wire (Biot–Savart): magnitude μ₀I/2πr, tangent to
// circles around the wire. The returned (−dy, dx)/r direction is that tangent.
function wireB(px,py,wx,wy,I){
  const dx=px-wx,dy=py-wy,r2=dx*dx+dy*dy;
  if(r2<25)return[0,0];
  const r=Math.sqrt(r2),B=I*5/(r*6.2832); // 5x boost for visibility
  return[-dy/r*B,dx/r*B];
}
// Superpose the field of every wire.
function totalB_amp(px,py){
  let Bx=0,By=0;
  for(const w of STATE.ampWires){const[bx,by]=wireB(px,py,w.x,w.y,w.I);Bx+=bx;By+=by;}
  return[Bx,By];
}

// Scene actions invoked from the control buttons.
/* ═══ ACTIONS ═══ */
// Add a charge of sign q near the center with a small random offset.
function addCharge(q){
  STATE.charges.push({x:(Math.random()-0.5)*120,y:(Math.random()-0.5)*120,q});
}
// Remove all charges.
function clearCharges(){STATE.charges=[];}
// Add a wire with current direction dir, searching outward in rings for a free
// slot so wires do not overlap. Stay inside the visible width.
function addAmpWire(dir){
  const half=Math.max(60,(CW/2-30)/K);
  let x=0,placed=false;
  for(let ring=0;ring<8&&!placed;ring++){
    for(const tx of(ring===0?[0]:[-ring*60,ring*60])){
      if(Math.abs(tx)>half)continue;
      let ok=true;
      for(const w of STATE.ampWires)if(Math.abs(tx-w.x)<50){ok=false;break;}
      if(ok){x=tx;placed=true;break;}
    }
  }
  STATE.ampWires.push({x,y:WIRE_Y,I:dir*2});
}

// Draw one field arrow at pixel (x,y) along unit vector (nx,ny), len pixels
// long. rgb is the core color. glow > 0 adds a wide faint stroke under it.
/* ═══ ARROW ═══ */
function arrow(x,y,nx,ny,len,rgb,alpha,glow){
  const ex=x+nx*len,ey=y+ny*len;
  if(glow>0){
    ctx.strokeStyle=`rgba(${rgb},${alpha*glow})`;ctx.lineWidth=3*T;
    ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ex,ey);ctx.stroke();
  }
  ctx.strokeStyle=`rgba(${rgb},${alpha})`;ctx.lineWidth=1.5*T;
  ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ex,ey);ctx.stroke();
  const h=4*T,s=2.5*T;
  if(len>h){
    ctx.beginPath();ctx.moveTo(ex,ey);ctx.lineTo(ex-nx*h-ny*s,ey-ny*h+nx*s);ctx.lineTo(ex-nx*h+ny*s,ey-ny*h-nx*s);ctx.closePath();
    ctx.fillStyle=`rgba(${rgb},${alpha})`;ctx.fill();
  }
}
// Visit an arrow grid that covers the canvas. step is in units. The grid is
// on the scene origin, so it does not move when the window changes shape.
// fn gets the pixel point and the matching unit point.
function eachGridPoint(step,fn){
  const sp=step*K;
  const x0=((FX-sp/2)%sp+sp)%sp,y0=((FY-sp/2)%sp+sp)%sp;
  for(let x=x0;x<CW;x+=sp)for(let y=y0;y<CH;y+=sp)fn(x,y,(x-FX)/K,(y-FY)/K);
}

// Per-frame draw: clear, paint the background grid, then dispatch to the active
// equation's own renderer.
/* ═══ RENDER ═══ */
function render(dt){
  ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.restore();
  ctx.fillStyle='#0a0c12';ctx.fillRect(0,0,CW,CH);
  // Grid, 50 units apart, on the scene origin.
  const g=50*K;
  ctx.strokeStyle='rgba(150,200,255,0.03)';ctx.lineWidth=1;
  ctx.beginPath();
  for(let x=FX%g;x<CW;x+=g){ctx.moveTo(x,0);ctx.lineTo(x,CH);}
  for(let y=FY%g;y<CH;y+=g){ctx.moveTo(0,y);ctx.lineTo(CW,y);}
  ctx.stroke();

  switch(activeEq){
    case 0:renderGauss(dt);break;
    case 1:renderMonopoles(dt);break;
    case 2:renderFaraday(dt);break;
    case 3:renderAmpere(dt);break;
  }
}

// Tab 0. Draw the E field as an arrow grid, the charges, the draggable Gaussian
// surface, and the flux arrows on it. Sum the enclosed charge and show that the
// net flux is zero exactly when the enclosed charge is zero.
/* ── EQ 0: GAUSS'S LAW ── */
function renderGauss(dt){
  ctx.save();ctx.globalCompositeOperation='lighter';
  // E field arrows
  eachGridPoint(28,(x,y,ux,uy)=>{
    const[Ex,Ey]=totalE(ux,uy);
    const Em=Math.sqrt(Ex*Ex+Ey*Ey);if(Em<0.01)return;
    const lv=Math.min(1,Math.log10(1+Em*1.5)/1.5);
    const len=Math.max(3,lv*16)*K;
    arrow(x,y,Ex/Em,Ey/Em,len,RGB.E,Math.max(0.08,lv*0.6),0.25);
  });
  ctx.restore();

  // Charges
  const gx=px(STATE.gaussX),gy=py(STATE.gaussY),gR=STATE.gaussR*K;
  for(const c of STATE.charges){
    ctx.beginPath();ctx.arc(px(c.x),py(c.y),Math.max(12,14*K),0,Math.PI*2);
    ctx.fillStyle=c.q>0?`rgba(${RGB.Q},0.9)`:`rgba(${RGB.Qn},0.9)`;ctx.fill();
    ctx.strokeStyle='rgba(255,255,255,0.3)';ctx.lineWidth=1.5*T;ctx.stroke();
    ctx.font=font(16);ctx.textAlign='center';ctx.textBaseline='middle';
    ctx.fillStyle='#fff';ctx.fillText(c.q>0?'+':'−',px(c.x),py(c.y));
  }

  // Gaussian surface
  ctx.strokeStyle='rgba(238,243,251,0.45)';ctx.lineWidth=1.5*T;ctx.setLineDash([6*T,5*T]);
  ctx.beginPath();ctx.arc(gx,gy,gR,0,Math.PI*2);ctx.stroke();
  ctx.setLineDash([]);
  ctx.font=font(11);ctx.textAlign='center';ctx.textBaseline='alphabetic';
  ctx.fillStyle='rgba(238,243,251,0.55)';ctx.fillText('GAUSSIAN SURFACE',gx,gy-gR-10*T);

  // Compute enclosed charge
  let Qenc=0;
  for(const c of STATE.charges){
    const dx=c.x-STATE.gaussX,dy=c.y-STATE.gaussY;
    if(dx*dx+dy*dy<STATE.gaussR*STATE.gaussR) Qenc+=c.q;
  }
  // Flux arrows on surface
  const nArrows=24;
  ctx.lineWidth=2*T;
  for(let i=0;i<nArrows;i++){
    const a=i/nArrows*Math.PI*2;
    const nr=Math.cos(a),nt=Math.sin(a);
    const[Ex,Ey]=totalE(STATE.gaussX+nr*STATE.gaussR,STATE.gaussY+nt*STATE.gaussR);
    const flux=Ex*nr+Ey*nt; // E·n̂
    const len=Math.min(20,Math.abs(flux)*3)*K;
    const dir=flux>0?1:-1;
    const sx=gx+nr*gR,sy=gy+nt*gR;
    ctx.strokeStyle=flux>0?`rgba(${RGB.Q},0.7)`:`rgba(${RGB.Qn},0.7)`;
    ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+nr*len*dir,sy+nt*len*dir);ctx.stroke();
  }

  setReadout(`<span class="r"><i>Q</i><sub>enc</sub> = <b>${sgn(Qenc)}</b> q</span>`+
    `<span class="r">${STATE.charges.length} charge${STATE.charges.length===1?'':'s'} in the scene</span>`+
    `<span class="note">${Qenc===0?'Net flux through the surface: zero':'Net flux '+(Qenc>0?'outward':'inward')+', Φ = Q<sub>enc</sub>/ε₀'}</span>`);
}

// Tab 1. Draw the dipole B field as arrows, the bar-magnet glyph, and a closed
// surface annotated to show its net magnetic flux is always zero: field lines
// close on themselves, so every line entering the surface also leaves it.
/* ── EQ 1: NO MONOPOLES ── */
function renderMonopoles(dt){
  ctx.save();ctx.globalCompositeOperation='lighter';
  eachGridPoint(24,(x,y,ux,uy)=>{
    const[Bx,By]=totalB_dip(ux,uy);
    const Bm=Math.sqrt(Bx*Bx+By*By);if(Bm<0.001)return;
    const lv=Math.min(1,Math.log10(1+Bm*3)/1.6);
    const len=Math.max(3,lv*14)*K;
    arrow(x,y,Bx/Bm,By/Bm,len,RGB.B,Math.max(0.08,lv*0.6),0.25);
  });
  ctx.restore();

  // Dipole magnet visual, 70 by 28 units.
  const dx=px(STATE.dipX),dy=py(STATE.dipY);
  ctx.save();ctx.translate(dx,dy);ctx.rotate(STATE.dipAngle);ctx.scale(K,K);
  ctx.fillStyle=`rgba(${RGB.Q},0.85)`;ctx.fillRect(0,-14,35,28);
  ctx.fillStyle=`rgba(${RGB.Qn},0.85)`;ctx.fillRect(-35,-14,35,28);
  ctx.strokeStyle='rgba(150,200,255,0.35)';ctx.lineWidth=1.2;ctx.strokeRect(-35,-14,70,28);
  ctx.font='bold 15px "IBM Plex Mono", monospace';ctx.textAlign='center';ctx.textBaseline='middle';
  ctx.fillStyle='#fff';ctx.fillText('N',17,1);ctx.fillText('S',-17,1);
  ctx.restore();

  // Show any closed surface has zero net flux
  const sr=125*K;
  ctx.strokeStyle='rgba(238,243,251,0.4)';ctx.lineWidth=1.5*T;ctx.setLineDash([6*T,5*T]);
  ctx.beginPath();ctx.arc(dx,dy,sr,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);
  setReadout(`<span class="r"><i>Φ</i><sub>B</sub> = <b>0</b></span><span class="note">Every line that leaves the surface comes back in</span>`);
}

// Tab 2. A circular region carries an oscillating B (drawn as into/out-of-plane
// glyphs). Its time derivative induces a circulating E outside the region; the
// induced magnitude tracks |dB/dt| and the circulation sense follows Lenz's law,
// opposing the change.
/* ── EQ 2: FARADAY'S LAW ── */
function renderFaraday(dt){
  // Advance the drive clock, then read off B, its rate, the induced E magnitude,
  // and the Lenz-law circulation direction.
  STATE.faradayTime+=dt*STATE.faradayRate;
  const cx=FX,cy=FY,Ru=STATE.faradayR,R=Ru*K;
  const Bval=Math.sin(STATE.faradayTime*2); // oscillating B
  const dBdt=Math.cos(STATE.faradayTime*2)*STATE.faradayRate*2; // rate of change
  const Eind=Math.abs(dBdt)*0.5; // induced E magnitude ∝ |dB/dt|
  const Edir=dBdt>0?-1:1; // Lenz's law: opposes change

  // B region (filled circle)
  const bAlpha=Math.abs(Bval)*0.3;
  ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);
  ctx.fillStyle=`rgba(${RGB.B},${bAlpha*0.6})`;
  ctx.fill();
  ctx.strokeStyle='rgba(150,200,255,0.3)';ctx.lineWidth=T;ctx.stroke();

  // B glyphs inside (into/out of screen), 25 units apart.
  const bStep=25;
  ctx.font=`bold ${Math.max(10,Math.round(13*K))}px "IBM Plex Mono", monospace`;ctx.textAlign='center';ctx.textBaseline='middle';
  ctx.fillStyle=`rgba(${RGB.B},${0.15+Math.abs(Bval)*0.6})`;
  const n=Math.floor(Ru/bStep);
  for(let i=-n;i<=n;i++)for(let j=-n;j<=n;j++){
    if((i*i+j*j)*bStep*bStep>Ru*Ru)continue;
    ctx.fillText(Bval>0?'⊙':'⊗',cx+i*bStep*K,cy+j*bStep*K);
  }

  // Induced E field (circulating arrows outside B region)
  if(Eind>0.05){
    ctx.save();ctx.globalCompositeOperation='lighter';
    const nE=24;
    for(let i=0;i<nE;i++){
      const a=i/nE*Math.PI*2;
      for(let rr=Ru+20;rr<Ru+110;rr+=30){
        const x=cx+Math.cos(a)*rr*K,y=cy+Math.sin(a)*rr*K;
        const ux=-Math.sin(a)*Edir,uy=Math.cos(a)*Edir;
        // A minimum shaft of 6 units, so a weak field still shows its direction.
        const len=(6+Math.min(12,Eind*12))*K;
        const alpha=Math.min(0.75,0.15+Eind*0.55)*(1-(rr-Ru)/130);
        if(alpha<0.02)continue;
        arrow(x,y,ux,uy,len,RGB.E,alpha,0);
      }
    }
    ctx.restore();
  }

  setReadout(`<span class="r"><i>B</i> = <b>${sgn(Bval,2)}</b> ${Bval>=0?'out of the page':'into the page'}</span>`+
    `<span class="r"><i>∂B/∂t</i> = <b>${sgn(dBdt,2)}</b> &nbsp; |<i>E</i>| = <b>${Eind.toFixed(2)}</b></span>`+
    `<span class="note">${Math.abs(dBdt)<0.1?'B does not change, so no E is induced':'E circulates '+(Edir>0?'counterclockwise':'clockwise')+', against the change'}</span>`);
}

// Tab 3. Two halves of the same law. Part 1: wire currents produce a circulating
// B (the μ₀J term), shown with an arrow grid, streaming tracers that follow the
// field, and an Amperian loop. Part 2: a charging capacitor whose changing E in
// the gap acts as a displacement current (the ε₀∂E/∂t term), circulating B even
// though no charge crosses the gap.
/* ── EQ 3: AMPERE-MAXWELL with tracers + displacement current ── */
function renderAmpere(dt){
  STATE.ampTime=(STATE.ampTime||0)+dt;
  const lh=Math.max(15,15*K);

  // ── PART 1: Wire currents → circulating B (μ₀J term) ──
  if(STATE.ampWires.length>0){
    ctx.save();ctx.globalCompositeOperation='lighter';
    // Dense field arrows
    eachGridPoint(24,(x,y,ux,uy)=>{
      const[Bx,By]=totalB_amp(ux,uy);
      const Bm=Math.sqrt(Bx*Bx+By*By);if(Bm<0.0005)return;
      const lv=Math.min(1,Math.log10(1+Bm*30)/1.6);
      const len=Math.max(3,lv*16)*K;
      arrow(x,y,Bx/Bm,By/Bm,len,RGB.B,Math.max(0.08,Math.min(0.6,lv*0.7)),0.3);
    });

    // Streaming tracers around each wire, in units.
    if(!STATE.ampTracers)STATE.ampTracers=[];
    for(const w of STATE.ampWires){
      if(Math.random()<0.3){
        const a=Math.random()*Math.PI*2,r=20+Math.random()*90;
        STATE.ampTracers.push({x:w.x+Math.cos(a)*r,y:w.y+Math.sin(a)*r,trail:[],age:0,maxAge:2+Math.random()*2});
      }
    }
    const speed=100;
    const [uL,uT]=toUnits(-10,-10),[uR,uB]=toUnits(CW+10,CH+10);
    for(let i=STATE.ampTracers.length-1;i>=0;i--){
      const tr=STATE.ampTracers[i];tr.age+=dt;
      const[Bx,By]=totalB_amp(tr.x,tr.y);
      const Bm=Math.sqrt(Bx*Bx+By*By);
      if(Bm>1e-6){tr.x+=(Bx/Bm)*speed*dt;tr.y+=(By/Bm)*speed*dt;}
      tr.trail.unshift([tr.x,tr.y]);
      if(tr.trail.length>20)tr.trail.pop();
      if(tr.age>tr.maxAge||tr.x<uL||tr.x>uR||tr.y<uT||tr.y>uB){STATE.ampTracers.splice(i,1);continue;}
      // Draw trail
      const tl=tr.trail.length;if(tl<2)continue;
      const ageA=tr.age<0.1?tr.age/0.1:tr.age>tr.maxAge*0.7?(tr.maxAge-tr.age)/(tr.maxAge*0.3):1;
      for(let s=0;s<tl-1;s++){
        const a0=(1-s/20)*ageA;if(a0<0.02)continue;
        ctx.strokeStyle=`rgba(${RGB.B},${a0*0.5})`;ctx.lineWidth=Math.max(0.5,2*a0)*T;
        ctx.beginPath();ctx.moveTo(px(tr.trail[s][0]),py(tr.trail[s][1]));ctx.lineTo(px(tr.trail[s+1][0]),py(tr.trail[s+1][1]));ctx.stroke();
      }
    }
    if(STATE.ampTracers.length>400)STATE.ampTracers.splice(0,STATE.ampTracers.length-400);
    ctx.restore();

    // Amperian loop around first wire
    const w0=STATE.ampWires[0],wx=px(w0.x),wy=py(w0.y);
    const loopR=62*K;
    ctx.strokeStyle=`rgba(${RGB.J},0.5)`;ctx.lineWidth=1.5*T;ctx.setLineDash([6*T,5*T]);
    ctx.beginPath();ctx.arc(wx,wy,loopR,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);
    // ∮B·dl arrows on loop
    const nLoop=16,cw=w0.I>0?1:-1,al=8*K,ah=3*K,aw=2.5*K;
    ctx.fillStyle=`rgba(${RGB.J},0.75)`;ctx.strokeStyle=`rgba(${RGB.J},0.75)`;ctx.lineWidth=2*T;
    for(let i=0;i<nLoop;i++){
      const a=i/nLoop*Math.PI*2+STATE.ampTime*0.5;
      const lx=wx+Math.cos(a)*loopR,ly=wy+Math.sin(a)*loopR;
      const ux=-Math.sin(a)*cw,uy=Math.cos(a)*cw;
      ctx.beginPath();ctx.moveTo(lx,ly);ctx.lineTo(lx+ux*al,ly+uy*al);ctx.stroke();
      ctx.beginPath();ctx.moveTo(lx+ux*al,ly+uy*al);ctx.lineTo(lx+ux*(al-ah)-uy*aw,ly+uy*(al-ah)+ux*aw);ctx.lineTo(lx+ux*(al-ah)+uy*aw,ly+uy*(al-ah)-ux*aw);ctx.closePath();
      ctx.fill();
    }

  }

  // ── PART 2: Displacement current (ε₀ ∂E/∂t term) ──
  // Show a capacitor charging: E grows between plates, B circulates around gap.
  // The capacitor sits below the wire row, in units.
  const cx=px(0),capY=py(105),capGap=46*K,plateW=100*K,plateH=9*K;
  const capCharge=Math.sin(STATE.ampTime*1.5)*0.8; // oscillating charge
  const dEdt=Math.cos(STATE.ampTime*1.5)*1.5*0.8; // rate of change

  // Plates
  ctx.fillStyle='rgba(180,180,200,0.6)';
  ctx.fillRect(cx-plateW/2,capY-capGap/2-plateH,plateW,plateH);
  ctx.fillRect(cx-plateW/2,capY+capGap/2,plateW,plateH);

  // E field between plates (vertical arrows)
  if(Math.abs(capCharge)>0.05){
    const nE=5,dir=capCharge>0?1:-1;
    const eAlpha=Math.abs(capCharge)*0.7;
    const hh=4*K,hw=3*K;
    ctx.strokeStyle=`rgba(${RGB.E},${eAlpha})`;ctx.fillStyle=`rgba(${RGB.E},${eAlpha})`;ctx.lineWidth=2*T;
    for(let i=0;i<nE;i++){
      const ex=cx-plateW/3+i*(plateW*2/3)/(nE-1);
      ctx.beginPath();ctx.moveTo(ex,capY-capGap/2+2*K);ctx.lineTo(ex,capY+capGap/2-2*K);ctx.stroke();
      const tip=capY+dir*(capGap/2-2*K),ay2=tip-dir*hh;
      ctx.beginPath();ctx.moveTo(ex,tip);ctx.lineTo(ex-hw,ay2);ctx.lineTo(ex+hw,ay2);ctx.closePath();ctx.fill();
    }
    ctx.font=font(13);ctx.textAlign='center';ctx.textBaseline='middle';
    ctx.fillText('E',cx+plateW/2+16*K,capY);
  }

  // Displacement current B circulation (when ∂E/∂t ≠ 0)
  if(Math.abs(dEdt)>0.1){
    ctx.save();ctx.globalCompositeOperation='lighter';
    const bAlpha=Math.min(0.7,Math.abs(dEdt)*0.45);
    const bDir=dEdt>0?1:-1;
    const bR=capGap*0.9;
    const nB=14;
    ctx.strokeStyle=`rgba(${RGB.B},${bAlpha})`;ctx.fillStyle=`rgba(${RGB.B},${bAlpha})`;ctx.lineWidth=2*T;
    for(let i=0;i<nB;i++){
      const a=i/nB*Math.PI*2;
      const bx=cx+Math.cos(a)*bR,by=capY+Math.sin(a)*bR;
      const ux=-Math.sin(a)*bDir*7*K,uy=Math.cos(a)*bDir*7*K;
      ctx.beginPath();ctx.moveTo(bx,by);ctx.lineTo(bx+ux,by+uy);ctx.stroke();
      ctx.beginPath();ctx.moveTo(bx+ux,by+uy);
      ctx.lineTo(bx+ux*0.6-uy*0.3,by+uy*0.6+ux*0.3);
      ctx.lineTo(bx+ux*0.6+uy*0.3,by+uy*0.6-ux*0.3);ctx.closePath();ctx.fill();
    }
    ctx.restore();
  }

  // Label
  ctx.font=font(11);ctx.textAlign='center';ctx.textBaseline='alphabetic';
  ctx.fillStyle='rgba(238,243,251,0.5)';
  ctx.fillText('CAPACITOR',cx,capY-capGap/2-plateH-lh*0.6);

  // Charge labels on plates
  if(Math.abs(capCharge)>0.1){
    ctx.font=`bold ${Math.max(11,Math.round(12*K))}px "IBM Plex Mono", monospace`;ctx.textBaseline='middle';
    ctx.fillStyle=capCharge>0?`rgba(${RGB.Q},0.9)`:`rgba(${RGB.Qn},0.9)`;
    ctx.fillText(capCharge>0?'+ + + +':'− − − −',cx,capY-capGap/2-plateH/2);
    ctx.fillStyle=capCharge>0?`rgba(${RGB.Qn},0.9)`:`rgba(${RGB.Q},0.9)`;
    ctx.fillText(capCharge>0?'− − − −':'+ + + +',cx,capY+capGap/2+plateH/2);
  }

  // Wires (draw on top)
  const wr=Math.max(14,16*K),m=wr*0.42;
  for(const w of STATE.ampWires){
    const x=px(w.x),y=py(w.y);
    ctx.beginPath();ctx.arc(x,y,wr,0,Math.PI*2);
    ctx.fillStyle='rgba(20,25,40,0.95)';ctx.fill();
    ctx.strokeStyle=`rgba(${RGB.J},0.7)`;ctx.lineWidth=2*T;ctx.stroke();
    ctx.fillStyle=COL.J;
    if(w.I>0){ctx.beginPath();ctx.arc(x,y,wr*0.36,0,Math.PI*2);ctx.fill();}
    else{ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=2.5*T;ctx.beginPath();ctx.moveTo(x-m,y-m);ctx.lineTo(x+m,y+m);ctx.moveTo(x+m,y-m);ctx.lineTo(x-m,y+m);ctx.stroke();}
    ctx.font=font(13);ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.fillStyle='rgba(255,255,255,0.8)';
    ctx.fillText((w.I>0?'+':'')+w.I.toFixed(0)+'A',x,y-wr-lh*0.45);
    // Direction label
    ctx.font=font(11,'normal');ctx.fillStyle='rgba(255,255,255,0.55)';ctx.textBaseline='top';
    ctx.fillText(w.I>0?'out ⊙':'into ⊗',x,y+wr+lh*0.3);
  }

  const Ienc=STATE.ampWires.length?STATE.ampWires[0].I:0;
  setReadout((STATE.ampWires.length?`<span class="r">loop: <i>I</i><sub>enc</sub> = <b>${sgn(Ienc)}</b> A</span>`:'')+
    `<span class="r">gap: <i>∂E/∂t</i> = <b>${sgn(dEdt,2)}</b></span>`+
    `<span class="note">${Math.abs(dEdt)>0.1?'No charge crosses the gap, but B still circulates':'E is not changing, so the gap makes no B'}</span>`);
}

// Pointer dragging. onDown picks the nearest draggable object for the active tab
// (a charge or the surface, the dipole, or a wire); onMove updates its position;
// release clears the grab. getPos maps a mouse or touch event to scene units.
// The pick radius is at least 24px, so a finger can hit small objects.
/* ═══ DRAG ═══ */
let dragObj=null,dragOff=[0,0];
function getPos(e){const r=canvas.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return toUnits(t.clientX-r.left,t.clientY-r.top);}
canvas.addEventListener('mousedown',onDown);canvas.addEventListener('touchstart',onDown,{passive:false});
function onDown(e){
  e.preventDefault();const[x,y]=getPos(e);
  const hit=(u)=>Math.max(u,24/K)**2;
  if(activeEq===0){
    // Drag charges or gaussian surface
    for(const c of STATE.charges){if((x-c.x)**2+(y-c.y)**2<hit(20)){dragObj={type:'charge',ref:c};dragOff=[c.x-x,c.y-y];return;}}
    if((x-STATE.gaussX)**2+(y-STATE.gaussY)**2<(STATE.gaussR+20)**2){dragObj={type:'gauss'};dragOff=[STATE.gaussX-x,STATE.gaussY-y];return;}
  }
  if(activeEq===1){
    if((x-STATE.dipX)**2+(y-STATE.dipY)**2<hit(40)){dragObj={type:'dip'};dragOff=[STATE.dipX-x,STATE.dipY-y];return;}
  }
  if(activeEq===3){
    for(const w of STATE.ampWires){if((x-w.x)**2+(y-w.y)**2<hit(22)){dragObj={type:'ampw',ref:w};dragOff=[w.x-x,0];return;}}
  }
}
window.addEventListener('mousemove',onMove);window.addEventListener('touchmove',onMove,{passive:false});
function onMove(e){
  if(!dragObj)return;e.preventDefault();const[x,y]=getPos(e);
  switch(dragObj.type){
    case'charge':dragObj.ref.x=x+dragOff[0];dragObj.ref.y=y+dragOff[1];break;
    case'gauss':STATE.gaussX=x+dragOff[0];STATE.gaussY=y+dragOff[1];break;
    case'dip':STATE.dipX=x+dragOff[0];STATE.dipY=y+dragOff[1];break;
    case'ampw':dragObj.ref.x=x+dragOff[0];break;
  }
}
window.addEventListener('mouseup',()=>dragObj=null);
window.addEventListener('touchend',()=>dragObj=null);

// Phone sheet. The dock button opens and closes the panel. A tap on the grip
// switches half and full height. A drag up gives full height. A drag down
// gives half height, then closes. On wide screens the panel is always open.
/* ═══ PHONE SHEET ═══ */
const PHONE_Q=window.matchMedia('(max-width:768px), (max-height:500px) and (pointer:coarse)');
const panel=document.getElementById('panel'),dockPanel=document.getElementById('dockPanel');
function setOpen(open){
  panel.classList.toggle('open',open);
  if(!open)panel.classList.remove('full');
  dockPanel.classList.toggle('on',open);
  dockPanel.setAttribute('aria-expanded',String(open));
}
dockPanel.addEventListener('click',()=>setOpen(!panel.classList.contains('open')));
setOpen(false);
PHONE_Q.addEventListener('change',()=>setOpen(false));
{
  const grip=document.getElementById('sheetGrip');
  let gripY=null;
  grip.addEventListener('pointerdown',e=>{gripY=e.clientY;try{grip.setPointerCapture(e.pointerId);}catch(x){}});
  grip.addEventListener('pointerup',e=>{
    if(gripY===null)return;
    const dy=e.clientY-gripY;gripY=null;
    if(Math.abs(dy)<8)panel.classList.toggle('full');
    else if(dy<-40)panel.classList.add('full');
    else if(dy>40){if(panel.classList.contains('full'))panel.classList.remove('full');else setOpen(false);}
  });
  grip.addEventListener('pointercancel',()=>{gripY=null;});
}

// Fit the canvas to its wrapper and scale the backing store by device pixel
// ratio (capped at 2). Then fit the scene to the free area. A change to the
// wrapper or to the card height calls resize again.
/* ═══ RESIZE ═══ */
function resize(){
  const w=document.getElementById('canvas-wrap');
  CW=w.clientWidth;CH=w.clientHeight;
  if(CW<10)CW=300;if(CH<10)CH=300;
  const dpr=Math.min(devicePixelRatio,2);
  canvas.width=Math.round(CW*dpr);canvas.height=Math.round(CH*dpr);
  ctx.setTransform(dpr,0,0,dpr,0,0);
  fitScene();
}
if(window.ResizeObserver){
  const ro=new ResizeObserver(()=>resize());
  ro.observe(document.getElementById('canvas-wrap'));
  ro.observe(document.getElementById('card'));
}else window.addEventListener('resize',resize);

// The animation loop: measure the frame delta and render the active law.
/* ═══ LOOP ═══ */
let lastTime=0;
function loop(time){
  requestAnimationFrame(loop);
  const dt=Math.min((time-lastTime)/1000,0.05);lastTime=time;
  render(dt);
}

// Boot after a short delay so layout settles: size the canvas, open the first
// equation, and start the loop. Fit again when the web fonts load, because
// the card height changes.
/* ═══ INIT ═══ */
setTimeout(()=>{
  buildLaws();
  resize();
  switchEq(0);
  requestAnimationFrame(loop);
},50);
if(document.fonts&&document.fonts.ready)document.fonts.ready.then(()=>fitScene());
