// ============================================================================
//  MAXWELL'S EQUATIONS  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the four laws with MathJax into static SVG and writes
//  equations.js. The page then shows the same glyph outlines in each
//  browser. KaTeX HTML output broke in Safari (see hydrogen-table).
//
//  Each law has two forms: the differential form (large, in the card over
//  the canvas and small in the law list) and the integral form (the line
//  under it). The field symbols carry the field colours of the canvas:
//  E amber, B cyan, charge coral, current gold. The constants stay ink.
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/maxwells-equations/typeset.mjs
//  The script finds equations.js next to itself.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      colours ......... "const C"      field colours, the same as main.js
//      formulas ........ "const TEX"    the TeX source of each form
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

// Field colours. main.js COL uses the same values.
const C = { E: '#ffa552', B: '#4fd6ea', Q: '#ff6f61', J: '#ffd166' };
const E = String.raw`{\color{${C.E}}{\mathbf{E}}}`;
const B = String.raw`{\color{${C.B}}{\mathbf{B}}}`;
const col = (c, t) => String.raw`{\color{${c}}{${t}}}`;

const TEX = [
  { d: String.raw`\nabla\cdot ${E} = \frac{${col(C.Q, String.raw`\rho`)}}{\varepsilon_0}`,
    i: String.raw`\oint_{S} ${E}\cdot d\mathbf{A} = \frac{${col(C.Q, String.raw`Q_{\text{enc}}`)}}{\varepsilon_0}` },
  { d: String.raw`\nabla\cdot ${B} = 0`,
    i: String.raw`\oint_{S} ${B}\cdot d\mathbf{A} = 0` },
  { d: String.raw`\nabla\times ${E} = -\frac{\partial ${B}}{\partial t}`,
    i: String.raw`\oint_{C} ${E}\cdot d\boldsymbol{\ell} = -\frac{d${col(C.B, String.raw`\Phi_B`)}}{dt}` },
  { d: String.raw`\nabla\times ${B} = \mu_0 ${col(C.J, String.raw`\mathbf{J}`)} + \mu_0\varepsilon_0\frac{\partial ${E}}{\partial t}`,
    i: String.raw`\oint_{C} ${B}\cdot d\boldsymbol{\ell} = \mu_0 ${col(C.J, String.raw`I_{\text{enc}}`)} + \mu_0\varepsilon_0\frac{d${col(C.E, String.raw`\Phi_E`)}}{dt}` },
];

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'color', 'boldsymbol'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
// Ink glyphs use currentColor, so CSS sets their colour.
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  const label = tex.replace(/\\color\{#[0-9a-f]+\}/gi, '').replace(/"/g, '&quot;');
  s = s.replace('<svg ', `<svg role="img" aria-label="${label}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = TEX.map(f => ({ d: svg(f.d), i: svg(f.i) }));
const js = `// ============================================================================
//  MAXWELL'S EQUATIONS  ·  equation SVG  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  window.MAXWELL_EQ[i] = { d: differential form, i: integral form } for
//  law i (0 Gauss, 1 no monopoles, 2 Faraday, 3 Ampere-Maxwell).
// ============================================================================
window.MAXWELL_EQ = ${JSON.stringify(out)};
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
