// ============================================================================
//  MAXWELL'S EQUATIONS  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the four laws with MathJax into static SVG and writes
//  equations.js. The page then shows the same glyph outlines in each
//  browser. KaTeX HTML output broke in Safari (see hydrogen-table).
//
//  Each law has two forms: the differential form (large, in the card over
//  the canvas and small in the law list) and the integral form (the line
//  under it). Each field symbol is wrapped in \class{mN}{...}. MathJax
//  keeps the class on the SVG group, and lib/sci.css gives .m1 to .m6 a
//  color. main.js COL uses the same values, so a symbol has the color of
//  its field on the canvas. The constants stay ink.
//    m2  electric field E, flux Φ_E      m1  magnetic field B, flux Φ_B
//    m4  charge ρ, Q_enc                 m5  current J, I_enc
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/maxwells-equations/typeset.mjs
//  The script finds equations.js next to itself.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      colors .......... "const K"      symbol -> .mN class map
//      label symbols ... "const SYM"    inline symbols for control labels
//      formulas ........ "const TEX"    the TeX source of each form
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

// Symbol classes. lib/sci.css colors them; main.js COL uses the same values.
const K = { E: 'm2', B: 'm1', Q: 'm4', J: 'm5' };
const col = (c, t) => String.raw`\class{${c}}{${t}}`;
const E = col(K.E, String.raw`\mathbf{E}`);
const B = col(K.B, String.raw`\mathbf{B}`);
const C = K;

const TEX = [
  { d: String.raw`\nabla\cdot ${E} = \frac{${col(C.Q, String.raw`\rho`)}}{\varepsilon_0}`,
    i: String.raw`\oint_{S} ${E}\cdot d\mathbf{A} = \frac{${col(C.Q, String.raw`Q_{\text{enc}}`)}}{\varepsilon_0}` },
  { d: String.raw`\nabla\cdot ${B} = 0`,
    i: String.raw`\oint_{S} ${B}\cdot d\mathbf{A} = 0` },
  { d: String.raw`\nabla\times ${E} = -\frac{\partial ${B}}{\partial t}`,
    i: String.raw`\oint_{C} ${E}\cdot d\boldsymbol{\ell} = -\frac{d${col(C.B, String.raw`\Phi_B`)}}{dt}` },
  { d: String.raw`\nabla\times ${B} = \mu_0 ${col(C.J, String.raw`\mathbf{J}`)} + \mu_0\varepsilon_0\frac{\partial ${E}}{\partial t}`,
    i: String.raw`\oint_{C} ${B}\cdot d\boldsymbol{\ell} = \mu_0 ${col(C.J, String.raw`I_{\text{enc}}`)} + \mu_0\varepsilon_0\frac{d${col(C.E, String.raw`\Phi_E`)}}{dt}` },
];

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'html', 'boldsymbol'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
// Ink glyphs use currentColor, so CSS sets their colour.
function svg(tex, display = true) {
  const node = doc.convert(tex, { display });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  const label = tex.replace(/\\class\{m\d\}/g, '').replace(/"/g, '&quot;');
  s = s.replace('<svg ', `<svg role="img" aria-label="${label}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = TEX.map(f => ({ d: svg(f.d), i: svg(f.i) }));
// Control label symbols (inline). main.js puts them before the label text.
const SYM = { dBdt: String.raw`\partial ${col(K.B, 'B')}/\partial t`, q: col(K.Q, 'q'), I: col(K.J, 'I') };
const sym = Object.fromEntries(Object.entries(SYM).map(([k, t]) => [k, svg(t, false)]));
const js = `// ============================================================================
//  MAXWELL'S EQUATIONS  ·  equation SVG  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  window.MAXWELL_EQ[i] = { d: differential form, i: integral form } for
//  law i (0 Gauss, 1 no monopoles, 2 Faraday, 3 Ampere-Maxwell).
//  window.MAXWELL_SYM holds inline symbols for the control labels.
//  Symbol colors are the .m1 to .m6 classes of lib/sci.css.
// ============================================================================
window.MAXWELL_EQ = ${JSON.stringify(out)};
window.MAXWELL_SYM = ${JSON.stringify(sym)};
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
