// ============================================================================
//  MATERIAL STUDIO  ·  export/engines/unreal.js — the Unreal import script
// ────────────────────────────────────────────────────────────────────────────
//  unrealScript writes import_<name>.py for the Unreal Python plugin. The
//  script imports each texture with its sRGB and compression setting, then
//  builds M_<name> with every map connected (BumpOffset for the height).
//
//  GREP TARGETS
//      pyStr  unrealScript  TEXTURES  sampler_type  BLEND_MODE
// ============================================================================
import { f } from '../format.js';

function pyStr(s) { return JSON.stringify(String(s)); }
export function unrealScript(o, sc, u, files) {
  const tex = files.map(fi => {
    const comp = fi.key === 'normal' ? 'TC_NORMALMAP' : fi.key === 'height' ? (fi.bits === 16 ? 'TC_GRAYSCALE' : 'TC_GRAYSCALE') : (fi.key === 'orm' || fi.key === 'clearcoat') ? 'TC_MASKS' : 'TC_DEFAULT';
    return `    ${pyStr(fi.key)}: (${pyStr(fi.name)}, ${fi.color === 'sRGB' ? 'True' : 'False'}, ${pyStr(comp)}),`;
  }).join('\n');
  const blend = sc.alphaMode === 'mask' ? 'BLEND_MASKED' : sc.alphaMode === 'blend' ? 'BLEND_TRANSLUCENT' : 'BLEND_OPAQUE';
  return `# -*- coding: utf-8 -*-
# Unreal Editor import script, generated by Stella Nova PBR Material Studio.
#
# Use: Unreal Editor > Tools > Execute Python Script... and pick this file.
# The Python Editor Script Plugin must be on (Edit > Plugins > Python).
# The script imports the textures next to it with the correct compression
# and sRGB settings, then builds M_${o.name} with every map connected.
# Edit DEST to change the content folder. Run it again to update in place.
import os
import unreal

MATERIAL_NAME = ${pyStr('M_' + o.name)}
DEST = ${pyStr(o.unrealDest.replace(/\{name\}/g, o.name))}
UV_TILING = ${f(o.uvScale)}
EMISSIVE_STRENGTH = ${f(sc.emissiveStrength * (u?.emissiveScale ?? 1))}
HEIGHT_RATIO = ${f(Math.min(0.1, 2 * sc.displacementScale))}
USE_PARALLAX = ${files.some(x => x.key === 'height') ? 'True' : 'False'}
BLEND_MODE = ${pyStr(blend)}
OPACITY_CLIP = ${f(sc.alphaCutoff)}
TWO_SIDED = ${sc.doubleSided ? 'True' : 'False'}
USE_OPACITY = ${u?.opacity || sc.alphaMode !== 'opaque' ? 'True' : 'False'}

# key: (file name, sRGB, compression setting)
TEXTURES = {
${tex}
}

try:
    HERE = os.path.dirname(os.path.abspath(__file__))
except NameError:
    HERE = os.getcwd()

asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
mel = unreal.MaterialEditingLibrary
eal = unreal.EditorAssetLibrary


def import_texture(key):
    fname, srgb, comp = TEXTURES[key]
    path = os.path.join(HERE, fname)
    if not os.path.isfile(path):
        unreal.log_warning("missing texture %s" % path)
        return None
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", path)
    task.set_editor_property("destination_path", DEST)
    task.set_editor_property("destination_name", os.path.splitext(fname)[0])
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("save", False)
    asset_tools.import_asset_tasks([task])
    tex = unreal.load_asset(DEST + "/" + os.path.splitext(fname)[0])
    if tex is None:
        unreal.log_error("import failed: %s" % path)
        return None
    tex.set_editor_property("srgb", srgb)
    tex.set_editor_property("compression_settings", getattr(unreal.TextureCompressionSettings, comp))
    if comp == "TC_NORMALMAP":
        # the file is already DirectX (green flipped); do not flip again
        tex.set_editor_property("flip_green_channel", False)
    eal.save_loaded_asset(tex)
    return tex


def sampler_type(key):
    if key == "normal":
        return unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL
    if key in ("orm", "clearcoat"):
        return unreal.MaterialSamplerType.SAMPLERTYPE_MASKS
    if key == "height":
        return unreal.MaterialSamplerType.SAMPLERTYPE_LINEAR_GRAYSCALE
    return unreal.MaterialSamplerType.SAMPLERTYPE_COLOR


def main():
    textures = {k: import_texture(k) for k in TEXTURES}
    path = DEST + "/" + MATERIAL_NAME
    if eal.does_asset_exist(path):
        mat = unreal.load_asset(path)
        mel.delete_all_material_expressions(mat)
    else:
        mat = asset_tools.create_asset(MATERIAL_NAME, DEST, unreal.Material, unreal.MaterialFactoryNew())

    mat.set_editor_property("blend_mode", getattr(unreal.BlendMode, BLEND_MODE))
    mat.set_editor_property("two_sided", TWO_SIDED)
    if BLEND_MODE == "BLEND_MASKED":
        mat.set_editor_property("opacity_mask_clip_value", OPACITY_CLIP)
    if textures.get("clearcoat"):
        mat.set_editor_property("shading_model", unreal.MaterialShadingModel.MSM_CLEAR_COAT)

    coord = mel.create_material_expression(mat, unreal.MaterialExpressionTextureCoordinate, -1400, 0)
    coord.set_editor_property("u_tiling", UV_TILING)
    coord.set_editor_property("v_tiling", UV_TILING)
    uv = coord

    if USE_PARALLAX and textures.get("height"):
        hs = mel.create_material_expression(mat, unreal.MaterialExpressionTextureSampleParameter2D, -1150, 500)
        hs.set_editor_property("parameter_name", "Height")
        hs.set_editor_property("texture", textures["height"])
        hs.set_editor_property("sampler_type", sampler_type("height"))
        mel.connect_material_expressions(coord, "", hs, "UVs")
        ratio = mel.create_material_expression(mat, unreal.MaterialExpressionScalarParameter, -1150, 700)
        ratio.set_editor_property("parameter_name", "HeightRatio")
        ratio.set_editor_property("default_value", HEIGHT_RATIO)
        bump = mel.create_material_expression(mat, unreal.MaterialExpressionBumpOffset, -900, 400)
        mel.connect_material_expressions(coord, "", bump, "Coordinate")
        mel.connect_material_expressions(hs, "R", bump, "Height")
        mel.connect_material_expressions(ratio, "", bump, "HeightRatioInput")
        uv = bump

    def sample(key, name, x, y):
        tex = textures.get(key)
        if tex is None:
            return None
        e = mel.create_material_expression(mat, unreal.MaterialExpressionTextureSampleParameter2D, x, y)
        e.set_editor_property("parameter_name", name)
        e.set_editor_property("texture", tex)
        e.set_editor_property("sampler_type", sampler_type(key))
        mel.connect_material_expressions(uv, "", e, "UVs")
        return e

    MP = unreal.MaterialProperty
    bc = sample("base", "BaseColor", -600, -300)
    if bc:
        mel.connect_material_property(bc, "RGB", MP.MP_BASE_COLOR)
        if USE_OPACITY and BLEND_MODE == "BLEND_MASKED":
            mel.connect_material_property(bc, "A", MP.MP_OPACITY_MASK)
        elif USE_OPACITY and BLEND_MODE == "BLEND_TRANSLUCENT":
            mel.connect_material_property(bc, "A", MP.MP_OPACITY)
    orm = sample("orm", "ORM", -600, 0)
    if orm:
        mel.connect_material_property(orm, "R", MP.MP_AMBIENT_OCCLUSION)
        mel.connect_material_property(orm, "G", MP.MP_ROUGHNESS)
        mel.connect_material_property(orm, "B", MP.MP_METALLIC)
    nrm = sample("normal", "Normal", -600, 300)
    if nrm:
        mel.connect_material_property(nrm, "RGB", MP.MP_NORMAL)
    em = sample("emissive", "Emissive", -600, 600)
    if em:
        k = mel.create_material_expression(mat, unreal.MaterialExpressionScalarParameter, -600, 800)
        k.set_editor_property("parameter_name", "EmissiveStrength")
        k.set_editor_property("default_value", EMISSIVE_STRENGTH)
        mul = mel.create_material_expression(mat, unreal.MaterialExpressionMultiply, -300, 650)
        mel.connect_material_expressions(em, "RGB", mul, "A")
        mel.connect_material_expressions(k, "", mul, "B")
        mel.connect_material_property(mul, "", MP.MP_EMISSIVE_COLOR)
    cc = sample("clearcoat", "ClearCoat", -600, 900)
    if cc:
        mel.connect_material_property(cc, "R", MP.MP_CUSTOM_DATA0)
        mel.connect_material_property(cc, "G", MP.MP_CUSTOM_DATA1)

    mel.layout_material_expressions(mat)
    mel.recompile_material(mat)
    eal.save_asset(path)
    unreal.log("Stella Nova material imported: %s" % path)


main()
`;
}
