// ============================================================================
//  SMITH CHART  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the reference formulas with MathJax into static SVG and writes
//  equations.js. The page then shows the same glyph outlines in each
//  browser. KaTeX HTML output broke in Safari (see hydrogen-table).
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/smith-chart/typeset.mjs
//  The script finds equations.js next to itself.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      formulas ........ "const TEX"    the TeX source of each formula
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

// Each formula has a slot id in index.html: eq-<key>.
const TEX = {
  gamma: String.raw`\Gamma=\frac{Z_L-Z_0}{Z_L+Z_0}=|\Gamma|\,e^{j\theta}`,
  vswr: String.raw`\mathrm{VSWR}=\frac{1+|\Gamma|}{1-|\Gamma|}`,
  loss: String.raw`\mathrm{RL}=-20\log_{10}|\Gamma|\qquad \mathrm{ML}=-10\log_{10}\!\left(1-|\Gamma|^{2}\right)`,
  zin: String.raw`Z_{in}=Z_0\,\frac{Z_L+jZ_0\tan\beta\ell}{Z_0+jZ_L\tan\beta\ell}`,
  beta: String.raw`\beta\ell=\frac{2\pi\ell}{\lambda}\qquad \lambda=\frac{v_f\,c}{f}`,
  lnetS: String.raw`X_s=-X_L\pm\sqrt{R_L Z_0-R_L^{2}}\quad (R_L\le Z_0)`,
  lnetP: String.raw`B_p=-B_L\pm\sqrt{G_L/Z_0-G_L^{2}}\quad (G_L\le 1/Z_0)`,
  partsS: String.raw`\text{series: }\ L=\frac{X}{\omega}\quad C=\frac{-1}{\omega X}`,
  partsP: String.raw`\text{shunt: }\ C=\frac{B}{\omega}\quad L=\frac{-1}{\omega B}\qquad Q=\frac{|X|}{R}`,
  qw: String.raw`Z_t=\sqrt{Z_0\,R}\qquad R=Z_0\,\mathrm{VSWR}\ \text{or}\ \frac{Z_0}{\mathrm{VSWR}}`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const js = `// ============================================================================
//  SMITH CHART  ·  formula renderer  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  Each formula goes into the element with id eq-<key>, if it is there.
//
//  SECTION MAP   (jump with grep -n "<anchor>" equations.js)
//      formulas ........ "const SVG"  the formulas as SVG text
// ============================================================================
(function(){
  const SVG = ${JSON.stringify(out, null, 2)};
  for (const k in SVG) { const el = document.getElementById('eq-' + k); if (el) el.innerHTML = SVG[k]; }
})();
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
for (const [k, s] of Object.entries(out)) console.log(' ', k, s.length, 'bytes', s.match(/width="[^"]+" height="[^"]+"/)[0]);
