// ============================================================================
//  SMITH CHART  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the reference formulas with MathJax into static SVG and writes
//  equations.js. The page then shows the same glyph outlines in each
//  browser. KaTeX HTML output broke in Safari (see hydrogen-table).
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/smith-chart/typeset.mjs
//  The script finds equations.js next to itself.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      colors .......... "COLOR"        symbol -> .mN class map
//      formulas ........ "const TEX"    the TeX source of each formula
//      label symbols ... "const SYM"    inline symbols for field labels
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

// COLOR. \class{mN}{...} puts a class on the symbol group of the SVG.
// lib/sci.css gives .m1 to .m6 a color. The same class goes on the field
// label that sets the quantity (SYM below), so they show the same color.
//   m3  load impedance Z_L, Z_in, R_L, X_L, G_L, B_L   (impedance)
//   m1  line impedance Z_0
//   m4  reflection coefficient Γ
//   m2  line length ℓ
//   m6  wavelength λ
//   m5  frequency f
const S = String.raw;
const k = (cls, t) => S`\class{${cls}}{${t}}`;
const ZL = k('m3', 'Z_L'), Z0 = k('m1', 'Z_0'), G = k('m4', S`\Gamma`), L = k('m2', S`\ell`), LAM = k('m6', S`\lambda`), F = k('m5', 'f');
const RL = k('m3', 'R_L'), XL = k('m3', 'X_L'), GL = k('m3', 'G_L'), BL = k('m3', 'B_L');

// Each formula has a slot id in index.html: eq-<key>.
const TEX = {
  gamma: S`${G}=\frac{${ZL}-${Z0}}{${ZL}+${Z0}}=|${G}|\,e^{j\theta}`,
  vswr: S`\mathrm{VSWR}=\frac{1+|${G}|}{1-|${G}|}`,
  loss: S`\begin{gathered}\mathrm{RL}=-20\log_{10}|${G}|\\ \mathrm{ML}=-10\log_{10}\!\left(1-|${G}|^{2}\right)\end{gathered}`,
  zin: S`${k('m3', 'Z_{in}')}=${Z0}\,\frac{${ZL}+j${Z0}\tan\beta${L}}{${Z0}+j${ZL}\tan\beta${L}}`,
  beta: S`\beta${L}=\frac{2\pi${L}}{${LAM}}\qquad ${LAM}=\frac{v_f\,c}{${F}}`,
  lnetS: S`\begin{gathered}X_s=-${XL}\pm\sqrt{${RL} ${Z0}-${RL}^{2}}\\ \text{for } ${RL}\le ${Z0}\end{gathered}`,
  lnetP: S`\begin{gathered}B_p=-${BL}\pm\sqrt{${GL}/${Z0}-${GL}^{2}}\\ \text{for } ${GL}\le 1/${Z0}\end{gathered}`,
  partsS: S`\text{series: }\ L=\frac{X}{\omega}\quad C=\frac{-1}{\omega X}`,
  partsP: S`\text{shunt: }\ C=\frac{B}{\omega}\quad L=\frac{-1}{\omega B}`,
  partsQ: S`Q=\frac{|X|}{R}`,
  qw: S`\begin{gathered}Z_t=\sqrt{${Z0}\,R}\\ R=${Z0}\,\mathrm{VSWR}\ \text{or}\ R=\frac{${Z0}}{\mathrm{VSWR}}\end{gathered}`,
};

// Field and readout labels as inline symbols. Each element with
// data-sym="<key>" gets the symbol of that key.
const SYM = {
  Z0: Z0, f: F, vf: 'v_f', len: L, R: k('m3', 'R'), X: k('m3', 'X'), absG: S`|${G}|`,
  Z: k('m3', 'Z'), z: S`z=${k('m3', 'Z')}/${Z0}`, Y: 'Y', G: G, Zin: k('m3', 'Z_{in}'), Gin: k('m4', S`\Gamma_{in}`),
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'html'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex, display = true) {
  const node = doc.convert(tex, { display });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  const label = tex.replace(/\\class\{m\d\}/g, '').replace(/"/g, '&quot;');
  s = s.replace('<svg ', `<svg role="img" aria-label="${label}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const sym = Object.fromEntries(Object.entries(SYM).map(([k, t]) => [k, svg(t, false)]));
const js = `// ============================================================================
//  SMITH CHART  ·  formula renderer  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  Each formula goes into the element with id eq-<key>, if it is there.
//  Each label symbol goes into the elements with data-sym="<key>".
//  Symbol colors are the .m1 to .m6 classes of lib/sci.css.
//
//  SECTION MAP   (jump with grep -n "<anchor>" equations.js)
//      formulas ........ "const SVG"         the formulas as SVG text
//      label symbols ... "SMITH_SYM"         inline symbols for labels
// ============================================================================
(function(){
  const SVG = ${JSON.stringify(out, null, 2)};
  for (const k in SVG) { const el = document.getElementById('eq-' + k); if (el) el.innerHTML = SVG[k]; }
  window.SMITH_SYM = ${JSON.stringify(sym, null, 2)};
  document.querySelectorAll('[data-sym]').forEach(el => { const s = window.SMITH_SYM[el.dataset.sym]; if (s) el.innerHTML = s; });
})();
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
for (const [k, s] of Object.entries(out)) console.log(' ', k, s.length, 'bytes', s.match(/width="[^"]+" height="[^"]+"/)[0]);
