// ============================================================================
//  CIRCULAR POLARIZATION  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the field equations with MathJax into static SVG and writes
//  equations.js. The page shows the same glyph outlines in each browser.
//  KaTeX HTML output broke in Safari (subscripts and fraction denominators
//  stayed on the baseline), so no math library loads at run time.
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/circular-polarization/typeset.mjs
//  The script writes equations.js next to itself.
//
//  Each quantity is wrapped in \class{mN}{...} (TeX html package). MathJax
//  keeps the class on the SVG group, and lib/sci.css gives .m1 to .m6 a
//  fill. The classes are the same as on the other field pages
//  (maxwells-equations, twenty-to-four). main.js COL and CSS use the same
//  values, so a symbol has the color of its part of the scene.
//    m2  electric field E          m1  magnetic field B
//    m4  component ê1, 1           m6  component ê2, e^(−iδ)
//    m3  phase δ                   m5  angular frequency ω
//  E0/r, k, c and û_r stay ink.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      colours ......... "const C"      the .mN class per symbol
//      formulas ........ "const TEX"    the TeX source of each formula
//      label symbols ... "const SYM"    inline symbols for labels
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const C = { E: 'm2', B: 'm1', e1: 'm4', e2: 'm6', d: 'm3', w: 'm5' };
const c = (col, t) => String.raw`\class{${col}}{${t}}`;
const S = String.raw;
const wt = S`${c(C.w, S`\omega`)} t`, dl = c(C.d, S`\delta`);

const TEX = {
  // the outgoing wave on one ray; delta = 90 deg gives the circular case
  // two lines, so the formula fits the panel without a scale-down
  E: S`\begin{aligned}${c(C.E, S`\vec{E}`)}=\frac{E_0}{r}\Big[&\cos(kr-${wt})\,${c(C.e1, S`\hat{e}_1`)}\\&+\cos(kr-${wt}-${dl})\,${c(C.e2, S`\hat{e}_2`)}\Big]\end{aligned}`,
  // B is perpendicular to E and to the ray
  B: String.raw`${c(C.B, String.raw`\vec{B}`)}=\frac{1}{c}\,\hat{u}_r\times${c(C.E, String.raw`\vec{E}`)}`,
  // the Jones vector of the transverse field
  J: S`\mathbf{J}=\frac{1}{\sqrt{2}}\begin{pmatrix}${c(C.e1, '1')}\\[2pt]${c(C.e2, S`e^{-i${dl}}`)}\end{pmatrix}`,
};
// Inline symbols for the legend and the slider labels. main.js puts each
// one into the element with the matching data-sym.
const SYM = {
  E: c(C.E, S`\vec E`), B: c(C.B, S`\vec B`),
  E1: S`${c(C.E, S`\vec E`)}\cdot${c(C.e1, S`\hat e_1`)}`, E2: S`${c(C.E, S`\vec E`)}\cdot${c(C.e2, S`\hat e_2`)}`,
  delta: dl, k: 'k', omega: c(C.w, S`\omega`), chi: S`\chi`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'html'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex, display = true) {
  const node = doc.convert(tex, { display });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/\\class\{m\d\}/g, '').replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const sym = Object.fromEntries(Object.entries(SYM).map(([k, t]) => [k, svg(t, false)]));
const js = `// ============================================================================
//  CIRCULAR POLARIZATION  ·  equation SVG  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  main.js puts EQ.E, EQ.B and EQ.J into #eqE, #eqB and #eqJ, and each
//  SYM entry into the element with the matching data-sym. Symbol colors
//  are the .m1 to .m6 classes of lib/sci.css.
// ============================================================================
export const EQ = ${JSON.stringify(out, null, 1)};
export const SYM = ${JSON.stringify(sym, null, 1)};
`;
writeFileSync(fileURLToPath(new URL('./equations.js', import.meta.url)), js);
console.log('wrote equations.js', Object.keys(out).map(k => k + ' ' + out[k].length + ' B').join(', '));
