// ============================================================================
//  CIRCULAR POLARIZATION  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the field equations with MathJax into static SVG and writes
//  equations.js. The page shows the same glyph outlines in each browser.
//  KaTeX HTML output broke in Safari (subscripts and fraction denominators
//  stayed on the baseline), so no math library loads at run time.
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/circular-polarization/typeset.mjs
//  The script writes equations.js next to itself.
//
//  The colours are the scene colours (const COL in main.js): E amber, B
//  cyan, the e1 component coral, the e2 component blue, E0/r gold.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      colours ......... "const C"      the hex colour per symbol
//      formulas ........ "const TEX"    the TeX source of each formula
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const C = { E: '#ffb84d', B: '#60e0ee', e1: '#ff8a78', e2: '#8aa8ff', amp: '#d4a847', ink: '#e8ecf4' };
const c = (col, t) => String.raw`{\color{${col}}{${t}}}`;

const TEX = {
  // the outgoing wave on one ray; delta = 90 deg gives the circular case
  E: String.raw`${c(C.E, String.raw`\vec{E}`)}=${c(C.amp, String.raw`\frac{E_0}{r}`)}\Big[${c(C.e1, String.raw`\cos(kr-\omega t)\,\hat{e}_1`)}+${c(C.e2, String.raw`\cos(kr-\omega t-\delta)\,\hat{e}_2`)}\Big]`,
  // B is perpendicular to E and to the ray
  B: String.raw`${c(C.B, String.raw`\vec{B}`)}=\frac{1}{c}\,\hat{u}_r\times${c(C.E, String.raw`\vec{E}`)}`,
  // the Jones vector of the transverse field
  J: String.raw`\mathbf{J}=\frac{1}{\sqrt{2}}\begin{pmatrix}${c(C.e1, '1')}\\[2pt]${c(C.e2, String.raw`e^{-i\delta}`)}\end{pmatrix}`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams', 'color'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/\\color\{#[0-9a-f]+\}/g, '').replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const js = `// ============================================================================
//  CIRCULAR POLARIZATION  ·  equation SVG  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  Each formula is static SVG from MathJax, with glyphs as paths. No font
//  or math library loads at run time, so each browser shows the same shape.
//  main.js puts EQ.E, EQ.B and EQ.J into #eqE, #eqB and #eqJ.
// ============================================================================
export const EQ = ${JSON.stringify(out, null, 1)};
`;
writeFileSync(fileURLToPath(new URL('./equations.js', import.meta.url)), js);
console.log('wrote equations.js', Object.keys(out).map(k => k + ' ' + out[k].length + ' B').join(', '));
