// ============================================================================
//  FRQI QUANTUM IMAGE LAB  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the FRQI state equation with MathJax into static SVG and writes
//  equation.js. The State Register panel shows that SVG. KaTeX HTML output
//  broke in Safari (see the hydrogen table): subscripts and fraction
//  denominators stayed on the baseline. SVG paths look the same in each
//  browser.
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/frqi-quantum-image-lab/typeset.mjs
//  The script finds equation.js next to itself.
//
//  SECTION MAP   (jump with grep -n "<anchor>" typeset.mjs)
//      formula ......... "const TEX"    the TeX source
//      svg cleanup ..... "function svg" MathJax output to inline SVG
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const TEX = String.raw`|\varphi\rangle=\frac{1}{\sqrt{N}}\sum_{i=0}^{N-1}\bigl(\cos\theta_i|0\rangle+\sin\theta_i|1\rangle\bigr)\otimes|i\rangle`;

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams'] }), OutputJax: new SVG({ fontCache: 'local' }) });

// MathJax output to inline SVG. The ex sizes stay, so CSS font-size scales
// the formula. aria-hidden is removed and a label with the TeX is added.
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}

const out = svg(TEX);
const js = `// ============================================================================
//  FRQI QUANTUM IMAGE LAB  ·  state equation  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again.
//  EQ_STATE is static SVG from MathJax, with glyphs as paths. It uses
//  currentColor, so the colour of #eq-main sets the ink.
// ============================================================================
export const EQ_STATE = ${JSON.stringify(out)};
`;
const dest = fileURLToPath(new URL('./equation.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes', out.match(/width="[^"]+" height="[^"]+"/)[0]);
