// compute_fractal.wgsl - the fractal iteration loop: hybrid sequence, bailout, c constant,
// iteration weight, analytic DE and the colouring mode.
// Ported from Mandelbulber v2 opencl/engines/compute_fractal.cl ("Fractal" is renamed
// ComputeFractal because the generated struct Fractal holds that name in WGSL).
// Copyright (C) 2017-24 Mandelbulber Team. Authors: Krzysztof Marczak (buddhi1980@gmail.com).
// Mandelbulber is free software under the GNU General Public License v3 or later.
// This port is also GPL-3.0. See COPYING in the page folder.
//
// callFormula(fcase, z, fi, aux) is generated by engine.js: one switch case per formula in use.
// Box folding and spherical folding (basic_foldings.cl), fake lights (orbit trap mode) and
// fractalize texture (cube orbit trap mode) are not ported.
//
// grep: FormulaOut ComputeFractal engSmoothCVector clAnalyticFunction linearDEFunction
//       fractalColoringCl_Standard

struct FormulaOut {
  z: vec4f,
  iters: f32,
  distance: f32,
  colorIndex: f32,
  orbitTrapR: f32,
  maxiter: bool,
}

// enumDEFunctionTypeCl
const linearDEFunction: i32 = 1;
const logarithmicDEFunction: i32 = 2;
const pseudoKleinianDEFunction: i32 = 3;
const josKleinianDEFunction: i32 = 4;
const customDEFunction: i32 = 5;
const maxAxisDEFunction: i32 = 6;

// enumDEAnalyticFunctionCl
const clAnalyticFunctionUndefined: i32 = -1;
const clAnalyticFunctionNone: i32 = 0;
const clAnalyticFunctionLinear: i32 = 1;
const clAnalyticFunctionLogarithmic: i32 = 2;
const clAnalyticFunctionIFS: i32 = 3;
const clAnalyticFunctionPseudoKleinian: i32 = 4;
const clAnalyticFunctionJosKleinian: i32 = 5;
const clAnalyticFunctionCustomDE: i32 = 6;
const clAnalyticFunctionMaxAxis: i32 = 7;

// enumColoringFunctionCl
const clColoringFunctionUndefined: i32 = -1;
const clColoringFunctionDefault: i32 = 0;
const clColoringFunctionABox: i32 = 1;
const clColoringFunctionIFS: i32 = 2;
const clColoringFunctionAmazingSurf: i32 = 3;
const clColoringFunctionABox2: i32 = 4;
const clColoringFunctionDonut: i32 = 5;

// enumFractalColoringCl
const fractalColoringCl_None: i32 = -1;
const fractalColoringCl_Standard: i32 = 0;
const fractalColoringCl_ZDotPoint: i32 = 1;
const fractalColoringCl_Sphere: i32 = 2;
const fractalColoringCl_Cross: i32 = 3;
const fractalColoringCl_Line: i32 = 4;

// SmoothCVector from opencl_algebra.h (engine copy, so the name cannot clash with helpers)
fn engSmoothCVector(v1: vec4f, v2: vec4f, k: f32) -> vec4f {
  let nk = 1.0 - k;
  if (k <= 0.0) { return v1; }
  if (k >= 1.0) { return v2; }
  let length1 = length(v1);
  let length2 = length(v2);
  let lenInterp = length1 * nk + length2 * k;
  let vTemp = v1 * nk + v2 * k;
  let lengthTemp = length(vTemp);
  if (lengthTemp > 0.0) { return (vTemp / lengthTemp) * lenInterp; }
  return v1;
}

fn ComputeFractal(point: vec3f, calcParam: ptr<function, CalcParams>, mode: i32) -> FormulaOut {
  var dist = 0.0;

  var seqLength = P.seqLength;
  if (seqLength <= 0) { seqLength = 1; }

  let point4D = vec4f(point, 0.0);

  var z = vec4f(point, P.initialWAxis);

  var maxN = P.formulaMaxiter;
  if ((*calcParam).normalCalculationMode != 0 && (*calcParam).iterThreshMode != 0) { maxN *= 5; }
  if (mode == calcModeColouring) { maxN *= 4; }

  let initialWAxisColor = z.w;
  let c = z;
  var i: i32 = 0;

  var out: FormulaOut;
  out.maxiter = true;
  out.orbitTrapR = 0.0;
  out.colorIndex = 0.0;

  var colorMin = 1000.0;

  // fractalIndex: slot of the first formula in the sequence (default fractal, initial scale)
  let fractalIndex = SEQ[0];

  var aux: Aux;
  aux.c = c;
  aux.const_c = c;
  aux.old_z = z;
  aux.pos_neg = 1.0;
  aux.r = length(z);
  aux.DE = 1.0;
  aux.DE0 = 0.0;
  aux.dist = 1000.0;
  aux.pseudoKleinianDE = 1.0;
  aux.actualScale = FR[fractalIndex].mandelbox.scale;
  aux.actualScaleA = 0.0;
  aux.color = 1.0;
  aux.colorHybrid = 0.0;
  aux.temp1000 = 1000.0;

  var sequence: i32 = 0;
  var lastZ = vec4f(0.0);
  var lastLastZ = vec4f(0.0);

  let fc = P.material.fractalColoring;

  for (i = 0; i < maxN; i++) {
    sequence = SEQ[min(i, seqLength - 1)];
    let sd = P.slots[sequence];

    aux.i = i;

    lastLastZ = lastZ;
    lastZ = z;

    // temporary vector for weight function
    let tempZ = z;
    let tempAuxDE = aux.DE;
    let tempAuxColor = aux.color;

    if (P.iterationWeight == 0 || sd.formulaWeight > 0.0) {
      z = callFormula(u32(sd.formulaCase), z, u32(sequence), &aux);
    }

    if (aux.r < 0.0) { // DummyIteration ran
      let high = sd.bailout * 10.0;
      z = vec4f(high);
      aux.r = length(z);
      out.distance = 10.0;
      out.iters = 1.0;
      out.z = z;
      out.colorIndex = 0.0;
      return out;
    }

    if (sd.addCConstant != 0) {
      let cm = vec4f(P.constantMultiplier, 0.0);
      if (sd.formulaId == 64 || sd.formulaId == 73) { // aboxMod1, amazingSurf
        if (P.juliaEnabled != 0) {
          let juliaC = vec4f(P.juliaConstant, 0.0) * cm;
          z += vec4f(juliaC.y, juliaC.x, juliaC.z, juliaC.w);
        } else {
          z += vec4f(aux.const_c.y, aux.const_c.x, aux.const_c.z, aux.const_c.w) * cm;
        }
      } else {
        if (P.juliaEnabled != 0) {
          z += vec4f(P.juliaConstant, 0.0) * cm;
        } else {
          z += aux.const_c * cm;
        }
      }
    }

    if (P.iterationWeight != 0 && P.isHybrid != 0) {
      let k = sd.formulaWeight;
      if (k < 1.0) {
        z = engSmoothCVector(tempZ, z, k);
        let kn = 1.0 - k;
        aux.DE = aux.DE * k + tempAuxDE * kn;
        aux.color = aux.color * k + tempAuxColor * kn;
      }
    }

    // calculate r
    aux.r = length(z);

    // escape conditions
    if (sd.checkForBailout != 0) {
      if (mode == calcModeNormal || mode == calcModeDeltaDE1) {
        if (aux.r > sd.bailout) {
          out.maxiter = false;
          break;
        }
        if (sd.useAdditionalBailoutCond != 0) {
          out.maxiter = false;
          if (length(z - lastZ) / aux.r < 0.1 / sd.bailout) { break; }
          if (length(z - lastLastZ) / aux.r < 0.1 / sd.bailout) { break; }
        }
      } else if (mode == calcModeDeltaDE2) {
        if (i == (*calcParam).deltaDEMaxN) { break; }
      } else if (mode == calcModeColouring) {
        var len = 0.0;
        var colorZ = z;
        if (fc.color4dEnabledFalse == 0) { colorZ.w = 0.0; }
        switch (fc.coloringAlgorithm) {
          case 0: { // fractalColoringCl_Standard
            len = length(colorZ);
          }
          case 1: { // fractalColoringCl_ZDotPoint
            len = abs(dot(vec4f(point4D.xyz, initialWAxisColor), colorZ));
          }
          case 2: { // fractalColoringCl_Sphere
            len = abs(length(colorZ - vec4f(point4D.xyz, initialWAxisColor)) - fc.sphereRadius);
          }
          case 3: { // fractalColoringCl_Cross
            len = min(min(abs(colorZ.x), abs(colorZ.y)), abs(colorZ.z));
            if (fc.color4dEnabledFalse != 0) { len = min(len, abs(colorZ.w)); }
          }
          case 4: { // fractalColoringCl_Line
            len = abs(dot(fc.lineDirection, colorZ));
          }
          default: { // fractalColoringCl_None
            len = aux.r;
          }
        }
        if (fc.colorPreV215False == 0) {
          if (sd.formulaId != 8) {
            if (len < colorMin) { colorMin = len; }
            if (aux.r > sd.bailout) { break; }
            if (sd.useAdditionalBailoutCond != 0 && length(z - lastZ) / aux.r < 1e-15) { break; }
          } else { // for Mandelbox
            if (fc.coloringAlgorithm == fractalColoringCl_Standard) {
              if (aux.r > 1e15 || length(z - lastZ) / aux.r < 1e-15) { break; }
            } else {
              if (len < colorMin) { colorMin = len; }
              if (aux.r > sd.bailout || length(z - lastZ) / aux.r < 1e-15) { break; }
            }
          }
        } else { // pre-2.15
          if (sd.formulaId != 8) {
            if (len < colorMin) { colorMin = len; }
            if (aux.r > 1e15 || length(z - lastZ) / aux.r < 1e-15) { break; }
          } else {
            if (aux.r > 1e15 || length(z - lastZ) / aux.r < 1e-15) { break; }
          }
        }
      }
    }
  }

  // calculate estimated distance
  if (mode == calcModeNormal) {
    if (aux.DE > 0.0) {
      if (P.isHybrid != 0) {
        let dft = P.DEFunctionType;
        if (dft == logarithmicDEFunction) {
          if (aux.r > 1.0) {
            dist = 0.5 * aux.r * log(aux.r) / abs(aux.DE);
          } else {
            dist = 0.0;
          }
        } else if (dft == linearDEFunction) {
          dist = (aux.r - P.linearDEOffset) / abs(aux.DE);
        } else if (dft == pseudoKleinianDEFunction) {
          let rxy = length(z.xy);
          dist = max(rxy - aux.pseudoKleinianDE, abs(rxy * z.z) / aux.r) / abs(aux.DE);
        } else if (dft == josKleinianDEFunction) {
          if (FR[sequence].transformCommon.spheresEnabled != 0) {
            z.y = min(z.y, FR[sequence].transformCommon.foldingValue - z.y);
          }
          dist = min(z.y, FR[sequence].analyticDE.tweak005)
            / max(abs(aux.DE), FR[sequence].analyticDE.offset1);
        } else if (dft == customDEFunction) {
          dist = aux.dist;
        } else if (dft == maxAxisDEFunction) {
          let absZ = abs(z);
          let rd = max(absZ.x, max(absZ.y, absZ.z));
          dist = rd / abs(aux.DE);
        }
      } else {
        switch (P.DEAnalyticFunction) {
          case 2: { // clAnalyticFunctionLogarithmic
            if (aux.r > 1.0) {
              dist = 0.5 * aux.r * log(aux.r) / aux.DE;
            } else {
              dist = 0.0;
            }
          }
          case 1: { // clAnalyticFunctionLinear
            dist = aux.r / aux.DE;
          }
          case 3: { // clAnalyticFunctionIFS
            dist = (aux.r - 2.0) / aux.DE;
          }
          case 4: { // clAnalyticFunctionPseudoKleinian
            let rxy = length(z.xy);
            dist = max(rxy - aux.pseudoKleinianDE, abs(rxy * z.z) / aux.r) / aux.DE;
          }
          case 5: { // clAnalyticFunctionJosKleinian
            if (FR[sequence].transformCommon.spheresEnabled != 0) {
              z.y = min(z.y, FR[sequence].transformCommon.foldingValue - z.y);
            }
            dist = min(z.y, FR[sequence].analyticDE.tweak005)
              / max(aux.DE, FR[sequence].analyticDE.offset1);
          }
          case 6: { // clAnalyticFunctionCustomDE
            dist = aux.dist;
          }
          case 7: { // clAnalyticFunctionMaxAxis
            let absZ = abs(z);
            let rd = max(absZ.x, max(absZ.y, absZ.z));
            dist = rd / aux.DE;
          }
          case 0: { // clAnalyticFunctionNone
            dist = -1.0;
          }
          default: { // clAnalyticFunctionUndefined
            dist = aux.r;
          }
        }
      }
    } else {
      dist = aux.r;
    }
  } else if (mode == calcModeColouring) {
    out.colorIndex = CalculateColorIndex(P.isHybrid != 0, aux.r, z, colorMin, aux,
      P.coloringFunction, fractalIndex);
  } else {
    dist = 0.0;
    // needed for JosKleinian fractal to calculate spheres in deltaDE mode
    if (P.DEFunctionType == josKleinianDEFunction) {
      if (FR[sequence].transformCommon.spheresEnabled != 0) {
        z.y = min(z.y, FR[sequence].transformCommon.foldingValue - z.y);
      }
    }
  }

  // end
  if (dist < 0.0) { dist = 0.0; }
  out.distance = dist;
  out.iters = f32(i + 1);
  out.z = z;
  return out;
}
