// ============================================================================
//  BUILD FLOOR  ·  writes floor.js (run by hand: node build-floor.mjs)
// ----------------------------------------------------------------------------
//  For each beam size, find the perturber mass whose best smooth fit leaves
//  a 5 sigma residual peak (the "detection floor" chart). It uses the same
//  engine (lens.js) and default model (model.js) as the page. The page
//  reads the result, because the search takes about a minute.
// ============================================================================
import fs from 'node:fs';
import { experiment, pjMass, R80 } from './lens.js';
import { LENS, LOBES, V0, A0, SNR } from './model.js';

const FWHM = [3, 5, 8, 12, 18, 25, 35, 50, 70, 95, 120];
const lens = { ...LENS, subs: [A0] };
// Noise: peak of the VLBI (5 mas) image over SNR.
const peak = experiment({ lens, lobes: LOBES, sub: V0, fwhm: 5, noise: 1 }).data.reduce((a, b) => Math.max(a, b), 0);
const noise = peak / SNR;
const at = (fwhm, m80) => {
  const m = m80 / pjMass(R80, 1, V0.rt);
  return experiment({ lens, lobes: LOBES, sub: { ...V0, m }, fwhm, noise, n: 96 }).max;
};
const rows = [];
for (const f of FWHM) {
  let lo = 3, hi = 10;                       // log10 m80
  for (let k = 0; k < 14; k++) { const mid = (lo + hi) / 2; if (at(f, 10 ** mid) > 5) hi = mid; else lo = mid; }
  const m80 = 10 ** ((lo + hi) / 2);
  rows.push({ fwhm: f, m80: +m80.toPrecision(3) });
  console.log(`fwhm ${f} mas  m80 ${m80.toExponential(2)}`);
}
const out = `// Generated by build-floor.mjs. Do not edit.\n// 5 sigma floor of m80 (Msun) per beam FWHM (mas), peak noise ${noise.toExponential(3)}.\nexport const NOISE = ${+noise.toPrecision(4)};\nexport const FLOOR = ${JSON.stringify(rows)};\n`;
fs.writeFileSync(new URL('./floor.js', import.meta.url), out);
console.log('wrote floor.js');
