// Generated by build-floor.mjs. Do not edit.
// 5 sigma floor of m80 (Msun) per beam FWHM (mas), peak noise 1.697e-3.
export const NOISE = 0.001697;
export const FLOOR = [{"fwhm":3,"m80":74400},{"fwhm":5,"m80":92800},{"fwhm":8,"m80":135000},{"fwhm":12,"m80":219000},{"fwhm":18,"m80":319000},{"fwhm":25,"m80":457000},{"fwhm":35,"m80":706000},{"fwhm":50,"m80":1250000},{"fwhm":70,"m80":2600000},{"fwhm":95,"m80":4670000},{"fwhm":120,"m80":7050000}];
