#!/usr/bin/env python3
"""Write the homepage commit heatmap data from a private git repository.

The script asks git for one field per commit: the author date (YYYY-MM-DD).
It reads no hash, subject, body, author, path or diff. The output holds only
a start date and one commit count per day, so no content of the repository
goes to the site.

Window: 53 weeks. The first column starts on the Sunday on or before the day
364 days before the end date. The end date is today, or --end.

Usage:
  python3 tools/commit-counts.py <repo> > stella-nova/pages/home/commit-data.js
  python3 tools/commit-counts.py <repo> --end 2026-10-01 > ...
"""
import argparse
import datetime as dt
import subprocess
import sys

p = argparse.ArgumentParser()
p.add_argument("repo")
p.add_argument("--end", help="last day (YYYY-MM-DD), default today")
a = p.parse_args()

end = dt.date.fromisoformat(a.end) if a.end else dt.date.today()
first = end - dt.timedelta(days=364)
start = first - dt.timedelta(days=(first.weekday() + 1) % 7)  # back to Sunday
n = (end - start).days + 1

# All local branches. Git counts a commit on two branches once.
out = subprocess.run(
    ["git", "-C", a.repo, "log", "--branches", "--format=%ad", "--date=short",
     f"--since={start.isoformat()} 00:00"],
    check=True, capture_output=True, text=True).stdout
counts = [0] * n
for line in out.split():
    i = (dt.date.fromisoformat(line) - start).days
    if 0 <= i < n:
        counts[i] += 1

sys.stdout.write(f"""// ============================================================================
//  COMMIT DATA  ·  daily commit counts for the hero heatmap
// ----------------------------------------------------------------------------
//  Generated by tools/commit-counts.py from the Stella Nova game repository.
//  Do not edit by hand. The file holds only a start date (a Sunday) and one
//  commit count per day. It holds no hash, message, author or file content.
//  main.js (buildCommits) draws it.
// ============================================================================
(window.Observatory = window.Observatory || {{}}).COMMITS = {{
  start: '{start.isoformat()}',
  end: '{end.isoformat()}',
  days: [{','.join(map(str, counts))}],
}};
""")
print(f"{start} .. {end}: {sum(counts)} commits, {sum(1 for c in counts if c)} active days, peak {max(counts)}", file=sys.stderr)
