// ============================================================================
//  SPHERE TRACING LAB  ·  formula typesetter  (Node, run by hand)
// ----------------------------------------------------------------------------
//  Typesets the explainer formulas with MathJax into static SVG and writes
//  equations.js. The page shows the same glyph outlines in each browser and
//  loads no math library at run time. (KaTeX HTML output breaks in Safari.)
//
//  RUN (MathJax is not a dependency of the site):
//      cd "$(mktemp -d)" && npm i mathjax-full@3 && \
//        NODE_PATH="$PWD/node_modules" node \
//        <repo>/stella-nova/pages/sdf-lab/typeset.mjs
//  The script writes equations.js next to itself.
// ============================================================================
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.NODE_PATH + '/');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
require('mathjax-full/js/input/tex/AllPackages.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const TEX = {
  step: String.raw`t_{n+1} = t_n + d(\mathbf{o} + t_n\,\mathbf{r})`,
  bound: String.raw`\begin{gathered}\bigl|d(\mathbf{p}) - d(\mathbf{q})\bigr| \le L\,\lVert\mathbf{p}-\mathbf{q}\rVert\\ t_{n+1} = t_n + d/L\end{gathered}`,
  relax: String.raw`\begin{gathered}t_{n+1} = t_n + \omega\, d_n\\ d_n + d_{n+1} < \omega\, d_n \;\Rightarrow\; t_{n+1} = t_n + d_n,\ \omega = 1\end{gathered}`,
  smin: String.raw`\begin{gathered}h = \max(k - |a-b|,\,0)/k\\ \operatorname{smin}(a,b) = \min(a,b) - \tfrac{k}{4}\,h^{2}\end{gathered}`,
  shadow: String.raw`s = \min_i\, \frac{k\, d_i}{t_i}`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: ['base', 'ams'] }), OutputJax: new SVG({ fontCache: 'local' }) });
function svg(tex) {
  const node = doc.convert(tex, { display: true });
  let s = adaptor.innerHTML(node).replace(/ aria-hidden="true"/, '');
  s = s.replace('<svg ', `<svg role="img" aria-label="${tex.replace(/"/g, '&quot;')}" `);
  if (s.includes('merror')) throw new Error('TeX error in: ' + tex);
  return s;
}
const out = Object.fromEntries(Object.entries(TEX).map(([k, t]) => [k, svg(t)]));
const js = `// ============================================================================
//  SPHERE TRACING LAB  ·  equations.js  (GENERATED by typeset.mjs)
// ----------------------------------------------------------------------------
//  Do not edit by hand. Change the TeX in typeset.mjs and run it again. Each
//  formula is static MathJax SVG with glyphs as paths. mountEquations() puts
//  each one into the element with id "eq-<key>".
// ============================================================================
export const EQ = ${JSON.stringify(out, null, 2)};
export function mountEquations() {
  for (const [k, s] of Object.entries(EQ)) { const el = document.getElementById('eq-' + k); if (el) el.innerHTML = s; }
}
`;
const dest = fileURLToPath(new URL('./equations.js', import.meta.url));
writeFileSync(dest, js);
console.log('wrote', dest, js.length, 'bytes');
for (const [k, s] of Object.entries(out)) console.log(' ', k, s.length, 'bytes', s.match(/width="[^"]+" height="[^"]+"/)[0]);
